- python/sparknlp/base.py
- python/test/annotators.py
- src/main/scala/com/jsl/nlp/Annotation.scala
- src/main/scala/com/jsl/nlp/TokenAssembler.scala
- src/main/scala/com/jsl/nlp/annotators/EntityExtractor.scala
- src/main/scala/com/jsl/nlp/annotators/Lemmatizer.scala
- src/main/scala/com/jsl/nlp/annotators/Normalizer.scala
- src/main/scala/com/jsl/nlp/annotators/RegexTokenizer.scala
- src/main/scala/com/jsl/nlp/annotators/Stemmer.scala
- src/main/scala/com/jsl/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
Token assembler annotator transformer bundles tokens into a new document. This annotator comes with modifications into what tokens know about the sentences they belong to, in order to enable the token assembler to reconstruct without destroying sentences
Token assembler is a simple annotator which reconstructs tokens back into text forms. The most important side effect is that tokens now know their belonging sentence.
It allows annotators that use documents, to act on top of cleaned raw data. It also adds sentence information to the token type annotations. It is now an open question whether annotators that require document should now use reconstructed document or not... this, if used, may change final accuracy. It should also motivate developers to use sentence index now.
Simple unit test …
> Token assembler

- build.sbt
> - Modified spark-package organization name

- README.md
Improved README
Improved README regarding the usage of the library
Missing documentation
> - Added documentation in the README regarding the usage of the library

- src/main/resources/application.conf
- src/main/scala/com/jsl/nlp/annotators/EntityExtractor.scala
- src/main/scala/com/jsl/nlp/annotators/Lemmatizer.scala
- src/main/scala/com/jsl/nlp/annotators/RegexMatcher.scala
- src/main/scala/com/jsl/nlp/annotators/ner/crf/CrfBasedNerModel.scala
- src/main/scala/com/jsl/nlp/annotators/ner/regex/NERRegexApproach.scala
- src/main/scala/com/jsl/nlp/annotators/pos/perceptron/PerceptronApproach.scala
- src/main/scala/com/jsl/nlp/annotators/sda/pragmatic/PragmaticScorer.scala
- src/main/scala/com/jsl/nlp/annotators/sda/pragmatic/SentimentDetectorModel.scala
- src/main/scala/com/jsl/nlp/annotators/sda/vivekn/ViveknSentimentModel.scala
- src/main/scala/com/jsl/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
- src/main/scala/com/jsl/nlp/util/ConfigHelper.scala
Let application.conf be read from file to allow the user to change settings and override settings in runtime
New ConfigHelper reads a setting for a path setting for applications.conf
Users will want to change annotator hyper parameters to try different accuracy measures
Manual testing of overriding values for now
> Runtime config

- CHANGELOG
- README.md
- build.sbt
- src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
- src/main/scala/com/johnsnowlabs/nlp/Finisher.scala
- src/test/scala/com/johnsnowlabs/nlp/DocumentAssemblerTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/FinisherTestSpec.scala
Finisher was not removing annotation columns
Issue was related to nullable in StructType not matching the columns properly in schema
New unit tests added
> Fixed Finisher bug not

- docs/quickstart.html
> Corrected defects in documentation

- python/example/vivekn-sentiment/sentiment.ipynb
- src/main/scala/com/johnsnowlabs/nlp/annotators/common/Tokenized.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentTestSpec.scala
Cleaned up tokens cause sentiment analysis not to work at all when sentences become empty of tokens.
It is a blocking issue that may happen very frequently depending on the "goodness" of the raw data.
Unit tests pass, new tests.
> Inconsistent token sentence state

- .gitignore
- README.md
- build.sbt
- docs/index.html
- docs/quickstart.html
- project/plugins.sbt
- Added configuration for sbt-sonatype
- Updated README
- Removed spark-nlp.jar and updated html docs
Adds proper configurations in order to publish the project to maven central using the sbt-sonatype plugin
Migration of release repo
sbt test
> Project configuration to release artifacts to the central repository

- python/run-tests.py
- python/sparknlp/annotator.py
-Removed deprecated unit test of Regex NER
-Removed deprecated setRequiredAnnotatorTypes function
From reported issue
https://github.com/JohnSnowLabs/spark-nlp/issues/58
Unit tests
- [] My change requires a change to the documentation.
> Remove deprecated functions

- src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingBehaviors.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingTestSpec.scala
Adds unit test to verify spell checker works when using TXTDS corpus format. To verify issue
> -Add TXTDS spell checker unittest

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/common/TaggedSentence.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
- src/main/scala/com/johnsnowlabs/util/Benchmark.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproachBehaviors.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproachTestSpec.scala
Part of speech training is quite limited and strict on the input provided to it. This PR allows reading input as Dataset, also makes it flexible to choose the amount of file limit to be trained, and improves the handling of source files.
POS training is slow by its iterative nature, shuffling the files before training and allowing to choose how many files in a folder to read provides more control.
> POS Training improvements

- src/main/scala/com/johnsnowlabs/nlp/HasWordEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfModel.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/ApproachWithWordEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/EmbeddingsReadable.scala
- src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
We needed word embeddings trait not to include all of AnnotatorModel components. This way, HasWordEmbeddings is just another annotator trait which may or may not be included in custom components.
> Flexible word embeddings

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/Lemmatizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcher.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/util/io/ReadAs.scala
- Overloaded setter to use readAs enumeration, moved validation to implicits
- Extended python readAs
> improved readAs API setters

- python/example/crf-ner/ner.ipynb
- python/example/dictionary-sentiment/sentiment.ipynb
- python/example/entities-extractor/extractor.ipynb
- python/example/logreg-assertion/assertion.ipynb
- python/example/vivekn-sentiment/sentiment.ipynb
- python/sparknlp/annotator.py
- python/test/annotators.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala
With the new introduced ExternalResources feature, API might be a little bit tricky to use. This facilitiates API towards the library user, to make it easier to provide file path and necessary delimiters and options for annotators.
This avoids having to pass delimiters and other options through dictionary, and instead made it a parameter in the annotator functions.
> Improved pyspark ExternalResource API easier to use

- src/main/scala/com/johnsnowlabs/nlp/annotators/EntityExtractor.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/Lemmatizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcher.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/pragmatic/SentimentDetector.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
Added options setting in external resource api
> Allow setting options directly from the improved api

- build.sbt
-updated build spark to 2.3.0
-updated scala version to 2.11.12
Should not affect users using older 2.x.x Spark versions.
Will affect compiling the library and unit testing.
> Update scala and spark

- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/datasets/CoNLL.scala
- src/test/scala/com/johnsnowlabs/nlp/DataBuilder.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/assertion/logreg/AssertionLogregApproachSpec.scala
Use System.lineSeparator for OS support will fix certain areas of the library in order to work properly under WIndows environment. Particularly in NER CRF which was hardcoding '\n' chars.
> Support Windows EOL's

- build.sbt
- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
> Rocks db cherry rollback

- src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
- Fixes positional issue when creating annotation
- Removes deprecated model from model downloader python example
> Small bug fixes

- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
Spell checker hamming distance calculation seems wrong. Might result in wrong spell checking.
> - Fixed hamming distance

- .ci/Dockerfile
- .ci/DockerfilePy2
- .ci/DockerfilePy3
- .travis.yml
Fixing travis configuration for testing process against 
Modifications of the .travis.yml
Additions of Dockerfiles under .ci directory
Test process failures in travis-ci environment
> Modified travis configuration to run tests inside docker containers

- build.sbt
Removed incorrect dependency aws-java-sdk-bom.
Fixe for Maven users
- [ x I have added tests to cover my changes.
> Remove aws-java-sdk-bom

- src/main/scala/com/johnsnowlabs/ml/tensorflow/Logging.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
- src/main/scala/com/johnsnowlabs/nlp/ParamsAndFeaturesReadable.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/LemmatizerModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/assertion/dl/AssertionDLModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/EmbeddingsReadable.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
- src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
- src/main/scala/com/johnsnowlabs/util/ZipArchiveUtil.scala
- src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
- src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala
1. Fixes in models reading with several treats like case  EmbeddingsReadable[NerDLModel] with ReadsNERGraph 
2. std dir for models downloader
> Models read fix

- src/main/scala/com/johnsnowlabs/nlp/annotators/common/Tagged.scala
- src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
- src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
- src/test/scala/com/johnsnowlabs/benchmarks/spark/NerHelper.scala
Exact measure in Scala code
Added Exact measure in Scala training code.
> More info about training

- python/example/model-downloader/ModelDownloaderExample.ipynb
- python/sparknlp/internal.py
- python/sparknlp/pretrained/__init__.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/LemmatizerModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/pipelines/PretrainedPipeline.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/pipelines/en/Models.scala
- src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderSpec.scala
1. Resource Downloader fix in python notebook
2. Made refactoring in API: folder goes after language.
> Resource downloader python fix

- docs/components.html
- docs/quickstart.html
- src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/Normalizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/base.scala
- Extended easier imports
- Normalizer and Spell Checker case sensitive by default
- Updated website documentation
> Extended easier imports and better defaults

- docs/components.html
- src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcher.scala
Date Matcher is slightly faster by creating Rule Factories only once
> DateMatcher create regex factories only once

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/AnnotatorApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/AnnotatorModel.scala
- src/main/scala/com/johnsnowlabs/nlp/HasInputAnnotationCols.scala
- src/main/scala/com/johnsnowlabs/nlp/annotator.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
- src/test/scala/com/johnsnowlabs/nlp/AnnotatorBaseTestSpec.scala
- Added missing assertion logreg commit caused missing target
- Fixed required annotator types to properly validate input columns
We missed a commit containing fixes for assertion status models asking for an invalid param name. This PR also fixes wrong validation of input columns
> Included missing logreg commit and fixed input validation

- CHANGELOG
- README.md
- build.sbt
- docs/index.html
- docs/notebooks.html
- docs/quickstart.html
> Release 1.5.2 build up changes

- src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.scala
Missing parameter made Sentence Detector fail when such value is not set
> Added missing sentence detector default param

- src/main/scala/com/johnsnowlabs/util/Version.scala
- src/test/scala/com/johnsnowlabs/util/VersionSpec.scala
If a new spark-nlp library version comes out, and last available downloadable models are from previous versions, download anyway. This will save us from having to re-train specific version models that are now outdated.
> Version matching is now retrocompatible

- CHANGELOG
- README.md
- docs/index.html
- docs/notebooks.html
- docs/quickstart.html
- python/example/model-downloader/assertion.ipynb
> Release candidate 153 hotfix

- CHANGELOG
- docs/notebooks.html
- example/src/TrainViveknSentiment.scala
- src/main/scala/com/johnsnowlabs/nlp/AnnotatorApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentApproach.scala
- src/main/scala/com/johnsnowlabs/util/spark/MapAccumulator.scala
-Fixed vivekn training from dataset
-Added new scala example
Vivekn sentiment analysis was failing due to unregistered accumulators when trained with sentimentCol defined. This now works properly.
> Fixed Vivekn sentiment analysis when training from dataset

- build.sbt
- src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherModel.scala
- src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherBehaviors.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherTestSpec.scala
RegexMatcher now properly includes the identifier of the match within metadata
> RegexMatcher includes identifier

- .gitignore
- example/src/NerDLPipeline.scala
- example/src/TokenizerWithNGram.scala
- python/sparknlp/base.py
- src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
- src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
- src/main/scala/com/johnsnowlabs/nlp/Finisher.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
- src/test/scala/com/johnsnowlabs/nlp/FinisherTestSpec.scala
When using OutputAsArray, there was no way to include metadata. Now includeMetadata Param allows output metadata in any format
> Finisher includeMetadata and Document from Array

- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
> added contains() to WordEmbeddings

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/collections/SearchTrie.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcher.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcherModel.scala
Allows TextMatcher to grab substrings ignoring case. Based on Param.
> Added TextMatcher support for case sensitiviness

- src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/RuleSymbols.scala
Sentence detection uses internal characters to identify sentence bounds. Current characters were common enough for them to appear (rarely), such as some German characters or in very ugly text scenarios.
This caused negative sentence bounds (e.g. -1) and some characters in text to disappear from sentence.
> Use lesser common internal characters for sentence detection

- src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
If a Pipeline contains another pipeline as a stage, LightPipeline was returning empty results. This use case might be useful for existing already created pipelines or downloading pretrained ones such as BasicPipeline
> Allow Light Pipelines to handle embedded pipelines

- src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
- src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticContentFormatter.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticMethod.scala
- src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
- src/main/scala/com/johnsnowlabs/nlp/util/regex/RuleFactory.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticApproachTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticDetectionBehaviors.scala
DocumentAssembler now deals with \n and may trim and clean its content. Makes it more versatile to receive entire document content in a row.
This will allow some processes to run sentence detection from scratch, without assuming any previous sentence detection (i.e. rows read by reading a text file)
This branch also:
1. Fixes broken Array type Metadata format used by Finisher
2. Fixes enumeration style of sentence detection
3. Fixes numbers and decimals use cases in sentence detection
4. Removes tail recursiveness by using foldRight instead
*experimental*
> Text Body parsing improvements

- build.sbt
- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
- src/main/scala/com/johnsnowlabs/nlp/HasWordEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/Normalizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/NormalizerModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLPythonReader.scala
- src/main/scala/com/johnsnowlabs/nlp/datasets/CoNLL2003NerReader.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/ApproachWithWordEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/SparkWordEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
- src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerCrfCoNLL2003.scala
- src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
- src/test/scala/com/johnsnowlabs/ml/logreg/NegexDatasetLogRegTest.scala
- src/test/scala/com/johnsnowlabs/ml/lstm/AssertionDLNegex.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproachTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfCustomCase.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLReader.scala
Enable tensorflow allow_soft_placement for gpu based models support. Updates TF dependency.
> Updated tensorflow structure, and spark default builder

- CHANGELOG
- README.md
- build.sbt
- docs/index.html
- docs/notebooks.html
- docs/quickstart.html
- python/example/model-downloader/ModelDownloaderExample.ipynb
- python/example/model-downloader/assertion.ipynb
- python/example/model-downloader/dl-ner.ipynb
- python/example/text-matcher/extractor.ipynb
- python/example/vivekn-sentiment/sentiment.ipynb
- python/setup.py
- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/util/Build.scala
Contains ready to release changes, fixes, and final integration testing
> Release Candidate 1.6.0

- src/main/scala/com/johnsnowlabs/nlp/functions.scala
- src/test/scala/com/johnsnowlabs/nlp/FunctionsTestSpec.scala
Provides API to filter and map content on datasets, regarding annotation content
> Annotation functions

- python/sparknlp/annotator.py
- src/main/resources/application.conf
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/pragmatic/PragmaticScorer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/pragmatic/SentimentDetector.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/pragmatic/SentimentDetectorModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
- src/test/resources/application.conf
Some Annotators had params set in applicacion.conf. Moved them to Params instead.
> Move config param to appropriate params

- src/main/resources/application.conf
- src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/SparkWordEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/serialization/Feature.scala
- src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
- src/main/scala/com/johnsnowlabs/util/ConfigLoader.scala
- src/test/resources/application.conf
- src/test/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherBehaviors.scala
Renamed configurations for better modularity. Added overridable TMP location for clusters without a distributed fs.defaultFS system.
> Renamed configs, added overrideable cluster tmp location

- src/main/scala/com/johnsnowlabs/nlp/HasFeatures.scala
- src/main/scala/com/johnsnowlabs/nlp/annotator.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentUtils.scala
- src/main/scala/com/johnsnowlabs/nlp/serialization/Feature.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknPerformanceTestSpec.scala
This fixes a long intersection operation during prediction and training. Improves performance significantly.
> Vivekn Sentiment Performance improvements

- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModel.scala
- src/main/scala/com/johnsnowlabs/util/Benchmark.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/spell/SpellCheckersPerfTest.scala
> Spell checker performance review

- CHANGELOG
- README.md
- build.sbt
- docs/index.html
- docs/notebooks.html
- docs/quickstart.html
- python/setup.py
- src/main/scala/com/johnsnowlabs/util/Build.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticDetectionPerfTest.scala
> 162 release candidate

- ocr/src/main/scala/com/johnsnowlabs/nlp/util/io/OcrHelper.scala
Now the regions are detected starting with the image that has not been eroded. Also the tesseract API object is no longer shared between threads.
Improve quality of detection.
Support parallel processing.
> Ocr improvements - improve layout analysis, concurrent access to API.

- Dockerfile
- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotator.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.scala
Fixes sentence detection sentence exploding after annotation
> Fix explode

- .sbtrc
- build.sbt
- python/MANIFEST.in
- python/setup.py
- python/sparknlp/base.py
Added configuration to include sparknlp.jar when installing with pip for python users.
Modifications in setup.py, build.sbt and creation of MANIFEST.in to copy the jar file inside the sparknlp package.
Modifications in base.py to allow python users create and access spark session. 
This will make working with sparknlp easier for python users
The generation and installation of the python distribution sparknlp package was done using [TestPyPI](https://test.pypi.org/).
> Pip install with jar

- CHANGELOG
- README.md
- build.sbt
- docs/index.html
- docs/notebooks.html
- docs/quickstart.html
- src/main/scala/com/johnsnowlabs/util/Build.scala
> 1.6.3 Release Candidate

- .gitattributes
Using `.gitattributes` to exclude `Jupyter` examples from Language Details on GitHub.
NOTE: Although it is through this repo contains `ipynb` files, but it shouldn't suppress the two main languages (Scala and Python) on the repo Language details.
More info: https://github.com/github/linguist#using-gitattributes
- [ x] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.
- [ x] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [ x] I have added tests to cover my changes.
> Create .gitattributes to fix language details on GitHub UI

- src/main/scala/com/johnsnowlabs/nlp/annotators/assertion/dl/TensorflowSerializeModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLPythonReader.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/ClusterWordEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/EmbeddingsHelper.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/ModelWithWordEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/serialization/Feature.scala
Added missing windows path hacks. Rolled back to net.URI for hdfs support
> Added missing windows path hack

- CHANGELOG
- README.md
- build.sbt
- docs/index.html
- docs/quickstart.html
> release candidate 1.7.1

- src/main/scala/com/johnsnowlabs/nlp/embeddings/ClusterWordEmbeddings.scala
> Fix windows path fix compatibility and cluster embeddings wrong FS

- docs/components.html
- example/src/NerCrfExcludedEmbeddings.scala
- python/sparknlp/embeddings.py
- python/sparknlp/internal.py
- src/main/scala/com/johnsnowlabs/nlp/embeddings/ApproachWithWordEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/EmbeddingsHelper.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/ModelWithWordEmbeddings.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproachTestSpec.scala
> EmbeddingsHelper api renaming

- CHANGELOG
- README.md
- build.sbt
- docs/index.html
- docs/quickstart.html
- src/main/scala/com/johnsnowlabs/util/Build.scala
> Release candidate 1.7.2

- python/sparknlp/base.py
- src/main/scala/com/johnsnowlabs/nlp/Doc2Chunk.scala
- src/main/scala/com/johnsnowlabs/nlp/base.scala
- src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
- src/test/scala/com/johnsnowlabs/nlp/Doc2ChunkTestSpec.scala
> chunk2doc and doc2chunk renames and fixes

- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
- src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
Fix serialization issues when using Annotation functions might require serialization of internal classes
> Avoid rocksdb from serialization

- ocr/src/main/scala/com/johnsnowlabs/nlp/util/io/OcrHelper.scala
- python/sparknlp/internal.py
- python/sparknlp/ocr.py
- python/test/annotators.py
Exposes multiple OCR configuration parameters to both Scala and Python APIs.
Allows force-disable processing of text-layers.
> OCR Helper param exposure in python and scala

- docs/articles.html
- docs/components.html
- docs/contribute.html
- docs/index.html
- docs/license.html
- docs/notebooks.html
- docs/quickstart.html
- docs/videos.html
I have replaced all the references to `http` with `https` to avoid `Mixed Content` error in Chrome and other browsers.
Cannot load unsafe content over a secure connection.
```
Mixed Content: The page at 'https://nlp.johnsnowlabs.com/components.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'. This request has been blocked; the content must be served over HTTPS.
```
> Fix "Mixed Content" error in spark-nlp documentation

- python/sparknlp/base.py
- python/sparknlp/internal.py
- src/main/scala/com/johnsnowlabs/util/CoNLLGenerator.scala
> Conll generator from Dataset method

- docs/components.html
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyParserApproach.scala
Adds documentation for dependency parser
Modifies _components.html_ to add documentation for dependency parser and typed dependency parser
> Adds dependency parser documentation

- build.sbt
- python/sparknlp/internal.py
Bypass spark 2.4.0 GC optimization for ExtendedJavaWrapper
> Support Spark 2.4.0

- README.md
- build.sbt
- docs/index.html
- docs/notebooks.html
- docs/quickstart.html
- python/setup.py
- src/main/scala/com/johnsnowlabs/util/Build.scala
Reverts JohnSnowLabs/spark-nlp#332
> Revert "Spark 2.4.0 support"

- build.sbt
Added hadoop-aws 2.7.3 in util dependency to support file download directly from s3a location for the embeddings helper class
Now Embeddings helper can download directly the files from s3a location using s3a url.
Tested using the Global Demo notebook
> added hadoop-aws dependency to support file download from s3 

- src/main/scala/com/johnsnowlabs/util/TrainingHelper.scala
Added TrainingHelper to create metadata file to use ResourceDownloader from trained models
> Metadata creator code

- python/tensorflow/ner/conll2003_folderBased.ipynb
- python/tensorflow/ner/conll2003_ner.ipynb
- python/tensorflow/ner/create_models.ipynb
- python/tensorflow/ner/dataset_encoder.py
- python/tensorflow/ner/ner_model.py
- python/tensorflow/ner/ner_model_saver.py
NERDL Python code for tensorflow to generate graphs and training
> Added NER Deep Learning graph generation for training

- .sbtrc
- build.sbt
Updated the build file to publish OCR jar as well.
> Ocr jar publishing

- CHANGELOG
- README.md
- build.sbt
- docs/index.html
- docs/notebooks.html
- docs/quickstart.html
- python/setup.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticContentFormatter.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/WeightedLevenshtein.scala
- src/main/scala/com/johnsnowlabs/util/Build.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorBehaviors.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticApproachTestSpec.scala
> Release candidate 1.8.1

- README.md
Reorganizing GitHub README page by adding `Table of Contents`.
This change will help users and newcomers to navigate easily through the GitHub page. It is important for users to find what they are looking for from a table of contents.
I have checked all the external and internal links manually to make sure there is no dead link.
> Updating README in GitHub page

- docs/license.html
- python/example/italian/Train-Lemmatizer-Italian.ipynb
- python/example/italian/Train-SentimentDetector-Italian.ipynb
Add Vincenzo Gaudenzi from DXC.technology to credits
> Add Python examples in Italian and update credits page

- src/main/scala/com/johnsnowlabs/nlp/annotator.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetector.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorBehaviors.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorTestSpec.scala
Fix issue of reading models
Adds an implementation of `ParamsAndFeaturesReadable[DeepSentenceDetector]`
Fix [GitHub issue](https://github.com/JohnSnowLabs/spark-nlp/issues/358)
Unit tests on scala and python
> Adds implementation of Readable for DeepSentenceDetector

- python/run-tests.py
- python/sparknlp/annotator.py
- python/test/annotators.py
- src/main/scala/com/johnsnowlabs/nlp/annotator.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ChunkTokenizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/common/SentenceSplit.scala
- src/main/scala/com/johnsnowlabs/nlp/functions.scala
- src/test/resources/entity-extractor/test-chunks.txt
- src/test/scala/com/johnsnowlabs/nlp/ContentProvider.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ChunkTokenizerTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerBehaviors.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Allows to tokenize CHUNK type annotators. Also stores metadata to link CHUNK id.
SECONDARY: Adds a foreach function. Removes default column name in Tokenizer.
> ChunkTokenizer annotator

- python/sparknlp/annotator.py
- python/test/annotators.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticApproachTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticDetectionBehaviors.scala
SentenceDetector maxLength splits sentence longer than specified value
> SentenceDetector maxLength splits long sentences

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverter.scala
> NerConverter whitelist entities

- CHANGELOG
- README.md
- build.sbt
- docs/index.html
- docs/notebooks.html
- docs/quickstart.html
- python/setup.py
- python/test/annotators.py
- src/main/scala/com/johnsnowlabs/util/Build.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorBehaviors.scala
> Release candidate 1.8.2

- README.md
Added instructions for Anaconda/Conda intallation for `spark-nlp`
> Update README for Anaconda instructions

- python/example/crf-ner/ner.ipynb
- python/example/crf-ner/ner_benchmark.ipynb
- python/example/dictionary-sentiment/sentiment.ipynb
- python/example/dl-ner/ner.ipynb
- python/example/dl-ner/ner_benchmark.ipynb
- python/example/italian/Train-Lemmatizer-Italian.ipynb
- python/example/italian/Train-SentimentDetector-Italian.ipynb
- python/example/model-downloader/ModelDownloaderExample.ipynb
- python/example/model-downloader/dl-ner.ipynb
- python/example/text-matcher/extractor.ipynb
- python/example/vivekn-sentiment/sentiment.ipynb
Updating Python examples with Spark NLP 1.8.2 and new config of Spark Packages.
> Update Python examples

- docs/videos.html
Updating the Video page for adding new video and styling it correctly.
> Adding a new video in french

- README.md
Redesign the `models` section in README to be accessible by languages. This makes the table more clear by each language has its own table.
> Re-design the models section

- ocr/src/main/scala/com/johnsnowlabs/nlp/util/io/ImageProcessing.scala
Replaced the min square computation by a more efficient one. 
This will save both memory and processing time. This solves some memory problems experienced on OCR tests.
> performance optimization for skew detection

- python/run-tests.py
- python/sparknlp/__init__.py
- python/test/annotators.py
> Added pyspark doc2chunk and chunk2doc as to sparknlp module

- build.sbt
> upgrade in aws sdk

- build.sbt
> resolved non provided key dependency for ocr

- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/datasets/CoNLL.scala
- src/test/scala/com/johnsnowlabs/benchmarks/spark/NerCrfCoNLL2003.scala
- src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
- src/test/scala/com/johnsnowlabs/nlp/DataBuilder.scala
> Fixed unit tests failing on windows for ner

- build.sbt
- src/main/scala/com/johnsnowlabs/nlp/embeddings/EmbeddingsHelper.scala
Embeddings are now downloaded only once from s3 and cached in the cached_pretrained folder
> Embeddings cache

- CHANGELOG
- README.md
- build.sbt
- docs/index.html
- docs/notebooks.html
- docs/quickstart.html
- python/README.md
- python/example/crf-ner/ner.ipynb
- python/example/crf-ner/ner_benchmark.ipynb
- python/example/dictionary-sentiment/sentiment.ipynb
- python/example/dl-ner/ner.ipynb
- python/example/dl-ner/ner_benchmark.ipynb
- python/example/italian/Train-Lemmatizer-Italian.ipynb
- python/example/italian/Train-SentimentDetector-Italian.ipynb
- python/example/model-downloader/ModelDownloaderExample.ipynb
- python/example/model-downloader/dl-ner.ipynb
- python/example/text-matcher/extractor.ipynb
- python/example/vivekn-sentiment/sentiment.ipynb
- python/setup.py
- src/main/scala/com/johnsnowlabs/util/Build.scala
> Release candidate branch for Spark NLP 1.8.3

- src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/Chunker.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/common/SentenceSplit.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverter.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ChunkerBehaviors.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerSpec.scala
1. DocumentAssembler now marks sentence id = 0
2. SentenceDetector zips sentence id
3. Chunker annotator respects sentences
4. Chunker includes chunk id
> assemble with sentence id, improved chunker

- src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/Chunker.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcher.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcherModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/common/SentenceSplit.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverter.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala
- src/test/resources/entity-extractor/test-phrases.txt
- src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ChunkTokenizerTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ChunkerBehaviors.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/TextMatcherTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerSpec.scala
1. Breaks on sentences appropriately
2. Case sensitive applies on input, not on output
3. Added appropriate unit test cases
> Text matcher sentenced

- src/main/scala/com/johnsnowlabs/nlp/Doc2Chunk.scala
- src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/Chunker.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcher.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcherModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/common/SentenceSplit.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverter.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala
- src/test/resources/entity-extractor/test-phrases.txt
- src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ChunkTokenizerTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ChunkerBehaviors.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/TextMatcherTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerSpec.scala
Ensures CHUNK type annotators include "sentence" id metadata
> Chunks promise sentence

- src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/SentenceDetectorParams.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetector.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticApproachTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticDetectionBehaviors.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetectorBoundsSpec.scala
> MaxLength now truncates in whitespaces, defaults to disabled

- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentApproach.scala
- src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
- src/test/scala/com/johnsnowlabs/nlp/LightPipelineTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentTestSpec.scala
Make sure `ViveknSentimentApproach` can be trained from a DataFrame in `.fit()` stage without any use of ExternalResources.
Removing the use of ExternalResource in the `.fit()` stage. 
Scalatest inside `ViveknSentimentTestSpec`.
> Adopt ViveknSentimentApproach to train only by DataFrame

- src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproach.scala
- src/test/scala/com/johnsnowlabs/nlp/LightPipelineTestSpec.scala
Fix LightPipelineTestSpec failing due to values for sentiment being `0` and `1` instead of `negative` and `positive`.
> Fix LightPipelineTestSpec

- python/example/crf-ner/ner.ipynb
- python/example/dl-ner/ner.ipynb
- python/example/dl-ner/ner_bert.ipynb
- python/example/quick-start.ipynb
- src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
- src/main/scala/com/johnsnowlabs/nlp/RawAnnotator.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/common/SentenceWithEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
> Fixed serialization of embeddings

- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
> Added missing wordembeddings class

- python/sparknlp/annotator.py
- python/sparknlp/base.py
- python/sparknlp/common.py
- python/sparknlp/training.py
- python/tensorflow/ner/dataset_encoder.py
- python/test/annotators.py
- src/main/scala/com/johnsnowlabs/nlp/AnnotatorModel.scala
- src/main/scala/com/johnsnowlabs/nlp/RawAnnotator.scala
> Unit test bug fixes

- build.sbt
Now to build spark-nlp for gpu just pass -Dis_gpu=true with sbt command for example:
sbt -Dis_gpu=true assembly
This change is to handle gpu build for spark-nlp.
> Added enviornment variable is_gpu to handle build for gpu.

- python/example/dl-ner/ner.ipynb
- python/example/dl-ner/ner_bert.ipynb
- src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
> Light pipelines not carrying over nested pipeline results

- build.sbt
> Updated build to alternate accross gpu tensorflow

- src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcher.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTestSpec.scala
> DateMatcher improvements

- python/example/match-datetime/Pretrained-MatchDateTime-Pipeline.ipynb
> Add example to use pretrained match_datetime pipeline

- python/example/match-pattern/Pretrained-MatchPattern-Pipeline.ipynb
> Add example to use pretrained match_pattern pipeline

- python/sparknlp/training.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/SentenceDetectorParams.scala
- src/main/scala/com/johnsnowlabs/nlp/training/CoNLL.scala
> CoNLL Reader can explode sentences

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/Normalizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/NormalizerModel.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/NormalizerBehaviors.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/NormalizerTestSpec.scala
> Normalizer improvements and slangs

- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
> Context spell multiple sentence

- src/main/scala/com/johnsnowlabs/nlp/annotators/NormalizerModel.scala
- src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
- src/test/resources/spell/slangs.txt
- src/test/scala/com/johnsnowlabs/nlp/annotators/NormalizerTestSpec.scala
> Fixed Normalizer slang case

- python/sparknlp/base.py
- src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
- src/main/scala/com/johnsnowlabs/nlp/base.scala
> Light Pipelines can now also transform

- python/sparknlp/__init__.py
- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteApproach.scala
> Symmetric detele Approach performance review

- python/example/match-datetime/Pretrained-MatchDateTime-Pipeline.ipynb
- python/example/match-pattern/Pretrained-MatchPattern-Pipeline.ipynb
> Remove dataframe transform in favor of annotator by LightPipeline

- python/example/quick-start.ipynb
- src/main/resources/application.conf
- src/main/scala/com/johnsnowlabs/nlp/serialization/Feature.scala
> Disable use broadcast by default

- python/example/perceptron-french/Train-Perceptron-French.ipynb
> Add example of how to train POS tagger in French

- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSpell.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
> Fixed serialization of TensorSpell

- python/sparknlp/common.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLPythonReader.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
- src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
> Dont serialize tensorflow transients

- python/example/spellchecking/ContextSpellChecking.ipynb
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSpell.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
-  Synchronized access to the Tensorflow layer.
-  LightPipelines in notebook.
-  Default value in model.
> Context spell bug

- ocr/src/main/scala/com/johnsnowlabs/nlp/util/io/OcrHelper.scala
> added code to handle IO Exceptions from OCR PDFBox

- build.sbt
- docs/assets/plugins/jquery-match-height/test.html
- docs/index.html
- docs/notebooks.html
- docs/quickstart.html
- ocr/src/main/scala/com/johnsnowlabs/nlp/util/io/OcrHelper.scala
- ocr/src/test/scala/com/johnsnowlabs/nlp/util/io/OcrExample.scala
- python/example/crf-ner/ner.ipynb
- python/example/crf-ner/ner_benchmark.ipynb
- python/example/dictionary-sentiment/sentiment.ipynb
- python/example/dictionary-sentiment/sentiment_rb.ipynb
- python/example/dl-ner/ner_benchmark.ipynb
- python/example/italian/Train-Lemmatizer-Italian.ipynb
- python/example/italian/Train-SentimentDetector-Italian.ipynb
- python/example/model-downloader/ModelDownloaderExample.ipynb
- python/example/model-downloader/dl-ner.ipynb
- python/example/text-matcher/extractor.ipynb
- python/example/vivekn-sentiment/sentiment.ipynb
- python/setup.py
- python/sparknlp/__init__.py
- python/test/annotators.py
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
- src/main/scala/com/johnsnowlabs/util/Build.scala
1. OcrHelper now is a class, not a global object. Previous global object design was preventing the object from being serialized, thus parameters in executors nodes were set to default values. If you were using default parameters, this didn't bother you.
2. setSplitPages() now does what it should do; control whether pages are split or not. Previously, it would merge all regions across all pages together. Again, if you had one region per page, you didn't notice this.
3. setSplitRegions() now this new param will allow to decide whether different regions should be merged or not.
4. Tested with Tesseract 4.0.0
5. Solved problems in classpath with different jar versions for apache.commons.lang3.
> Different Ocr fixes

- docs/assets/js/main.js
- docs/components.html
> Update website 200

- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteApproach.scala
- src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingBehaviors.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteBehaviors.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModelTestSpec.scala
Refactor unit test and handle an exception
Make changes on unit tests to match actual changes
Make unit tests lighter by removing unnecessary tests
Adds intuitive error message when setting a wrong dataset for training
> Validate dataset spellcheckers

- python/sparknlp/__init__.py
- src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
> add ocr handlers for quick start

- CHANGELOG
- README.md
- build.sbt
- docs/assets/plugins/jquery-match-height/test.html
- docs/index.html
- docs/notebooks.html
- docs/quickstart.html
- python/example/crf-ner/ner.ipynb
- python/example/crf-ner/ner_benchmark.ipynb
- python/example/dictionary-sentiment/sentiment.ipynb
- python/example/dl-ner/ner.ipynb
- python/example/dl-ner/ner_benchmark.ipynb
- python/example/dl-ner/ner_bert.ipynb
- python/example/italian/Train-Lemmatizer-Italian.ipynb
- python/example/italian/Train-SentimentDetector-Italian.ipynb
- python/example/match-datetime/Pretrained-MatchDateTime-Pipeline.ipynb
- python/example/match-pattern/Pretrained-MatchPattern-Pipeline.ipynb
- python/example/model-downloader/ModelDownloaderExample.ipynb
- python/example/model-downloader/dl-ner.ipynb
- python/example/perceptron-french/Train-Perceptron-French.ipynb
- python/example/spell-check-ml/Pretrained-SpellCheckML-Pipeline.ipynb
- python/example/text-matcher/extractor.ipynb
- python/example/vivekn-sentiment/sentiment.ipynb
- python/setup.py
- python/sparknlp/__init__.py
- src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
- src/main/scala/com/johnsnowlabs/util/Build.scala
> Release Candidate 2.0.1

- python/sparknlp/base.py
- python/sparknlp/common.py
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
- src/main/scala/com/johnsnowlabs/nlp/AnnotatorApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/AnnotatorType.scala
- src/main/scala/com/johnsnowlabs/nlp/Chunk2Doc.scala
- src/main/scala/com/johnsnowlabs/nlp/Doc2Chunk.scala
- src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
- src/main/scala/com/johnsnowlabs/nlp/HasInputAnnotationCols.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ChunkTokenizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/Chunker.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcherModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/common/SentenceWithEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/common/TokenizedWithSentence.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverter.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/FeatureGenerator.scala
- src/main/scala/com/johnsnowlabs/nlp/base.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
Adds helpful params to Doc2Chunk
> Chunkdoc improvements upstream

- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserApproach.scala
- src/test/scala/com/johnsnowlabs/nlp/Doc2ChunkTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/TextMatcherTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserApproachTestSpec.scala
- src/test/scala/com/johnsnowlabs/util/ResourceHelperTestSpec.scala
> Fix unit tests for windows compatibility

- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
Allows use of pre-trained Symmetric Spell  on Python
Add Symmetric Spell on ResourceDownloader
> Add Symmetric Spell for use as pre-trained on python

- python/sparknlp/annotator.py
Fix the functionality to set your own normalization pattern in V2.x
Fix the functionality to set your own normalization pattern in V2.x. There appears to have been a small oversight in the referenced variables which I have corrected.
Fixes `AttributeError: 'Normalizer' object has no attribute 'patterns'`
when using `setCleanupPatterns`:
> normalizer = Normalizer() \
.setInputCols(["tokens"]) \
.setOutputCol("normalized") \
.setCleanupPatterns(["[^A-Za-z0-9\\-]"])
On a Databricks cluster using the code above
> fix specifying custom normalization cleanup pattern

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/common/Tagged.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/common/TaggedWord.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfModel.scala
> confidence in crf

- ocr/src/main/scala/com/johnsnowlabs/nlp/util/io/OcrHelper.scala
- ocr/src/main/scala/com/johnsnowlabs/nlp/util/io/TesseractAccess.scala
- ocr/src/test/scala/com/johnsnowlabs/nlp/util/io/OcrExample.scala
> Fix tess4j init

- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSerializeModel.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSpell.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/LoadsContrib.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
> Dont serialize logger

- CHANGELOG
- README.md
- build.sbt
- docs/quickstart.html
- python/setup.py
- python/sparknlp/__init__.py
- src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
- src/main/scala/com/johnsnowlabs/util/Build.scala
> Release Candidate 2.0.3

- README.md
**English**
**Italian**
**French**
> Update README: New Pipelines and Models in 2.0.3

- docs/components.html
change "entitiy" to "entity"
It is easier to read documentation when words are spelled correctly.
https://www.google.com/search?q=how+do+you+correctly+spell+entitiy
> fix typos in components.html

- docs/components.html
fix some misspellings
Fix misspellings and grammar errors.
improve the documentation
n/a
n/a
> [skip travis] Update components.html

- python/sparknlp/annotator.py
- python/sparknlp/embeddings.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModel.scala
> Updated pretrained model names

- src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
> corrected wrong reader

- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
> fix embeddings name mapping

- CHANGELOG
- README.md
- build.sbt
- docs/en/install.md
- docs/en/quickstart.md
- docs/index.html
- python/setup.py
- python/sparknlp/__init__.py
- src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
- src/main/scala/com/johnsnowlabs/util/Build.scala
> Release candidate 2.0.4

- Dockerfile
- src/test/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyModelTestSpec.scala
> Ignore tests that fail on travis because of heap memory shortage

- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
> Download tf.contrib NerDLModel if not windows

- python/sparknlp/__init__.py
> Included ocr dependency coordinates in sparknlp quickstart

- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceMetadata.scala
> Ignore blank lines in metadata

- build.sbt
- python/sparknlp/__init__.py
> Spark version bump

- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentModel.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentTestSpec.scala
> Sentiment analysis confidence scores

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSerializeModel.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSpell.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/LoadsContrib.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLPythonReader.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/HasWordEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
- src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
> Optionally set to use contrib or not, rather than OS choice

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/LemmatizerModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyParserModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModel.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/PretrainedPipeline.scala
> Shorthand lang rather than language in all pretrained

- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
> Always load contrib before training

- CHANGELOG
- README.md
- build.sbt
- docs/Gemfile.lock
- docs/_layouts/landing.html
- docs/en/install.md
- docs/en/quickstart.md
- python/setup.py
- python/sparknlp/__init__.py
- src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
- src/main/scala/com/johnsnowlabs/util/Build.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorTestSpec.scala
> Release candidate 2.0.6

- CHANGELOG
- README.md
- build.sbt
- docs/Gemfile.lock
- docs/_layouts/landing.html
- docs/en/install.md
- docs/en/quickstart.md
- python/setup.py
- python/sparknlp/__init__.py
- src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
- src/main/scala/com/johnsnowlabs/util/Build.scala
> Release version bump

- src/main/scala/com/johnsnowlabs/nlp/annotators/common/TokenizedWithSentence.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/HasWordEmbeddings.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorTestSpec.scala
> Fixed logic of overriding embeddings ref

- README.md
> corrected broken link

- CHANGELOG
- README.md
- build.sbt
- docs/Gemfile.lock
- docs/_layouts/landing.html
- docs/en/install.md
- docs/en/quickstart.md
- python/setup.py
- python/sparknlp/__init__.py
- src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
- src/main/scala/com/johnsnowlabs/util/Build.scala
> Release Candidate 2.0.8

- README.md
> Added Google Colab notebook setup in README

- docs/en/annotators.md
Just adding the classnames to every annotator in the docs
Getting familiar with the lifecycle
It has not, I imagine manual test is performed. Otherwise assertions on the link's view containing the class definition.
> Classnames were added to each annotator in the list

- README.md
- docs/en/quickstart.md
Just fixing a typo on ConfigLoader's namespace in the docs
It aids in the correctness of the documentation, and new users that may not quickly identify the typo
> (...).uti.ConfigLoader to (...).util.ConfigLoader in docs

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
> Fix unix pick pretrained NerDL model correctly

- python/sparknlp/common.py
- src/main/scala/com/johnsnowlabs/nlp/embeddings/ClusterWordEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/HasWordEmbeddings.scala
Embeddings ref is an address to the embeddings word2vec database. This PR validates the address is not overwritten if embeddings were already loaded into some ref.
> Embeddings ref override check

- .sbtrc
- build.sbt
- eval/src/main/scala/com/johnsnowlabs/nlp/eval/DependencyParserEvaluation.scala
- eval/src/main/scala/com/johnsnowlabs/nlp/eval/EvaluationMetrics.scala
- eval/src/main/scala/com/johnsnowlabs/nlp/eval/NerCrfEvaluation.scala
- eval/src/main/scala/com/johnsnowlabs/nlp/eval/NerDLEvaluation.scala
- eval/src/main/scala/com/johnsnowlabs/nlp/eval/NorvigSpellEvaluation.scala
- eval/src/main/scala/com/johnsnowlabs/nlp/eval/SymSpellEvaluation.scala
- eval/src/main/scala/com/johnsnowlabs/nlp/eval/TypedDependencyParserEvaluation.scala
First eval module with model and pipeline evalution scripts
> Evaluation module with few help scripts

- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
Added AnonymousAWSCredentials if none of the credentials chains found
> added AnonymousAWSCredentials to support download from public 

- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverter.scala
> Whitelist setter in NerConverter

- python/sparknlp/embeddings.py
- python/sparknlp/pretrained.py
- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
Provide a download progress bar during pre-trained Model and Pipeline download.
> Download resource progress bar

- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceMetadata.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
- src/main/scala/com/johnsnowlabs/util/FileHelper.scala
- src/main/scala/com/johnsnowlabs/util/TrainingHelper.scala
1) Added check to do not download zip file if either the zip is present or the folder is present
2) Delete the zip file after download and unzip
3) Added checksum in metadata which will be added while upload and if checksum is present the downloaded zip file will be checked to ensure the zip file is correct.
Tested manually
> updated zip download from s3

- src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Tokenizer exceptions list now allows parsing regular expressions
> Tokenizer exceptions now support regex

- CHANGELOG
- python/sparknlp/__init__.py
- python/sparknlp/annotator.py
- python/sparknlp/base.py
- src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ocr/PositionFinder.scala
Allows position finder to retrieve the coordinates of a chunk within a windowed string, instead of only when exact matching position is found, increases matching ratio as we increase window size, but reduces performance
> Position finder window

- python/sparknlp/annotator.py
- src/main/resources/application.conf
- src/main/scala/com/johnsnowlabs/ml/tensorflow/Logging.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala
- src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
NerDL can output metrics to file
> Output helper log files

- docs/en/annotators.md
- docs/en/install.md
- docs/en/quickstart.md
> Doc review

- docs/en/quickstart.md
> TOC added and some minor format issues fixed

- docs/en/install.md
> Minor fixes in doc

- docs/en/annotators.md
- docs/en/quickstart.md
> Add a new section to Getting Started in the documentation for getting data out

- CHANGELOG
- python/sparknlp/base.py
- python/sparknlp/internal.py
- python/sparknlp/pretrained.py
- src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
- src/main/scala/com/johnsnowlabs/nlp/Finisher.scala
- src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/PretrainedPipeline.scala
- src/test/java/com/johnsnowlabs/nlp/GeneralAnnotationsTest.java
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticApproachTestSpec.scala
> Finisher optional parse embeddings

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/EmbeddingsFinisher.scala
- src/main/scala/com/johnsnowlabs/nlp/base.scala
This PR will fix the missing `EmbeddingsFinisher` in Scala and Python.
> Fix missing EmbeddingsFinisher in Scala and Python

- docs/en/models.md
- docs/en/quickstart.md
Changed Pythond to Python in the Quickstart documentation
Changed NerCRFModel to NerCrfModel in the Models documenation
#682 
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
> Fixed two typos. closes #682

- python/sparknlp/__init__.py
- python/sparknlp/annotator.py
Removed deprecated import links in pyspark
> fixed bad deprecated ocr and spell paths

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerOverwriter.scala
> Ner overwriter

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotator.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcher.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcherModel.scala
Just adding a feature to TextMatcher in which it merges overlapping matches
To train the trie using ngrams and combinations and just get the longest chunk for a particular set of words that have overlapping results
> Text matcher overlapping

- python/sparknlp/internal.py
- python/sparknlp/pretrained.py
For flexibility reasons, the inner jvm downloader may now be overriden
> Python argument downloader validator

- python/sparknlp/base.py
Fixed some situation where import Annotation fails
> Preferred import of Annotation at an upper level

- src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddings.scala
* Fixed bad sentence id synchronization between zipWithIndex and appropriate sentence index
* Added missing SentenceEmbeddings metadata
> Embeddings Fixed metadata and sentence index synchronization

- src/main/scala/com/johnsnowlabs/nlp/HasPretrained.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/LemmatizerModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcherModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyParserModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModel.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
Default model names made an Option, so we can set it to None when there are no default models to be loaded
> Pretrained API defaultModelName now an Option

- python/sparknlp/__init__.py
- src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
Version functions return the version (for any further tests on the client)
> Version returns string

- build.sbt
- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
> Chunk embeddings ref fix

- docs/en/quickstart.md
Small edits to quickstart.md that do not change meaning.
Cleans up the language on the documentation.
- [x ] I have updated the documentation accordingly.
> minor edits to quickstart

- src/main/scala/com/johnsnowlabs/nlp/util/regex/RuleFactory.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticApproachTestSpec.scala
Fixed a bug in pragmatic sentence detector where a sub matched group contained dollar sign reference to a fake matching group of a regex.
> Fixed a fake group match scenario

- README.md
> minor readme spelling fixes

- CHANGELOG
- README.md
- build.sbt
- docs/en/quickstart.md
- python/setup.py
- python/sparknlp/__init__.py
- python/sparknlp/functions.py
- src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcher.scala
- src/main/scala/com/johnsnowlabs/nlp/util/regex/RuleFactory.scala
- src/main/scala/com/johnsnowlabs/util/Build.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticApproachTestSpec.scala
We would like to thank you all for your valuable feedback via our Slack channels and our GitHub repositories. Spark NLP `2.3.4` is a very stable and rock-solid release. However, we wanted to fix the few remaining minor bugs before moving to our bigger release `2.4.0`! 
---------------
Bugfixes
---------------
- https://github.com/JohnSnowLabs/spark-nlp/pull/702 Date matcher fixes flexible dates
- https://github.com/JohnSnowLabs/spark-nlp/pull/718 Fixed a bug in a pragmatic sentence detector where a sub matched group contained a dollar sign.
- https://github.com/JohnSnowLabs/spark-nlp/pull/719 Move import to top-level to avoid import fail in Spark NLP functions
- https://github.com/JohnSnowLabs/spark-nlp/pull/709 https://github.com/JohnSnowLabs/spark-nlp/pull/716 Some improvements in our …
> 235 release candidate

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcher.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcherUtils.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcher.scala
- src/main/scala/com/johnsnowlabs/nlp/util/regex/RuleFactory.scala
- src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcherBehaviors.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcherTestSpec.scala
New Annotator based on DateMatcher but supporting multiple Dates per sentence. Currently has time detection disabled.
> Multi date matcher

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcher.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcherModel.scala
Generates SearchTrie on fit rather on transform. Should improve memory usage and serialization efficiency
> Text Matcher Trie on Fit

- src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala
> Chunk embeddings empty sentence bug fix

- src/main/scala/com/johnsnowlabs/storage/RocksDBConnection.scala
Fixes a situation where cluster would put rocksdb files in executor root location
> Local db search fix

- README.md
- build.sbt
- python/setup.py
- python/sparknlp/__init__.py
- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
- src/main/scala/com/johnsnowlabs/util/Build.scala
> Release Candidate 2.3.6

- src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
The empty sentence bug fix for ChunkEmbeddings
> Empty sentence bug fix

- src/main/scala/com/johnsnowlabs/nlp/annotators/btm/TMEdgesReadWriter.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/btm/TMEdgesReader.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/btm/TMNodesReader.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/btm/TMNodesWriter.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/btm/TMVocabReadWriter.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/btm/TMVocabReader.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsReader.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsWriter.scala
- src/main/scala/com/johnsnowlabs/nlp/util/LruMap.scala
- src/main/scala/com/johnsnowlabs/storage/StorageBatchWriter.scala
- src/main/scala/com/johnsnowlabs/storage/StorageReadWriter.scala
- src/main/scala/com/johnsnowlabs/storage/StorageReader.scala
- src/main/scala/com/johnsnowlabs/storage/StorageWriter.scala
- Improves LRU performance by caching its current size
- Fixed flawed logic on StorageReadWriter
> Storage read writer review

- src/main/scala/com/johnsnowlabs/nlp/annotators/btm/BigTextMatcher.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
- src/main/scala/com/johnsnowlabs/storage/HasStorage.scala
Storage refactor polishing: Make storage external resource optional, in case content comes only from training dataset
> Storage resource as optional

- src/main/scala/com/johnsnowlabs/nlp/annotators/btm/BigTextMatcherModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
- src/main/scala/com/johnsnowlabs/nlp/util/LruMap.scala
- src/main/scala/com/johnsnowlabs/storage/HasStorage.scala
- src/main/scala/com/johnsnowlabs/storage/HasStorageModel.scala
- src/main/scala/com/johnsnowlabs/storage/HasStorageRef.scala
- src/main/scala/com/johnsnowlabs/storage/RocksDBConnection.scala
- src/main/scala/com/johnsnowlabs/storage/StorageHelper.scala
- src/main/scala/com/johnsnowlabs/storage/StorageLocator.scala
- src/main/scala/com/johnsnowlabs/storage/StorageReadWriter.scala
- src/main/scala/com/johnsnowlabs/storage/StorageReadable.scala
- src/main/scala/com/johnsnowlabs/storage/StorageReader.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/btm/BigTextMatcherTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsTestSpec.scala
Storage optimizations by improving data structure, LRU improvements and API fixes
> Storage performance optimizations

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/btm/TMEdgesReadWriter.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/btm/TMEdgesReader.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/btm/TMNodesReader.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/btm/TMNodesWriter.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/btm/TMVocabReadWriter.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/btm/TMVocabReader.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsLoader.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsReadWriter.scala
- src/main/scala/com/johnsnowlabs/nlp/training/CoNLL2003NerReader.scala
- src/main/scala/com/johnsnowlabs/nlp/util/LfuCache.scala
- src/main/scala/com/johnsnowlabs/nlp/util/LruMap.scala
- src/main/scala/com/johnsnowlabs/storage/StorageReadWriter.scala
- src/main/scala/com/johnsnowlabs/storage/StorageReader.scala
- src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
- src/test/scala/com/johnsnowlabs/nlp/util/LfuCacheTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/util/LruMapTestSpec.scala
Improved LRU by switching order and storing disk reads, increased default cache sizes
> Increased cache sizes, improved LRU, added LFU

- python/sparknlp/annotator.py
- python/sparknlp/internal.py
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoder.scala
> BertEmbeddings should load TF Saved Models

- src/main/scala/com/johnsnowlabs/storage/HasStorage.scala
- src/main/scala/com/johnsnowlabs/storage/StorageHelper.scala
Fixes windows support with storage in path resolution
> Windows valid uri support

- src/main/scala/com/johnsnowlabs/storage/Database.scala
Bugfix for storage stringify in rc-2
> Fixed missing toString

- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLPythonReader.scala
- src/main/scala/com/johnsnowlabs/storage/HasStorage.scala
- src/main/scala/com/johnsnowlabs/storage/HasStorageModel.scala
- src/main/scala/com/johnsnowlabs/storage/StorageHelper.scala
- src/main/scala/com/johnsnowlabs/storage/StorageLocator.scala
- src/main/scala/com/johnsnowlabs/storage/StorageReadable.scala
- src/test/java/com/johnsnowlabs/nlp/GeneralAnnotationsTest.java
Fixes a bug in rc-2 where it fails to load non-included embeddings
> Fixed loading to cluster

- docs/_layouts/landing.html
Fixed typo of "Anacodna" to "Anaconda"
> Fixed typo in landing.html

- docs/en/licensed_annotators.md
- src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
Just documentation for ChunkEntityResolver
> Docs chunk entity resolver

- docs/en/licensed_annotators.md
Including documentation for new licensed annotators in 2.4.0
> New licensed annotators

- docs/en/licensed_annotators.md
- src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala
Fix to get the chunk from the right place
> Chunk embeddings empty chunk fix

- build.sbt
- python/setup.py
- python/sparknlp/__init__.py
- src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
- src/main/scala/com/johnsnowlabs/util/Build.scala
Just the version bump.
I needed this to test new models generated with 2.4.2
> 2.4.2 version bump

- python/tensorflow/ner/create_models.py
Small fix changing return to raise in order to throw the exception
> Fixed return and wrote raise for the tensorflow version exception

- docs/en/ocr.md
corrected some typos and did some rephrasing
- [x ] Code improvements with no or little impact
- [x ] I have updated the documentation accordingly.
> small updates of the OCR documentation

- src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
> splitpattern implementation

- python/sparknlp/__init__.py
- python/test/annotators.py
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowClassifier.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLTestSpec.scala
> Fix ClassifierDL in Python

- src/test/scala/com/johnsnowlabs/nlp/LightPipelineTestSpec.scala
Fixed the test case name for pipelineWithoutNormalize typo
The test case pipelineWithoutNormalize was having incorrect name.
Fixes test case which compares benchmark for Lightweight pipeline and Pipeline
- [ x] Code improvements with no or little impact
- [ x] My code follows the code style of this project.
- [ x] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
> Updated test case for pipelineWithoutNormalize 

- src/main/scala/com/johnsnowlabs/util/CoNLLGenerator.scala
- src/test/scala/com/johnsnowlabs/nlp/util/CoNLLGeneratorTestSpec.scala
Added test class, overloaded CoNLLGenerator to work when passed a completed dataframe, and changed CoNLLGenerator to actually use NER labels from the dataframe instead of ignoring them and just writing "O" for all entities.
It improved the functionality of the CoNLLGenerator to work with NERs, and to accept a dataframe as a parameter without a pipeline.
I made a test class to check the output against previous correct output, and also added new NER-friendly test output which is tested against. My environment is IntelliJ Community with Scala Plugin 2020 Java 8, and Python 3.7. This has no affects on other areas of the code.
- [  ] Breaking change (fix or feature that would cause existing functionality to change)
> Refactor + Test CoNLLGenerator

- src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala
- src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
The Annotator log files where not getting created in DBFS due to IO Operation not supported error. This fix is to handle the error.
To make the fix the change was done on OutputHelper class where if FileSystem Scheme is of type "dbfs" it is treated as a normal disk file for creating directory and for writing and appending logs to the file.
The limitation of this approach is that the setOutputLogsPath in Annotators or sparknlp.settings.annotator.log_folder in application.conf can only point to a file system path and not the dbfs mount paths. File system paths like /home or /tmp of the driver. 
dbfs is a S3 like an object store which do not support appending to a file hence logs can not be created in dbfs paths. 
**Note:** 
1. If neither sparknlp.settings.annotator.log_folder is set nor …
> Annotator log file Fix for DBFS

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSentiment.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLModel.scala
> Introducing new SentimentDL annotator

- docs/en/training.md
- src/main/scala/com/johnsnowlabs/nlp/training/PubTator.scala
- src/main/scala/com/johnsnowlabs/util/CoNLLGenerator.scala
- src/test/resources/corpus_pubtator_sample.txt
- src/test/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddingsTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/util/CoNLLGeneratorTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/util/PubTatorTestSpec.scala
-Added PubTator object for readDataset function, which reads in a PubTator document and produces a DataFrame ready to be written as a CoNLL or used for training an NER. Also added test class, test corpus, and section in training.md documentation
-Fixed CoNLLGenerator (which was previously writing "" "" "" "" instead of blank lines).
Allows users to read new files as DataFrames, including the [MedMentions dataset](https://github.com/chanzuckerberg/MedMentions), which can be used to train an NER.
Created PubTatorTestSpec to test if PubTator.readDataset creates file compatible with CoNLLGenerator. Tests ran on Intellij Community 2 with Python 3.6, Java 1.8.
> Add PubTator Reader (and fix CoNLLGenerator)

- docs/en/developers.md
Updated developers instructions for the whl generation.
> add whl generation instruction to the dev section

- src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
This PR makes sure if the line in the dictionary is corrupted it will skip instead of an exception.
> Lemmatizer should not crash in case of bad input

- python/run-tests.py
- python/test/annotators.py
- src/test/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddingsTestSpec.scala
Added tests for the new XlnetEmbeddings for 
- scala
- python
> add python ans scala tests for XlnetEmbeddings

- python/sparknlp/training.py
Python wrapper was missing for PubTator reader
> add new PubTator reader to python

- docs/en/annotators.md
- docs/en/licensed_annotators.md
- docs/en/transformers.md
Documentation update for new features in 2.5.0:
- AlbertEmbeddings annotator
- XlnetEmbeddings annotator
- ContextSpellChecker annotator
- SentimentDL annotator
- outputLogsPath param for NerDLApproach, ClassifierDLApproach and SentimentDLApproach annotators
> Updated documentation for new features in the 2.5.0 release

- docs/en/concepts.md
Spell correction in documentation
Spell correction in documentation
> Spell correction

- docs/en/evaluation.md
Fixed multi-language selection
> Fixed multi language selection tabs

- src/main/scala/com/johnsnowlabs/storage/RocksDBConnection.scala
- src/main/scala/com/johnsnowlabs/storage/StorageBatchWriter.scala
- src/main/scala/com/johnsnowlabs/storage/StorageWriter.scala
Provides the mapping of more methods for the RocksDb interface:
- extra param for merge method
- actual exposure of merge method
Disambiguation and other downstream models make use of different storage capabilities and need this merge method.
Existing tests for Annotators using storages (WordEmbeddings, BigTextMatchers)
Serialization test for Disambiguation
> Improve RocksDB connection

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/common/TokenParser.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
> changed param name to avoid collision

- docs/en/annotators.md
Added missing annotator to the docs
> add NerConverter to the docs

- python/sparknlp/internal.py
- python/sparknlp/util.py
> 253 conllgenerator python wrapper

- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
Move fix to the previous operation in computeTrellis
> Context spell checker fix

- docs/en/ocr_pipeline_components.md
- docs/en/ocr_release_notes.md
Spark OCR 1.5.0 release update
> Spark OCR 1.5.0 release update

- docs/videos.md
added some new links on the articles page
some new videos are available and we should publish them here also
I have tested the changes on my local env.
- [o ] Code improvements with no or little impact
- [o ] I have updated the documentation accordingly.
> added new video links

- docs/en/annotators.md
Updates for annotator docs for NER converter and DeepSentenceDetector.
Also fixed a few minor inaccuracies in the examples and in general.
Also enhanced readability by adding a few missing linebreaks
Tested via running Jekyll server locally and confirming updates are correct
> Annotator docs updates

- src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
This PR presents a fix for `setGraphFolder` param inside NerDLApproach when the FileSysem is HDFS.
> Fix HDFS compatibility in gaphFolder param for NerDLApproach

- docs/en/licensed_annotators.md
> Adding DeIdentifcation code sample

- src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala
`com.johnsnowlabs.ml.tensorflow.Logging` uses OutputHelper#writeAppend to output logs to a specific file. This is working fine in a local file system but produces the following error when trying to use an hdfs path. 
```
java.io.FileNotFoundException: Failed to append to non-existent file /balanced/POP/lemmaprecleanpostcleannozips/negative_classes=2/negative_sampling_ratio=2/classifier_bert_logs/ClassifierDL_62c13b6ecd40.log
```
An example of this is:
```
val logsPath = "hdfs:///balanced/POP/lemmanonumsnopunctnostop/negative_classes=2/negative_sampling_ratio=10/classifier_elmo_logs"
val docClassifier = new ClassifierDLApproach()
.setInputCols("sentenceEmbeddings")
.setOutputCol("class")
.setLabelColumn("label")
.setEnableOutputLogs(true)
.setOutputLogsPath(logsPath)
.setVerbose(0) …
```
> OutputHelper#writeAppend: Create file if not exists before trying to append to it

- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
This PR makes sure the number of labels/classes in SentimenDL and ClassifierDL are at least 2 or above.
> Make sure the SentimentDL and ClassifierDL are at least binary

- python/sparknlp/annotator.py
- python/sparknlp/internal.py
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
- src/main/scala/com/johnsnowlabs/nlp/annotator.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/wordpiece/WordpieceTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddingsTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddingsTestSpec.scala
This PR will introduce a new annotator for reduce_mean of the last layer to generate sentence embeddings.
- It also introduces dynamic paddings to improve performance in both word and sentence embeddings
> Introducing BertSentenceEmbeddings

- src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
> fixed in Tokenizer for exceptions and sentences

- docs/en/ocr_pipeline_components.md
- docs/en/ocr_release_notes.md
- docs/en/ocr_structures.md
> Ocr documentation update 160

- docs/en/install.md
Corrected 2 typos, budling instaed of building,compling instead of compiling.
It's a typo that noticeable as you read.
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
> Update typo install.md

- docs/_layouts/landing.html
- docs/en/concepts.md
- docs/learn.md
> docs update

- docs/_data/navigation.yml
- docs/modelmain.md
> added models landing page

- docs/_includes/scripts/programmingLanguageSwitcherScalaPython.js
- docs/_posts/2020-01-30-assertion_dl_en.md
- docs/_posts/2020-01-30-assertion_ml_en.md
- docs/_posts/2020-01-30-ner_bionlp_en.md
- docs/_posts/2020-01-30-ner_clinical_en.md
- docs/_posts/2020-03-19-explain_document_dl.md
- docs/_posts/2020-03-25-ner_drugs_en.md
- docs/_posts/2020-03-25-ner_events_clinical_en.md
- docs/_posts/2020-03-26-ner_healthcare_en.md
- docs/_posts/2020-04-15-ner_posology_en.md
- docs/_posts/2020-04-22-ner_anatomy_en.md
- docs/_posts/2020-04-22-ner_cellular_en.md
- docs/_posts/2020-04-22-ner_jsl_en.md
- docs/_posts/2020-04-22-ner_jsl_enriched_en.md
- docs/_posts/2020-04-22-ner_posology_large_en.md
- docs/_posts/2020-04-22-ner_posology_small_en.md
- docs/_posts/2020-04-22-ner_risk_factors_en.md
- docs/_posts/2020-05-21-assertion_dl_large_en.md
- docs/_posts/2020-05-23-ner_clinical_large_en.md
- docs/_posts/2020-08-09-re_clinical_en.md
- docs/_posts/2020-08-19-explain_clinical_doc_carp_en.md
- docs/_posts/2020-08-19-explain_clinical_doc_era_en.md
- docs/_sass/custom.scss
- docs/en/licensed_install.md
- docs/en/ocr.md
- docs/en/ocr_pipeline_components.md
> Website updates

- src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLTestSpec.scala
This PR will add a unit test for MultiClassifierDL in Scala
> Add MultiClassifierDL unit test in Scala

- docs/_posts/2020-03-17-ner_diseases_en.md
- docs/_posts/2020-04-17-spellcheck_clinical_en.md
- docs/_posts/2020-04-21-chunkresolve_icd10cm_clinical_en.md
- docs/_posts/2020-04-21-chunkresolve_icd10pcs_clinical_en.md
- docs/_posts/2020-04-21-chunkresolve_icdo_clinical_en.md
- docs/_posts/2020-05-07-assertion_i2b2_en.md
- docs/_posts/2020-05-10-wikiner_6B_100_pl.md
- docs/_posts/2020-05-10-wikiner_6B_100_pt.md
- docs/_posts/2020-05-10-wikiner_6B_300_pl.md
- docs/_posts/2020-05-10-wikiner_6B_300_pt.md
- docs/_posts/2020-05-10-wikiner_840B_300_pl.md
- docs/_posts/2020-05-10-wikiner_840B_300_pt.md
- docs/_posts/2020-05-16-chunkresolve_loinc_clinical_en.md
- docs/_posts/2020-05-19-deidentify_rb_no_regex_en.md
- docs/_posts/2020-06-20-chunkresolve_snomed_findings_clinical_en.md
- docs/_posts/2020-06-24-chunkresolve_rxnorm_xsmall_clinical_en.md
- docs/_posts/2020-07-08-ner_deid_enriched_en.md
- docs/_posts/2020-07-08-ner_diag_proc_es.md
- docs/_posts/2020-07-08-ner_neoplasms_es.md
- docs/_posts/2020-07-14-stopwords_eo.md
- docs/_posts/2020-07-22-ner_deid_large_en.md
- docs/_posts/2020-07-27-chunkresolve_rxnorm_cd_clinical_en.md
- docs/_posts/2020-07-27-chunkresolve_rxnorm_sbd_clinical_en.md
- docs/_posts/2020-07-27-chunkresolve_rxnorm_scd_clinical_en.md
- docs/_posts/2020-08-04-deidentify_large_en.md
- docs/_posts/2020-08-18-ner_events_clinical_en.md
Removed some tags and updated the data source text for some of the models.
> tags removal + Data source text updated

- docs/_posts/2020-03-17-ner_posology_en.md
- docs/_posts/2020-04-15-ner_posology_en.md
- docs/_posts/2020-04-21-ner_posology_large_en.md
- docs/_posts/2020-04-21-ner_posology_small_en.md
- docs/_posts/2020-04-22-ner_anatomy_en.md
- docs/_posts/2020-04-22-ner_cancer_genetics_en.md
- docs/_posts/2020-04-22-ner_posology_large_en.md
- docs/_posts/2020-04-22-ner_posology_small_en.md
- docs/_posts/2020-04-22-ner_risk_factors_en.md
- docs/en/install.md
small changes to the docs page + models hub pages.
> Databricks install instructions + streamlit apps links for some models

- docs/_posts/2020-09-13-sentence_detector_dl_healthcare_en.md
Just removing unnecessary columns from DeepSentenceDetector docs
> Code sample update for DeepSentenceDetector

- src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/AveragedPerceptron.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronUtils.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/util/Utilities.scala
Profiled and improved bottlenecks in algorithms of these two important annotators. Should not impact accuracy at all.
> Improved POS and Norvig Spell Checker performance

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLModel.scala
Add a parameter 'explodeSentences' with a corresponding getter/setter, just like in SentenceDetector. Python wrapping also added and tested.
> Added option to explode sentences from SentenceDetectorDL

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/common/DatasetHelpers.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/common/Tagged.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
- src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
This change allows the training process to be memory optimized. Training will take a fixed memory size regardless of the dataset size.
The downside to this is a slow down of about 2X.
> Improve ner memory management during training

- docs/en/licensed_release_notes.md
Just adding some new lines that were missing
> 270 fixed licensed release notes

- docs/_posts/2020-11-04-ner_anatomy_coarse_biobert_en.md
- docs/_posts/2020-11-04-ner_anatomy_coarse_en.md
> ner_anatomy_coarse desc added

- docs/_posts/2020-04-22-ner_anatomy_en.md
- docs/_posts/2020-07-03-classifierdl_use_emotion_en.md
- docs/_posts/2020-07-03-classifierdl_use_fakenews_en.md
- docs/_posts/2020-07-03-classifierdl_use_sarcasm_en.md
- docs/_posts/2020-07-03-classifierdl_use_spam_en.md
- [x ] Code improvements with no or little impact
> [skip travis] emotion models fix

- docs/_posts/2020-07-03-classifierdl_use_cyberbullying_en.md
- docs/_posts/2020-07-03-classifierdl_use_emotion_en.md
- docs/_posts/2020-07-03-classifierdl_use_fakenews_en.md
- docs/_posts/2020-07-03-classifierdl_use_sarcasm_en.md
- docs/_posts/2020-07-03-classifierdl_use_spam_en.md
- [x ] Code improvements with no or little impact
> [skip travis]  emotions models fixes

- docs/_posts/2020-04-22-ner_anatomy_en.md
- docs/_posts/2020-11-04-ner_anatomy_coarse_biobert_en.md
- docs/_posts/2020-11-04-ner_anatomy_coarse_en.md
> [skip travis] MH - ner anatomy corrected

- docs/en/alab.md
> [skip travis] Alab.md

- docs/en/ocr_install.md
- docs/en/ocr_pipeline_components.md
- docs/en/ocr_release_notes.md
- docs/en/ocr_structures.md
Spark OCR 1.8.0 documentation update
> Spark OCR 1.8.0 documentation update

- docs/en/alab.md
> [skip travis] link fix

- .github/workflows/build_and_test.yml
- CHANGELOG
- README.md
- build.sbt
- docs/en/concepts.md
- docs/en/install.md
- python/setup.py
- python/sparknlp/__init__.py
- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
- src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
- src/main/scala/com/johnsnowlabs/nlp/HasPretrained.scala
- src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala
- src/main/scala/com/johnsnowlabs/util/Build.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddingsTestSpec.scala
* Fix loading from a local folder with no access to the cache folder https://github.com/JohnSnowLabs/spark-nlp/pull/1141
* Fix NullPointerException in DocumentAssembler when there are null in the rows https://github.com/JohnSnowLabs/spark-nlp/pull/1145
* Fix dynamic padding in BertSentenceEmbeddings https://github.com/JohnSnowLabs/spark-nlp/pull/1162
> 264 release candidate

- docs/_sass/custom.scss
- docs/en/release_notes.md
- docs/learn.md
> [skip travis] learn

- docs/_posts/2020-05-05-pos_ud_iu_uk.md
> uk fix [skip ci]

- docs/_posts/2020-05-04-pos_ud_tal_sv.md
- [ x] Code improvements with no or little impact
> spanish pos update [skip ci]

- docs/_posts/2020-11-27_sbiobert_base_cased_mli_en.md
- docs/_posts/2020-11-27_sbiobertresolve_cpt_en.md
- docs/_posts/2020-11-27_sbiobertresolve_icd10cm_en.md
- docs/_posts/2020-11-27_sbiobertresolve_icd10pcs_en.md
- docs/_posts/2020-11-27_sbiobertresolve_icdo_en.md
- docs/_posts/2020-11-27_sbiobertresolve_rxnorm_en.md
- docs/_posts/2020-11-27_sbiobertresolve_snomed_auxConcepts_en.md
- docs/_posts/2020-11-27_sbiobertresolve_snomed_auxConcepts_int_en.md
- docs/_posts/2020-11-27_sbiobertresolve_snomed_findings_en.md
- docs/_posts/2020-11-27_sbiobertresolve_snomed_findings_int_en.md
- docs/_posts/2020-11-27_sbluebert_base_uncased_mli_en.md
> [skip ci] MH - new resolvers and sbert mds added

- docs/en/licensed_release_notes.md
> Release Notes Docs update for 2.7.1

- docs/_posts/2020-11-27-sbiobert_base_cased_mli_en.md
- docs/_posts/2020-11-27-sbiobertresolve_cpt_en.md
- docs/_posts/2020-11-27-sbiobertresolve_icd10cm_en.md
- docs/_posts/2020-11-27-sbiobertresolve_icd10pcs_en.md
- docs/_posts/2020-11-27-sbiobertresolve_icdo_en.md
- docs/_posts/2020-11-27-sbiobertresolve_rxnorm_en.md
- docs/_posts/2020-11-27-sbiobertresolve_snomed_auxConcepts_en.md
- docs/_posts/2020-11-27-sbiobertresolve_snomed_auxConcepts_int_en.md
- docs/_posts/2020-11-27-sbiobertresolve_snomed_findings_en.md
- docs/_posts/2020-11-27-sbiobertresolve_snomed_findings_int_en.md
- docs/_posts/2020-11-27-sbluebert_base_uncased_mli_en.md
Indentation on type under article_header
> Indentation fix on models hub posts [skip ci]

- README.md
> Fixed typos in README file

- docs/learn.md
> [skip ci] update

- docs/_posts/maziyarpanahi/2020-12-05-detect_language_bigru_21_xx.md
- docs/_posts/maziyarpanahi/2020-12-05-onto_bert_base_cased_en.md
> Models hub

- docs/learn.md
> Update lear.md [skip ci]

- docs/_posts/HashamUlHaq/2020-12-09-lemma_he.md
- docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_electra_large_en.md
> Models hub [skip ci]

- docs/en/ocr_pipeline_components.md
- docs/en/ocr_release_notes.md
Ocr documentation update related 1.9.0 release
> Ocr documentation update related 1.9.0 release

- docs/demo.md
> 04 01 21 [skip ci]

- docs/_posts/dcecchini/2021-01-03-ner_ud_kaist_glove_840B_300d_ko.md
> Updated model name and AWS S3 link

- src/test/scala/com/johnsnowlabs/nlp/AssertAnnotations.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/LemmatizerTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/WordSegmenterTest.scala
- src/test/scala/com/johnsnowlabs/nlp/training/CoNLLUTestSpec.scala
Refactor of AssertAnnotations object
Rename a method and added invocation on WordSegmenter unit tests
To have a cleaner code and remove duplicated code
> Refactors AssertAnnotations

- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLModel.scala
The release of 2.7.0 fixed one of the issues that made trained classifier annotators () not be used right after without savings. However, there is an issue with saving the trained models in Databricks due to `bad magic` error. This error indicates the TF Session/Variables in the memory don't match and corrupted.
This PR fixes the issue of saving the models while keeping the other fixes stable. However, due to chang in TF models, read, and write functions all previously saved models must be re-trained and re-saved including pre-trained models prior to 2.7.1 release.
> Fix for classifiers annotator in Cluster

- docs/_includes/article-footer.html
- docs/_includes/programmingLanguageSelectScalaPython.html
- docs/_includes/programmingLanguageSelectScalaPythonNLU.html
- docs/_includes/scripts/custom.js
- docs/_includes/scripts/programmingLanguageSwitcherScalaPython.js
- docs/en/concepts.md
> Update [skip ci]

- docs/_posts/dcecchini/2021-01-14-sentiment_jager_use_th.md
> Added model name to title

- docs/_posts/dcecchini/2021-01-14-sentiment_jager_use_th.md
> Small corrections on the documentation of Thai sentiment analysis model

- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMarian.scala
This PR fixes the issue with Decoder Casual Mask in MarianTransformer. Initially, it was filled with Float(0), but the inputs must be a matrix of Float(0) where the upper triangulation is Float(-inf). This was reported in German to English model which works fine after this fix.
> Fix decoder casual mask input

- docs/en/ocr_pipeline_components.md
- docs/en/ocr_release_notes.md
Updated documentation according to the 1.10.0 Spark OCR release
> Updated documentation according to the 1.10.0 Spark OCR release

- docs/_posts/dcecchini/2021-01-03-pos_ctb9_zh.md
- docs/_posts/dcecchini/2021-01-03-pos_ud_gsd_ja.md
- docs/_posts/dcecchini/2021-01-03-pos_ud_gsd_zh.md
- docs/_posts/dcecchini/2021-01-03-pos_ud_kaist_ko.md
- docs/_posts/dcecchini/2021-01-13-pos_lst20_th.md
- docs/_posts/dcecchini/2021-01-18-pos_ud_bhtb_bh.md
I added standard links for `Live Demo` and `Colab` links for all the POS models I trained. 
Documentation improvement and standardization.
> Improved documentation of POS models

- docs/_posts/dcecchini/2021-01-15-lemma_ja.md
- docs/_posts/dcecchini/2021-01-15-lemma_ko.md
- docs/_posts/dcecchini/2021-01-18-lemma_bh.md
Added live demo and colab links to Lemma models (JA, KO, BH).
Better and standardized documentation.
> Added live demo and colab links to Lemma models (JA, KO, BH)

- docs/learn.md
> Update learn.md [skip ci]

- docs/_posts/2020-11-27-sbiobertresolve_cpt_en.md
- docs/_posts/2020-11-27-sbiobertresolve_icd10cm_en.md
- docs/_posts/2020-11-27-sbiobertresolve_icd10pcs_en.md
- docs/_posts/2020-11-27-sbiobertresolve_icdo_en.md
- docs/_posts/2020-11-27-sbiobertresolve_rxnorm_en.md
- docs/_posts/2020-11-27-sbiobertresolve_snomed_auxConcepts_en.md
- docs/_posts/2020-11-27-sbiobertresolve_snomed_auxConcepts_int_en.md
- docs/_posts/2020-11-27-sbiobertresolve_snomed_findings_en.md
- docs/_posts/2020-11-27-sbiobertresolve_snomed_findings_int_en.md
- docs/_posts/2020-12-11-sbiobertresolve_rxcui_en.md
- docs/_posts/2020-12-13-sbiobertresolve_icd10cm_augmented_en.md
> [skip_ci] updating colab links of sbiobertreslove models

- python/sparknlp/annotator.py
Updated documentation for the get classes function
No tests required
> fix typo in getClasses function

- docs/_posts/dcecchini/2021-01-29-ner_drugs_large_en.md
Added documentation for the existing model `ner_drugs_large` (added in Spark NLP for Healthcare 2.7.1).
The documentation page was not found on [Models Hub](https://nlp.johnsnowlabs.com/models).
> Added documentation for ner_drugs_large

- .gitignore
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLApproach.scala
Adding graph def loader in sentence detector DL approach
> Fixed TF2 graph loading in SentenceDetectorDLApproach

- docs/_includes/footer.html
- docs/learn.md
Update Learn items and change footer`s date
> [skip ci] Update Learn items and footer date

- README.md
> Updated slack link

- docs/en/annotation.md
> completion docs update  [skip ci]

- docs/en/licensed_release_notes.md
> new release v273

- docs/en/quickstart.md
> [skip ci] Update slack

- build.sbt
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbert.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowElmo.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/ElmoEmbeddingsTestSpec.scala
TF2 BERT, ALBert, ELMO classes refactoring
TF2 BERT, ALBert, ELMO classes refactoring
> Added refactoring for TF2 embeddings classes

- docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_direction_biobert_en.md
- docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_problem_biobert_en.md
- docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_procedure_test_biobert_en.md
- docs/_posts/HashamUlHaq/2021-02-04-redl_chemprot_biobert_en.md
- docs/_posts/HashamUlHaq/2021-02-04-redl_clinical_biobert_en.md
- docs/_posts/HashamUlHaq/2021-02-04-redl_date_clinical_biobert_en.md
- docs/_posts/HashamUlHaq/2021-02-04-redl_drug_drug_interaction_biobert_en.md
- docs/_posts/HashamUlHaq/2021-02-04-redl_human_phenotype_gene_biobert_en.md
- docs/_posts/HashamUlHaq/2021-02-04-redl_temporal_events_biobert_en.md
- docs/_posts/HashamUlHaq/2021-02-06-sbiobertresolve_icd10cm_augmented_billable_hcc_en.md
New metadata lines inserted into the following Newly trained models :
- 2021-02-04-redl_bodypart_direction_biobert_en.md
- 2021-02-04-redl_bodypart_problem_biobert_en.md
- 2021-02-04-redl_bodypart_procedure_test_biobert_en.md
- 2021-02-04-redl_chemprot_biobert_en.md
- 2021-02-04-redl_clinical_biobert_en.md
- 2021-02-04-redl_date_clinical_biobert_en.md
- 2021-02-04-redl_drug_drug_interaction_biobert_en.md
- 2021-02-04-redl_human_phenotype_gene_biobert_en.md
- 2021-02-04-redl_temporal_events_biobert_en.md
- 2021-02-06-sbiobertresolve_icd10cm_augmented_billable_hcc_en.md
> [skip_ci] insertion of new metadata lines

- .github/workflows/build_and_test.yml
- src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala
This PR set the default OS for GA `ubuntu-18.04` and use a smaller dataset for the NerDL unit tests
> Test TF v2 on GA

- src/main/scala/com/johnsnowlabs/nlp/TokenAssembler.scala
- src/test/scala/com/johnsnowlabs/nlp/TokenAssemblerTestSpec.scala
Fixed index error for the sentence "I have some plpitations in my chest."
Created new test for the fix
> fix for "Check odd behavior in TokenAssembler"

- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLModel.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLTestSpec.scala
Fix #2287 Ignore if there are no embeddings
Return empty annotation seq, if there are zero sentences to process
https://github.com/JohnSnowLabs/spark-nlp/issues/2287
Unit Tests
> Fix #2287 ClassifierDLModel and SentimentDLModel  fails if empty string is passed as input

- build.sbt
> shaded httpclient

- docs/_layouts/demo.html
- docs/demo.md
> Adding ids on demos [skip ci]

- docs/_config.yml
- docs/_includes/head.html
- docs/_includes/header.html
> Update Google Tag manager [skip ci]

- docs/_includes/head.html
- docs/_includes/header.html
- docs/_layouts/demo.html
> Update demos page [skip ci]

- docs/index.md
Adding new trusted sponsors on home page
> Adding new trusted users [skip ci]

- docs/en/ocr.md
- docs/en/ocr_pipeline_components.md
- docs/en/ocr_release_notes.md
- docs/en/ocr_structures.md
Ocr documentation update for 1.11.0 release
> Ocr documentation update for 1.11.0 release

- docs/_posts/maziyarpanahi/2020-12-05-onto_bert_base_cased_en.md
- docs/_posts/maziyarpanahi/2020-12-05-onto_bert_large_cased_en.md
- docs/_posts/maziyarpanahi/2020-12-05-onto_electra_base_uncased_en.md
- docs/_posts/maziyarpanahi/2020-12-05-onto_electra_large_uncased_en.md
- docs/_posts/maziyarpanahi/2020-12-05-onto_electra_small_uncased_en.md
- docs/_posts/maziyarpanahi/2020-12-05-onto_small_bert_L2_128_en.md
- docs/_posts/maziyarpanahi/2020-12-05-onto_small_bert_L4_256_en.md
- docs/_posts/maziyarpanahi/2020-12-05-onto_small_bert_L4_512_en.md
- docs/_posts/maziyarpanahi/2020-12-05-onto_small_bert_L8_512_en.md
- docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_multi_lg_xx.md
- docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_multi_xx.md
- docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_de_xx.md
- docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_es_xx.md
- docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_fr_xx.md
- docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_many_xx.md
- docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_base_en.md
- docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_large_en.md
- docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_medium_en.md
- docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_mini_en.md
- docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_small_en.md
- docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_tiny_en.md
- docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_electra_base_en.md
- docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_electra_small_en.md
> [skip ci] Insertion of NLU blocks into onto-ner-models/pipelines and multi lingual use embeddings

- docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_emotion_en.md
- docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_fakenews_en.md
- docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_sarcasm_en.md
- docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_spam_en.md
- docs/_posts/HashamUlHaq/2021-01-09-sentimentdl_glove_imdb_en.md
- docs/_posts/HashamUlHaq/2021-01-21-classifierdl_ade_biobert_en.md
- docs/_posts/HashamUlHaq/2021-01-21-classifierdl_ade_clinicalbert_en.md
- docs/_posts/HashamUlHaq/2021-01-21-classifierdl_ade_conversational_biobert_en.md
- docs/_posts/HashamUlHaq/2021-01-21-classifierdl_gender_biobert_en.md
- docs/_posts/HashamUlHaq/2021-01-21-classifierdl_gender_sbert_en.md
- docs/_posts/HashamUlHaq/2021-01-21-classifierdl_pico_biobert_en.md
> [skip ci] fixing nlu blocks conflict

- docs/models.json
> added metadata to models.json [skip ci]

- docs/en/annotators.md
> [skip ci] updates of public annotator pages

- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
Small fix for NER training and confidence score errors in TF
> fix for BigDecimal bug in NER training

- docs/_posts/C-K-Loan/2021-03-05-pos_anc_spk3_en.md
updated missing metadata fields for the `pos_anc` model.
> pos anc docs update

- python/sparknlp/annotator.py
Added batch annotator in BertSentenceEmbeddings Python
Added batch annotator in BertSentenceEmbeddings Python
Added batch annotator in BertSentenceEmbeddings Python
Local non reg test and Databricks 8.0 ML runtime
> Added batch annotator in BertSentenceEmbeddings Python

- docs/demo.md
- docs/learn.md
Add GloVe, ELMo & BERT article in Document Classification
Fix link Detect legal entities in German
> Add GloVe, ELMo & BERT article 

- .github/workflows/create_search_index.yml
- docs/_plugins/search_index.rb
* Remove renamed or deleted posts from the search index.
* Index name, tags and more content in the body.
> Search index improvements

- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
> replaced nulls with proper variables

- docs/en/ocr.md
- docs/en/ocr_install.md
- docs/en/ocr_pipeline_components.md
- docs/en/ocr_release_notes.md
- docs/en/ocr_structures.md
Updated documentation related Spark OCR 3.0.0 release
> Updated documentation related Spark OCR 3.0.0 release

- docs/en/licensed_release_notes.md
> update in healthcare release notes

- docs/_posts/HashamUlHaq/2021-03-31-ner_healthcare_de.md
- docs/_posts/aydinmyilmaz/2021-01-18-re_bodypart_directions_en.md
For issue  #412 on streamlit demos (https://github.com/JohnSnowLabs/streamlit-demo-apps/issues/412), made the following changes
**modified:   docs/_posts/HashamUlHaq/2021-03-31-ner_healthcare_de.md**
- model name changed as the embeddings and annotator do not have the same storage ref by default
**modified:   docs/_posts/aydinmyilmaz/2021-01-18-re_bodypart_directions_en.md**
- model name changed due to typo
> Code Examples Bug Fixes

- docs/_data/navigation.yml
- docs/_layouts/demopage.html
- docs/_sass/custom.scss
- docs/assets/images/arrow.svg
- docs/demos/analyze_non_english_medical_text.md
- docs/demos/analyze_specialty_reports.md
- docs/demos/analyze_spelling_grammar.md
- docs/demos/classify_documents.md
- docs/demos/deidentification.md
- docs/demos/detect_sentiment_emotion.md
- docs/demos/east_asian_languages.md
- docs/demos/enhance_low_quality_images.md
- docs/demos/european_languages.md
- docs/demos/extract_relationships.md
- docs/demos/extract_tables_structured_data.md
- docs/demos/extract_text_from_documents.md
- docs/demos/identify_translate_languages.md
- docs/demos/infer_meaning_intent.md
- docs/demos/languages_india.md
- docs/demos/middle_eastern_languages.md
- docs/demos/recognize_biomedical_entities.md
- docs/demos/recognize_clinical_entities.md
- docs/demos/recognize_entitie.md
- docs/demos/recognize_social_determinants.md
- docs/demos/resolve_entities_codes.md
- docs/demos/split_clean_medical_text.md
- docs/index.md
Add demos on
Spark NLP: English
Spark NLP: World Languages
Spark NLP for Healthcare 
Spark OCR:
> [skip ci] Update NLP demos page

- docs/en/licensed_annotators.md
Update the Annotators page with updated documentation. Created a WIP script that converts the scala doc to markdown (but only available for classes that have the scaladoc) 
added/updated so far:
- AssertionDL
- AssertionFilterer
- ChunkFilterer
- ChunkMerge
- IOBTagger
- NerConverterInternal
- NerDisambiguator
> Healthcare Anno Page Update

- docs/_data/navigation.yml
- docs/_includes/demomenu.html
- docs/_layouts/demopage.html
- docs/_sass/custom.scss
- docs/demos/extract_tables_structured_data.md
> Publish new demos page

- docs/_posts/HashamUlHaq/2021-04-29-sbiobertresolve_loinc_en.md
- docs/_posts/HashamUlHaq/2021-04-29-sbluebertresolve_loinc_en.md
> sbiobertresolve loinc download url fixed

- docs/_includes/demomenu.html
- docs/demos/split_clean_medical_text.md
> Little demo page fix

- docs/_posts/Digaari/2021-04-30-explain_document_lg_ko.md
Added a NER Pipeline for Korean.
The Pipeline is made from the model: https://nlp.johnsnowlabs.com/2021/01/03/ner_ud_kaist_glove_840B_300d_ko.html
> 2021-04-30-explain_document_lg_ko

- docs/_posts/Digaari/2021-04-30-explain_document_lg_he.md
Added a NER Pipeline for Hebrew.
The Pipeline is made from the model: https://nlp.johnsnowlabs.com/2020/12/09/hebrewner_cc_300d_he.html
> 2021-04-30-explain_document_lg_he

- src/main/scala/com/johnsnowlabs/nlp/HasBatchedAnnotate.scala
Avoid type erasure warning in compile.
Avoid type erasure warning in compile.
Avoid type erasure warning in compile.
Non regression tests.
[info] Suites: completed 89, aborted 0
[info] Tests: succeeded 416, failed 0, canceled 0, ignored 1, pending 0
[info] All tests passed.
> Added unchecked annotation to suppress type erasure warning

- docs/_posts/HashamUlHaq/2021-05-05-sbiobertresolve_HPO_en.md
model name changed in sample python code.
> HPO model name in python code fixed

- docs/demos/analyze_non_english_medical_text.md
- docs/demos/extract_text_from_documents.md
Detect Diagnoses And Procedures In Spanish
Logical Observation Identifiers Names and Codes (LOINC)
Map Healthcare Codes
DOCX to Text
> Add new demos

- docs/en/licensed_release_notes.md
> added release notes for healthcare 3.0.3

- src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeSpecialTokens.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizerTestSpec.scala
Added BPE Tokenizer for future implementations of e.g. RoBERTa, GPT-2.
Tests added in src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizerTestSpec.scala
> BPE, input IndexToken, Output Array[TokenPiece]

- src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizer.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizerTestSpec.scala
> End Index changed, prepend space for token without one

- docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_medium_umls_uncased_en.md
- docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_medium_uncased_en.md
- docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_mini_umls_uncased_en.md
- docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_mini_uncased_en.md
- docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_tiny_umls_uncased_en.md
- docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_tiny_uncased_en.md
- docs/_posts/HashamUlHaq/2021-05-14-sbiobert_jsl_cased_en.md
- docs/_posts/HashamUlHaq/2021-05-14-sbiobert_jsl_umls_cased_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_HPO_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_cpt_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_augmented_billable_hcc_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_augmented_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10pcs_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icdo_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_loinc_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_rxcui_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_rxnorm_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_auxConcepts_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_auxConcepts_int_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_findings_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_findings_int_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_umls_findings_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_umls_major_concepts_en.md
- docs/_posts/HashamUlHaq/2021-05-17-sbiobertresolve_icd10cm_slim_normalized_en.md
- docs/_posts/maziyarpanahi/2021-05-20-bert_base_dutch_cased_nl.md
- docs/_posts/maziyarpanahi/2021-05-20-bert_base_german_cased_de.md
> Models hub dev

- src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/moses/MosesTokenizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/normalizer/MosesPunctNormalizer.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/moses/MosesTokenizerTestSpec.scala
Further performance optimizations for Moses related classes
Included tests are passing
> Moses Optimizations

- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_HPO_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_cpt_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_augmented_billable_hcc_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_augmented_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10pcs_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icdo_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_loinc_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_rxcui_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_rxnorm_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_auxConcepts_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_auxConcepts_int_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_findings_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_findings_int_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_umls_findings_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_umls_major_concepts_en.md
Upload details added to v304 sentence ER model .md files
> Upload optimization details added

- docs/_includes/demomenu.html
- docs/_sass/custom.scss
- docs/demos/languages_africa.md
Add Free sign
Rename some demos
> Add Free sign

- project/Dependencies.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
Migration to TF 2.4.1 using Java bindings 0.3.1 .
Version | Python version | Compiler | Build tools | cuDNN | CUDA
tensorflow-2.4.0 | 3.6-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 8.0 | 11.0
Bumping version to migrate TF 2.4.1 using Java bindigs which are now using CUDA capabilities from official TF releases.
Fix memory leaks occurring with new TensorFlow 2.4.1 layout of string tensors .
Fix and use JavaCPP deallocator for releasing graph sessions .
Local non regression test.
[info] Suites: completed 94, aborted 0
[info] Tests: succeeded 429, failed 0, canceled 0, ignored 1, pending 0
[info] All tests passed.
> Migration to TF 2.4.1 with Java bindings 0.3.1

- python/sparknlp/annotator.py
- python/sparknlp/internal.py
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowRoBerta.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlmRoberta.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/SentencepieceEncoder.scala
- src/main/scala/com/johnsnowlabs/nlp/annotator.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddingsTestSpec.scala
> Introducing new XlmRoBertaEmbeddings annotator

- docs/_posts/muhammetsnts/2021-05-25-sbiobertresolve_icd10cm_slim_billable_hcc_en.md
> Typo fixed, title changed

- src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/XlmTokenizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/normalizer/MosesPunctNormalizer.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/normalizer/MosesPunctNormalizerTestSpec.scala
Slightly refactored MosesPunctNormalizer and added test
Added new test for MosesPunctNormalizer
> MosesPunctNormalizer improvements

- docs/_posts/2020-11-27-sbiobertresolve_cpt_en.md
- docs/_posts/2020-11-27-sbiobertresolve_icd10cm_en.md
- docs/_posts/2020-11-27-sbiobertresolve_icd10pcs_en.md
- docs/_posts/2020-11-27-sbiobertresolve_icdo_en.md
- docs/_posts/2020-11-27-sbiobertresolve_rxnorm_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_cpt_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10pcs_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icdo_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_rxcui_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_rxnorm_en.md
> typo fixed

- docs/en/ocr_pipeline_components.md
- docs/en/ocr_release_notes.md
Documentation update for Spark OCR 3.2.0 release
> Documentation update for Spark OCR 3.2.0 release

- src/test/resources/ner-corpus/ner_fake_connl_cv.txt
- src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerPerfTest.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/DistilBertEmbeddingsTestSpec.scala
DistilBertEmbeddingsTestSpec and NerPerfTest had errors in slow tests. Minor changes fixed them.
Some slow tests were missing the required information in interface to run properly.
Fixing the interfaces.
> Added slow tests fixes on distilbert and ner crf

- src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
> Fix ContextSpellCheckerTestSpec  test in scala 11 .

- docs/_posts/C-K-Loan/2021-03-08-pos_ud_hdt_de.md
fixed issues that were in the examples. also updated link to colab notebook.
> fix examples for pos_ud_hdt_de

- docs/demos/recognize_clinical_entities.md
Remove Detect Clinical Entities in Radiology Reports
> Remove demo

- docs/_posts/murat-gunay/2021-03-18-assertion_dl_radiology_en.md
> example fixed in assertion_radiology

- docs/demos/extract_relationships.md
Detect how dates relate to clinical entities
> Add new demo

- docs/_posts/C-K-Loan/2021-03-29-recognize_entities_posology_en.md
- docs/_posts/HashamUlHaq/2021-02-19-ner_deid_synthetic_en.md
> corrected library versions of two models

- docs/_layouts/demopage.html
- docs/_sass/custom.scss
- docs/demos/analyze_non_english_medical_text.md
- docs/demos/recognize_clinical_entities.md
- docs/demos/resolve_entities_codes.md
Hide
https://demo.johnsnowlabs.com/healthcare/ER_SNOMED/
https://demo.johnsnowlabs.com/healthcare/ER_ICDO/
https://demo.johnsnowlabs.com/healthcare/ER_ICD10_CM/
https://demo.johnsnowlabs.com/healthcare/ER_RXNORM/
https://demo.johnsnowlabs.com/healthcare/ER_LOINC/
https://demo.johnsnowlabs.com/healthcare/ER_ICD10_GM_DE/
> Hide some demos

- docs/en/transformers.md
> added explanations on transformers import

- docs/en/concepts.md
Fix typo in docs
"lemma" -> "lemmas"
The code in [Manipulating pipelines](https://nlp.johnsnowlabs.com/docs/en/concepts#manipulating-pipelines) currently throws an error.
Ran the snippet in [Manipulating pipelines](https://nlp.johnsnowlabs.com/docs/en/concepts#manipulating-pipelines) successfully.
> Fix typo in `concepts.md`

- python/test/annotators.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLTestSpec.scala
Added Missing getter/setter for randomSeed parameter for 
- ClassifierDLApproach, 
- MultiClassifierDLApproach and 
- SentimentDLApproach
For the python classes, the api was already implemented.
Users should be able to set these paramaters.
Set the parameter in python and scala tests and tests are passing.
> Missing getter/setter for random seed

- src/main/scala/com/johnsnowlabs/nlp/annotators/keyword.yake/YakeModel.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/keyword/yake/YakeTestSpec.scala
When passing in rows of collections of tokens that may or may not be empty, the yake model will throw this exception:
`[info] Caused by: java.lang.UnsupportedOperationException: empty.max`
`[info] 	at scala.collection.TraversableOnce.max(TraversableOnce.scala:275)`
`[info] 	at scala.collection.TraversableOnce.max$(TraversableOnce.scala:273)`
`[info] 	at scala.collection.AbstractTraversable.max(Traversable.scala:108)`
`[info] 	at com.johnsnowlabs.nlp.annotators.keyword.yake.YakeModel.calculateTokenScores(YakeModel.scala:182)`
`[info] 	at com.johnsnowlabs.nlp.annotators.keyword.yake.YakeModel.processSentences(YakeModel.scala:316)`
`[info] 	at com.johnsnowlabs.nlp.annotators.keyword.yake.YakeModel.annotate(YakeModel.scala:340)`
`[info] 	at …
> Fixing yake bug, was throwing exception on empty token input

- docs/_posts/albertoandreottiATgmail/2021-03-30-spellcheck_clinical_en.md
> [skip ci] fixing version metadata

- docs/_data/navigation.yml
- docs/en/ocr.md
- docs/en/ocr_object_detection.md
- docs/en/ocr_release_notes.md
Update documentation for Spark OCR 3.4.0 release
> Update documentation for Spark OCR 3.4.0 release

- docs/_posts/2020-11-27-sbiobertresolve_icdo_en.md
- docs/_posts/HashamUlHaq/2021-04-02-chunkresolve_icdo_clinical_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icdo_en.md
- docs/_posts/HashamUlHaq/2021-07-02-sbiobertresolve_cpt_procedures_measurements_augmented_en.md
- docs/_posts/HashamUlHaq/2021-07-02-sbiobertresolve_icdo_base_en.md
- docs/_posts/muhammetsnts/2021-06-22-sbiobertresolve_icdo_augmented_en.md
> mds updated for icdo and cpt resolvers

- docs/learn.md
> [skip ci] Add NLU video

- src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizerTestSpec.scala
If string cannot be encoded for roberta, return unk token.
New test and old test run successfully.
> Fixed issue with encoding unknown bytes

- docs/en/annotator_entries/RegexMatcher.md
- src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcher.scala
RegexMatcher still had some traces of the old API in the docs, this was fixed.
> Doc: Minor update for python scala API sync

- docs/en/licensed_release_notes.md
Release notes for latest 3.1.2 Spark-NLP Healthcare release.
> upgraded licensed release notes

- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModelPythonReader.scala
- src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
This PR makes sure the batchSize in NerDLModel and NerDLApproah is not part of the broadcast variable
> Make sure param is not part of the broadcast

- python/docs/requirements_doc.txt
minor adjustments to requirements.txt
> PyDoc: adjust requirements.txt

- docs/_posts/HashamUlHaq/2021-07-12-re_ade_clinical_en.md
- docs/_posts/HashamUlHaq/2021-07-12-redl_ade_biobert_en.md
- docs/_posts/HashamUlHaq/2021-07-15-explain_clinical_doc_ade_en.md
> ade_re mds updated

- docs/en/licensed_release_notes.md
> 3.1.3 licensed release notes

- docs/_data/navigation.yml
- docs/en/ocr_install.md
- docs/en/ocr_release_notes.md
- docs/en/version_compatibility.md
Added version compatibility page
> Added version compatibility page

- docs/_posts/2021-01-18-jsl_assertion_wip_large_en.md
the description of the model was changed and detailed.
> description updated

- python/sparknlp/annotator.py
- python/sparknlp/internal.py
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBertTokenClassification.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/sign/ModelSignatureConstants.scala
- src/main/scala/com/johnsnowlabs/nlp/annotator.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForTokenClassification.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForTokenClassificationTestSpec.scala
This annotator allows the use of models coming from HF trained/saved as `BertForTokenClassification`
> Introducing BertForTokenClassification annotator

- python/sparknlp/annotator.py
- python/sparknlp/internal.py
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowRoBerta.scala
- src/main/scala/com/johnsnowlabs/nlp/annotator.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/LongformerEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/LongformerEmbeddingsTestSpec.scala
This PR is introducing a new annotator for Longformer word embeddings models.
> Introducing LongformerEmbeddings annotator

- docs/en/licensed_release_notes.md
> update in release notes for licensed lib

- docs/en/licensed_release_notes.md
> changed order

- docs/en/licensed_release_notes.md
> added escaping for json

- docs/demos/recognize_entitie.md
> fix url link of fewnerd demo

- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBertClassification.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowDistilBertClassification.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlmRoberta.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForTokenClassification.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForTokenClassification.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddings.scala
This PR will remove the batchSize param from the broadcast and also hard-codes the special tokens in XML-RoBERTa
> Remove batchSize from the broadcast 

- docs/_posts/Digaari/2021-08-29-bert_muril_xx.md
Embedding Model (1 of 9) imported from: https://tfhub.dev/google/MuRIL/1
> 2021-08-29-bert_muril_xx

- docs/en/transformer_entries/AlbertEmbeddings.md
- docs/en/transformer_entries/ElmoEmbeddings.md
- docs/en/transformer_entries/XlnetEmbeddings.md
Added rest of the examples for the transformer use cases.
- AlbertEmbeddings
- ElmoEmbeddings
- XlnetEmbeddings
> Docs: Added Rest of Transformer use case examples

- docs/_posts/HashamUlHaq/2021-06-30-ner_deid_subentity_augmented_en.md
> Detect PHI for Deidentification error

- docs/en/licensed_release_notes.md
Release notes for healthcare 3.2.2, and formatting fixes.
> added release notes for hc 3.2.2

- docs/en/licensed_install.md
> don't use env vars for keys

- docs/en/licensed_install.md
> change the config for keys

- docs/en/annotators.md
- docs/en/transformer_entries/BertForTokenClassification.md
- docs/en/transformer_entries/DistilBertForTokenClassification.md
- docs/en/transformer_entries/RoBertaSentenceEmbeddings.md
- docs/en/transformer_entries/XlmRoBertaSentenceEmbeddings.md
- python/sparknlp/annotator.py
- *ForTokenClassification moved to transformers page
- Added RobertaSentenceEmbeddings, XlmRobertaSentenceEmbeddings
- additionally fixed the pydoc strings of these two, as there were some issues with the formatting
**Note:**
RobertaSentenceEmbeddings, XlmRobertaSentenceEmbeddings don't have pretrained models for prediction yet, therefore have a placeholder for the examples at the moment.
> Docs: Moved some annotators to transformers page, added new ones

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/GraphFinisher.scala
- src/main/scala/com/johnsnowlabs/nlp/HasInputAnnotationCols.scala
- src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/GraphExtraction.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala
- src/main/scala/com/johnsnowlabs/nlp/util/GraphBuilder.scala
- src/test/scala/com/johnsnowlabs/nlp/GraphFinisherTest.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/GraphExtractionFixture.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/GraphExtractionTest.scala
- src/test/scala/com/johnsnowlabs/nlp/util/GraphBuilderTest.scala
Adds support to use GraphExtraction in LightPipeline
This fix solves issue #6091 
- Unit tests in Scala
- Google Colab and Databticks notebooks
> Fix graph extraction light pipeline

- docs/_layouts/nlp_products.html
- docs/en/nlp_server/nlp_server.md
> NLP products page

- docs/_posts/muhammetsnts/2021-09-15-ner_healthcare_de.md
- docs/_posts/murat-gunay/2021-09-13-bert_token_classifier_ner_deid_en.md
> Models hub [skip test]

- docs/_posts/2020-09-24-re_clinical_en.md
- docs/_posts/2020-09-30-re_human_phenotype_gene_clinical_en.md
- docs/_posts/C-K-Loan/2021-03-27-Typed_Dependency_Parsing_en.md
- docs/_posts/C-K-Loan/2021-03-27-dependency_conllu_en.md
- docs/_posts/C-K-Loan/2021-03-27-dependency_parse_en.md
- docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_direction_biobert_en.md
- docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_problem_biobert_en.md
- docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_procedure_test_biobert_en.md
- docs/_posts/HashamUlHaq/2021-02-04-redl_date_clinical_biobert_en.md
- docs/_posts/HashamUlHaq/2021-02-04-redl_human_phenotype_gene_biobert_en.md
- docs/_posts/HashamUlHaq/2021-02-04-redl_temporal_events_biobert_en.md
- docs/_posts/HashamUlHaq/2021-04-19-re_test_problem_finding_en.md
- docs/_posts/HashamUlHaq/2021-07-12-re_ade_clinical_en.md
- docs/_posts/HashamUlHaq/2021-07-12-redl_ade_biobert_en.md
- docs/_posts/HashamUlHaq/2021-07-16-re_ade_biobert_en.md
- docs/_posts/albertoandreottiATgmail/2021-09-10-redl_bodypart_procedure_test_biobert_en.md
- docs/_posts/aydinmyilmaz/2021-01-18-re_bodypart_directions_en.md
- docs/_posts/aydinmyilmaz/2021-01-18-re_bodypart_problem_en.md
- docs/_posts/aydinmyilmaz/2021-01-18-re_bodypart_proceduretest_en.md
- docs/_posts/aydinmyilmaz/2021-01-18-re_date_clinical_en.md
- docs/_posts/muhammetsnts/2021-06-01-redl_bodypart_direction_biobert_en.md
- docs/_posts/muhammetsnts/2021-06-01-redl_bodypart_problem_biobert_en.md
- docs/_posts/muhammetsnts/2021-06-01-redl_bodypart_procedure_test_biobert_en.md
- docs/_posts/muhammetsnts/2021-06-01-redl_date_clinical_biobert_en.md
- docs/_posts/muhammetsnts/2021-07-24-redl_human_phenotype_gene_biobert_en.md
- docs/_posts/muhammetsnts/2021-07-24-redl_temporal_events_biobert_en.md
> [skip ci] fixing predicted entities of re models

- docs/_posts/murat-gunay/2021-09-03-ner_deid_subentity_augmented_en.md
since it is an urgent correction for healthcare release, it should be merged as soon as possible.
> fixing predicted entities

- src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeSpecialTokens.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/Gpt2Tokenizer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizer.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizerBehaviours.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/Gpt2TokenizerTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizerTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/XlmTokenizerTestSpec.scala
This PR contains the class for tokenizing strings in preparation for the GPT-2 model.
It includes the following changes:
- Refactored RobertaTokenizer to inherit from GPT-2 Tokenizer, as it is based on it
- Added own class and SpecialTokens for GPT-2
- Fixed a bug, when all special tokens were identical
- Fixed a bug, when special token contained valid regex (used only as literal now)
RobertaTokenizer tests are passing, added new tests for the GPT-2 Tokenizer.
> GPT-2 Tokenizer and refactoring RobertaTokenizer 

- docs/_posts/murat-gunay/2021-05-03-classifierdl_bert_news_tr.md
- docs/_posts/murat-gunay/2021-07-12-classifierdl_bert_news_de.md
- docs/_posts/murat-gunay/2021-07-21-classifierdl_berturk_cyberbullying_tr.md
- docs/_posts/murat-gunay/2021-08-13-classifierdl_berturk_cyberbullying_pipeline_tr.md
- docs/_posts/murat-gunay/2021-08-13-classifierdl_electra_questionpair_en.md
- docs/_posts/murat-gunay/2021-09-13-bert_token_classifier_ner_deid_en.md
Updated the codes that were needed to be fixed.
Fixed issues: [#585](https://github.com/JohnSnowLabs/streamlit-demo-apps/issues/585#event-5334665709) [#584](https://github.com/JohnSnowLabs/streamlit-demo-apps/issues/584#event-5334661750) [#582](https://github.com/JohnSnowLabs/streamlit-demo-apps/issues/582#event-5334657808) [#671](https://github.com/JohnSnowLabs/streamlit-demo-apps/issues/671#event-5342794599)
> Update code fixes of issues #585 #584 #582 #671

- docs/en/alab/install.md
> fixed typos

- docs/_includes/demomenu.html
> remove spark nlp special cases

- docs/_posts/2020-05-16-chunkresolve_loinc_clinical_en.md
- docs/_posts/HashamUlHaq/2021-04-02-chunkresolve_loinc_clinical_en.md
Restores fixes that were overwritten in a previous commit, and adds a fix for another detected error.
The fix is mandatory to correct the python snippet code, since the variable names were incorrect.
The changes were testes using a Notebook with the code snippet.
> Fixes wrong variable names in loinc examples in modelshub

- docs/_posts/muhammetsnts/2021-09-23-ner_profiling_biobert_en.md
Updated stages in Included Models section by using (x21) to make it shorter.
> Updated ner_profiling_biobert.md file

- README.md
- python/README.md
- python/sparknlp/internal.py
- python/sparknlp/pretrained.py
- python/test/pretrained.py
- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
- src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderMetaSpec.scala
- updated `ResourceDownloader.showPublicPipelines` to be more in line with the `ResourceDownloader.showPublicModels` function
- providing no version will use the current version to check for compatibility
- updated README.md to show examples on how to use those functions
Added tests for `ResourceDownloader.showPublicPipelines`.
> Update ResourceDownloader.showPublicPipelines interface and README.md

- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/io/ChunkBytes.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
- src/main/scala/com/johnsnowlabs/util/ConfigLoader.scala
- src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddingsTestSpec.scala
This PR uses chunking for reading and writing Array[Byte] to overcome the 2G limit in TF SavedModel size.
> Use chunk to read and write TF Variables

- docs/_posts/HashamUlHaq/2021-06-30-ner_deid_generic_augmented_en.md
- docs/_posts/muhammetsnts/2021-07-24-assertion_jsl_en.md
- docs/_posts/muhammetsnts/2021-07-24-assertion_jsl_large_en.md
- docs/_posts/murat-gunay/2021-07-22-nerdl_fewnerd_subentity_100d_en.md
- docs/_posts/murat-gunay/2021-08-13-classifierdl_bert_news_pipeline_de.md
- docs/_posts/murat-gunay/2021-08-27-classifierdl_bert_news_pipeline_tr.md
- docs/_posts/murat-gunay/2021-09-16-bert_token_classifier_ner_jsl_en.md
Made changes in the following models.
> docs/_posts/HashamUlHaq/2021-06-30-ner_deid_generic_augmented_en.md
> docs/_posts/muhammetsnts/2021-07-24-assertion_jsl_en.md
> docs/_posts/muhammetsnts/2021-07-24-assertion_jsl_large_en.md
> docs/_posts/murat-gunay/2021-07-22-nerdl_fewnerd_subentity_100d_en.md
> docs/_posts/murat-gunay/2021-08-13-classifierdl_bert_news_pipeline_de.md
> docs/_posts/murat-gunay/2021-08-27-classifierdl_bert_news_pipeline_tr.md
> docs/_posts/murat-gunay/2021-09-16-bert_token_classifier_ner_jsl_en.md
> Adding colab/Demo links and fixing code.

- docs/_data/navigation.yml
- docs/_sass/custom.scss
- docs/en/benchmark.md
> Add Benchmark in Spark NLP Healthcare

- docs/_posts/albertoandreottiATgmail/2021-09-10-redl_bodypart_procedure_test_biobert_en.md
> fixing download link

- docs/_posts/murat-gunay/2021-09-08-classifierdl_bert_sentiment_fr.md
Adds new Live Demo and Google Colab links to existing classifierdl-sentiment-model (French language).
Adds new Live Demo and Google Colab links to existing classifierdl-sentiment-model (French language) markdown file.
A new live demo and a Google colab notebook were created, so we need to update the Modelshub page to reflect the changes.
New links have been tested in md file to check that they are correctly linked.
> Adds Live Demo and Google Colab links

- docs/en/alab/quickstart.md
> updated AWS link to Annotation Lab

- docs/en/licensed_install.md
> updated install doc for spark nlp for healthcare

- README.md
Adding missing instructions on README for GCP cluster
Improve documentation
> Adding instructions for GCP cluster

- src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala
Super simple change for adding newlines to the logs in databricks.
> added newline to logs in databricks

- docs/_posts/josejuanmartinez/2021-11-01-roberta_base_biomedical_es.md
Fixes typos and a bad usage of model loading (using disk load instead of calling to pretrained() to load from ModelsHub).
This change is requires since the example code didn't show how to consume the model from the Models Hub page.
This has been tested in a Google Colab notebook to check the consumption of the model using pretrained() is correct.
> Fix roberta model

- docs/_posts/murat-gunay/2021-11-03-bert_token_classifier_ner_bionlp_en.md
> update and fix tags

- docs/_posts/murat-gunay/2021-11-03-bert_token_classifier_ner_cellular_en.md
> update and fix scala section&tag section

- docs/en/third-party-projects.md
- python/docs/third_party/Comet.rst
- python/sparknlp/logging/comet.py
The documentation for Comet had some issues which where pointed out by @DN6. These are fixed in this PR.
Similarl issues where fixed in the workshop with PR https://github.com/JohnSnowLabs/spark-nlp-workshop/pull/419
Only contains changes to the documentation
> Docs: Fixed some issues with Comet documentation

- docs/_posts/josejuanmartinez/2021-11-01-roberta_base_biomedical_es.md
Changes download link and code examples, since this model be in the public repo
Changes download link and code, for switching from healthcare to public
Roberta Clinical Embeddings model should be in public/models, not in the healthcare suit. Model has been moved in S3, now updating the link.
> Changes Roberta es embeddings link from clinical to public

- docs/_posts/josejuanmartinez/2021-11-01-roberta_base_biomedical_es.md
Removes "licensed" tag, since it's not licensed
Removes the "licensed" tag from the tags metadata field
This model is not licensed, that's why that tag is not correct.
> Removes "licensed" tag from roberta biomedical

- docs/_posts/josejuanmartinez/2021-11-03-robertaresolve_snomed_es.md
After moving roberta embeddings to public, the code examples should change
Changes the reference of RobertaEmbeddings biomedical to public (in the code it was set the model was in "clinical/models")
We have moved the RobertaEmbeddings biomedical to public
> Updating roberta embeddings in snomed example

- docs/_posts/josejuanmartinez/2021-11-03-robertaresolve_snomed_es.md
The ER header was 'icd10_code' when it should be 'snomed_code'
Changes one header in the results section (`icd10_code` to `snomed_code`)
There was an incorrect header name.
> Changes bad column header name

- docs/_posts/josejuanmartinez/2021-11-05-bert_sequence_classifier_question_statement_clinical_en.md
Removes extra quotes in some code examples (modelshub already add the format quotes automatically)
Shallow change to remove additional quotes for code sections
Modelshub uploading page already adds the quotes for you, you don't need to quote code text.
> Removes extra quotes in some code examples

- docs/_posts/josejuanmartinez/2021-11-03-robertaresolve_snomed_es.md
Adds a simplified version of the pipeline reusing several components
Adds a simplified version of the pipeline reusing several components
The previous pipeline was more complex and had more components, being simpler than it was.
Running the pipeline in a notebook
> Simplifies pipeline in the Spanish snomed example

- docs/_posts/josejuanmartinez/2021-11-04-roberta_ner_diag_proc_es.md
Changes ner token-based results in Spanish Roberta NER model by chunk-based
Shallow change to show chunk ner entities, instead of by token.
It's better to show chunk-based results, grouping ner entities by chunks, instead of having the tokens separately.
> Changes ner token-based results by chunk-based

- docs/en/licensed_release_notes.md
These are the release notes for Spark NLP Healthcare 3.3.2 release.
> added release notes for healthcare 3.3.2

- docs/_data/navigation.yml
- docs/en/alab/project_setup.md
- docs/en/alab/start_page.md
- docs/en/alab/user_management.md
> general updates to alab instructions

- docs/en/licensed_install.md
> added the NLP libs install script

- docs/en/licensed_install.md
> updated installation instructions

- docs/_posts/josejuanmartinez/2021-11-04-bert_sequence_classifier_question_statement_en.md
Removes extra quotes from Bert For Sequence Classifier "Question vs Statement" (Opensource version)
Shallow change to remove extra quotes in code section
Uploading through ModelsHub already adds format quotes, so no need to manually insert them.
> Removes extra quotes from Question vs Statement (Opensource)

- docs/_posts/murat-gunay/2021-11-06-bert_sequence_classifier_antisemitism_en.md
Since I couldn't push all changes in one commit (it doesn't allow me to push locally), I am creating PRs one by one
> fixing scala script

- docs/_posts/HashamUlHaq/2021-09-01-ner_posology_experimental_en.md
Dia asks for fixing the typo because they are working on the Annotation lab. this issue blocks them.
> urgent fix of entity typo

- docs/_posts/josejuanmartinez/2021-11-04-bert_sequence_classifier_question_statement_en.md
- docs/_posts/josejuanmartinez/2021-11-05-bert_sequence_classifier_question_statement_clinical_en.md
Two colons were removed from titles of models in ModelsHub. 
They are reserved characters and can't be used.
> Fixing colon in titles

- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/embeddings/Doc2VecApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/Doc2VecModel.scala
This PR adds and polishes doc strings in the scaladocs and pydocs for the new Doc2Vec Annotator.
The pages for the main website will be added at a later date.
> Added Docs for Doc2Vec

- docs/en/licensed_install.md
> added aws emr docs

- docs/en/licensed_install.md
> fixed links

- docs/demos/analyze_non_english_medical_text.md
- docs/demos/european_languages.md
- docs/demos/infer_meaning_intent.md
- docs/demos/resolve_entities_codes.md
ICD-10 taxonomy for German medical terminology - hide
Detect Entities in tweets
> Add few changes

- docs/_posts/maziyarpanahi/2021-11-22-lemma_antbnc_en.md
- docs/_posts/maziyarpanahi/2021-11-22-sentiment_vivekn_en.md
- docs/_posts/maziyarpanahi/2021-11-22-spellcheck_norvig.md
This PR manually adds an entries for pretrained models, that were missing in the modelshub.
Resolves  #6486.
> Added missing pretrained models in models hub

- docs/en/licensed_annotator_entries/ChunkKeyPhraseExtraction.md
- docs/en/licensed_annotators.md
Update documentation of ChunkKeyPhraseExtraction.
> Update documentation of ChunkKeyPhraseExtraction

- docs/_posts/josejuanmartinez/2021-11-01-roberta_base_biomedical_es.md
There were incorrect `new` keywords when instantiating in scala.
Removes the `new` instantiation in scala.
No `new` instantiaton in scala is required. Also, there was a type.
In Google Colab notebooks
> Fixes `new` instantiation in scala section

- docs/_includes/demomenu.html
> removed broken link from menu

- docs/en/licensed_release_notes.md
> added healthcare 3.3.4 release notes

- docs/en/licensed_release_notes.md
There is a typo in the name of one model in 3.3.2 release notes. This commit aims to fix it.
Changes the name of a model in python example in release notesd of 3.3.2.
The model name is incorrect and needs to be changed.
Using a Google Colab notebooks to check download before and after the fix.
> Changes name model in release notes 3.3.2 example

- docs/_posts/HashamUlHaq/2021-02-15-classifierdl_use_snips_en.md
> fix python-scla code, added 'pretrained()'

- docs/_includes/demomenu.html
- docs/demos/analyze_financial_models.md
- docs/demos/analyze_medical_text_german.md
- docs/demos/analyze_medical_text_spanish.md
- docs/demos/medical_risk_scoring.md
- docs/demos/recognize_clinical_entities.md
Analyze non-medical clinical texts -> split into:
Analyze Medical Texts in Spanish
Detect Diagnoses And Procedures In Spanish
HPO coding – Spanish -> change name to “Resolve Clinical Health Information using the HPO taxonomy (Spanish”)
Detect Tumor Characteristics in Spanish medical texts
Analyze Medical Texts in German
Detect symptoms, treatments and other NERs in German
Analyze Financial Models
Detect legal entities in German
Detect traffic information in texts -> change name to “Detect traffic information in German”
Named Entity Recognition for (Brazilian) Portuguese Legal Texts
Detect professions and occupations in Spanish texts
Calculate Medicare Risk Score -> change to “Calculate Medicare HCC Risk Score”
Recognize Clinical Entities - Identify diagnosis and symptoms assertion status …
> Add some fixes in demos

- docs/en/licensed_release_notes.md
Description of New Ner Model modified.
Description of ner_deid_subentity_augmented_i2b2 model's training data has been changed.
> licensed release notes v3.3.4 updated

- python/run-tests.py
- python/sparknlp/annotator.py
- python/test/annotators.py
- src/main/scala/com/johnsnowlabs/nlp/annotator.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/Word2VecApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/embeddings/Word2VecModel.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/Word2VecTestSpec.scala
This PR introduces two new annotators: Word2VecApproach a distributed trainable Word2Vec and Word2VecModel that uses the trained words/vectors to output WORD_EMBEDDINGS.
> Introducing Distributed and Trainable Word2Vec annotators

- docs/_posts/murat-gunay/2021-09-09-bert_token_classifier_ner_btc_en.md
Added "Predicted Entities" to bert_token_classifier_ner_btc.
It fixes the issue [#763](https://github.com/JohnSnowLabs/streamlit-demo-apps/issues/763)
> Added predicted entities to bert_token_classifier_ner_btc

- docs/demos/european_languages.md
- docs/demos/recognize_entitie.md
Move Detect Entities in tweets into Recognize Entities
> Move Detect Entities in tweets into Recognize Entities

- docs/en/ocr_pipeline_components.md
- docs/en/ocr_release_notes.md
> Updated OCR docs for 3.9.1

- docs/_posts/josejuanmartinez/2021-11-03-robertaresolve_snomed_es.md
Fixes bad model name in python code
This fix just changes the model name in the Python section for the snomed resolver annotator.
There was a name change and the Python code didn't reflect that
In Google Colab notebooks
> Fixes bad model name in python code

- docs/_plugins/search_index.rb
Part of [NMH-51](https://johnsnowlabs.atlassian.net/browse/NMH-51)
- Only the latest models with same name and edition are indexed, thus removing duplicates during search
> FEATURE NMH-51: Tracked latest model and change id for indexed models [skip test]

- docs/_posts/HashamUlHaq/2021-02-10-bengaliner_cc_300d_bn.md
Fixes a typo in one entity name
There is a typo in the Organization entity
> Fixes typo in entities

- docs/_posts/dcecchini/2021-01-27-ner_jifs_glove_840B_300d_bn.md
Fixes typos in entity names
There are typos in the entity names
> Removes typos from entities

- docs/_plugins/search_index.rb
- docs/_sass/components/_model-item.scss
- docs/assets/js/models.js
[NMH-53](https://johnsnowlabs.atlassian.net/browse/NMH-53)
- Add Deprecated to models UI.
- Add `deprecated` to elastic search
> FEATURE NMH-53: Add deprecated label in models [skip test]

- docs/_posts/josejuanmartinez/2021-11-03-robertaresolve_snomed_es.md
There was a bad sequence of components in the documentation, detected when creating a demo. This fixes it.
Changes python and scala code, with the new sequence of components needed.
A bad sequence of components was set.
In Jupyter Notebook when creating a demo for it.
> Fixes the code examples in snomed (es)

- docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_de_xx.md
- docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_es_xx.md
- docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_fr_xx.md
- docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_many_xx.md
Adding Deprecated label to models which are no longer getting updated.
> Deprecating models(Open-Source)

- docs/_data/navigation.yml
- docs/en/CPUvsGPUbenchmark.md
- docs/en/CPUvsGPUbenchmark_healthcare.md
GPU vs CPU benchmark on ClassifierDL on GPU vs CPU benchmark
> GPU vs CPU benchmarks changes

- docs/_data/navigation.yml
- docs/_includes/demomenu.html
- docs/_sass/custom.scss
- docs/demos/radiology.md
- docs/demos/recognize_clinical_entities.md
- docs/en/CPUvsGPUbenchmark.md
- docs/en/CPUvsGPUbenchmark_healthcare.md
Add Radiology in demos
CPUvsGPUbenchmark fixes
> Add Radiology demos

- docs/demos/radiology.md
Change link on Detect Anatomical and Observation Entities in Chest Radiology Reports
> Detect Anatomical and Observation Entities in Chest Radiology Reports

- docs/_posts/Digaari/2020-08-31-bert_finnish_cased.md
- docs/_posts/Digaari/2020-08-31-bert_finnish_uncased.md
- docs/_posts/Digaari/2020-08-31-sent_bert_finnish_cased.md
- docs/_posts/Digaari/2020-08-31-sent_bert_finnish_uncased.md
> Deprecated models

- docs/demos/languages_india.md
Move NER Model for Hindi+Englishdemo  to top
> Move NER Model for Hindi+Englishdemo to top

- python/sparknlp/training.py
- src/main/scala/com/johnsnowlabs/nlp/training/CoNLL.scala
For some situations, the output of the ConLL reader was failing schema checks. This change sets the schema explicitly, and fixes the problem.
Also, documentation for the readDataset() method was enhanced.
> CoNLL Reader: Add Schema to Dataframe

- docs/_posts/luca-martial/2021-12-20-ner_drugprot_clinical_en.md
Hi @vkocaman I've added explanations for entity labels in the description of the model. Let me know if those are enough or if I should elaborate. Thanks!
> updated description with reasoning for entity labels

- docs/_includes/demomenu.html
- docs/demos/oncology.md
- docs/demos/recognize_clinical_entities.md
Move Detect biological concepts into Oncology
> move Detect biological concepts

- docs/_posts/HashamUlHaq/2021-04-29-sbiobertresolve_loinc_en.md
- docs/_posts/HashamUlHaq/2021-04-29-sbluebertresolve_loinc_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_loinc_en.md
sbiobertresolve_loinc and sbluebertresolve_loinc models has been tagged as deprecated.
> models tagged as deprecated

- docs/demos/radiology.md
- docs/demos/recognize_clinical_entities.md
add fixes into Radiology and Recognize clinical entities
> Add demos fixes

- docs/_posts/luca-martial/2022-01-05-re_drugprot_clinical_en.md
- docs/_posts/luca-martial/2022-01-05-redl_drugprot_biobert_en.md
> new re model description

- docs/en/ocr_pipeline_components.md
> Fix true to True for python sample

- docs/_posts/josejuanmartinez/2021-11-01-roberta_base_biomedical_es.md
Adds embeddings dimension info to description of the `roberta_base_biomedical_es` model
Adds some words to the description of the model, with information abou the embeddings dimension (768).
Sometimes if you need to train a NER model and create a TF graph, you need to know the embeddings dimension.
> Adds Embeddings dimension info to `roberta_base_biomedical_es`

- docs/_posts/murat-gunay/2021-12-03-xlm_roberta_large_token_classification_ner_id.md
Updates wrong name of the model, as reported by @C-K-Loan
Changes the name of the model. 
The used name in snippets does not exist
In notebooks, trying to execute old and new names.
> Updates wrong name of the model - by @C-K-Loan

- docs/learn.md
> Hide broken links in Learn section

- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/parser/SerializableClass.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/parser/SpecialTokensParser.scala
This fix is for solving an issue appearing during training of ContextSpellChecker.
Please hold the merge until we test this.
> Serialization context spell

- src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
- src/test/scala/com/johnsnowlabs/nlp/EmbeddingsFinisherTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/TokenAssemblerTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/LemmatizerTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/TextMatcherTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/btm/BigTextMatcherTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverterTest.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerPerfTest.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticDetectionPerfTest.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknPerformanceTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/spell/SpellCheckersPerfTest.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddingsTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoderTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsTestSpec.scala
This PR fixes some of the slowTest unit tests in Scala.
> Update slow unit tests

- docs/_frontend/src/models/App/App.js
- docs/_frontend/src/models/Sidebar/Sidebar.js
- Add UI options to sort models based on date and views
- [NMH-48](https://johnsnowlabs.atlassian.net/browse/NMH-58)
> FEATURE NMH-58: Add sort by views and date [skip-test]

- docs/_posts/HashamUlHaq/2021-04-01-ner_traffic_de.md
> updated for ner_traffic md file

- docs/_posts/egenc/2022-01-03-bert_token_classifier_ner_bionlp_en.md
- docs/_posts/egenc/2022-01-04-bert_token_classifier_ner_ade_en.md
- docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_anatomy_en.md
- docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_cellular_en.md
- docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_chemicals_en.md
- docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_chemprot_en.md
- docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_clinical_en.md
- docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_deid_en.md
- docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_drugs_en.md
- docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_jsl_en.md
- docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_jsl_slim_en.md
- docs/_posts/egenc/2022-01-07-bert_token_classifier_ner_bacteria_en.md
This Pull Requests aims to fix several typos in the Scala and Python code of Models Hub md files.
Fixes Python and Scala syntax.
The code was not running due to existence of typos.
In Google Colab
> Fix of several md files with typos

- docs/_posts/luca-martial/2022-01-05-re_drugprot_clinical_en.md
- docs/_posts/luca-martial/2022-01-05-redl_drugprot_biobert_en.md
Modified errors in example Scala code (md file)
The Scala code was not correct.
N/A
> models hub existing licensed models mardown Scala example code fixes

- docs/Gemfile
- docs/Gemfile.lock
- docs/_sass/custom.scss
- docs/demos/languages_india.md
- docs/demos/middle_eastern_languages.md
- docs/en/benchmark.md
fixing benchmark.md
move Indian Languages
update Gemfile 
gem 'wdm', '~> 0.1.0'
gem "webrick"
> Fixing benchmark and move Indian languages

- docs/_posts/luca-martial/2022-02-08-bert_sequence_classifier_ade_en.md
Adds a new RxNorm EntityResolver for 3.4.1 HC release, merging modelshub_internal to master.
This model should be released in 3.4.1 and will be announced, so we need to merge modelshub_internal it to master.
Notebooks
> RxNorm addition to 3.4.1 HC Release

- docs/_posts/maziyarpanahi/2020-02-03-onto_300_en.md
- docs/_posts/murat-gunay/2020-09-08-ner_dl_bert_en.md
This update aims to learn more about the models by adding the "Predicted Entities" section for some models.
Checking the md files in md viewer
> Update documentation about the models

- docs/_posts/luca-martial/2021-12-20-ner_drugprot_clinical_en.md
- docs/_posts/luca-martial/2022-02-07-bert_sequence_classifier_pico_biobert_en.md
- docs/_posts/luca-martial/2022-02-08-bert_sequence_classifier_ade_en.md
- docs/_posts/luca-martial/2022-02-08-bert_sequence_classifier_gender_biobert_en.md
- docs/_posts/luca-martial/2022-02-08-distilbert_sequence_classifier_ade_en.md
5 models had the wrong edition headers in their md file. I changed those to the correct versions (Spark NLP for Healthcare instead of Spark NLP). I also fixed the compatibility numbers in the md tables.
NA
> fixed model editions on md files

- docs/_posts/HashamUlHaq/2021-06-30-ner_deid_subentity_augmented_en.md
- docs/_posts/murat-gunay/2021-06-01-ner_deid_subentity_augmented_en.md
This update aims to learn more about models by editing the "Predicted Entities" section for some models.
Checking the md files in md viewer
> Fixes typos in English clinical_deidentification with STREET entity

- docs/en/licensed_install.md
> added additional details

- docs/demos/languages_india.md
- docs/learn.md
add Contextual Parser: Increased Flexibility Extracting Entities in Spark NLP
Copy Indian demos
> Copy demos

- docs/_posts/josejuanmartinez/2022-01-24-clinical_deidentification_es.md
Temporal fix to remove the bad name and path of this pipeline until the proper name ones are merged from models_hub_internal into master.
Removes the name and the download link, since this model had a bad one and the new one is not merged until 3.4.2 release.
This has been reuploaded but we have not merged models_hub_internal into master yet, so until that moments come, we will just correct this and them remove it when the new one is available
> Changes bad name/path until new version is merged

- docs/_data/navigation.yml
- docs/en/Serving_Spark_NLP_via_API_Databricks_and_MLFlow.md
- docs/en/Serving_Spark_NLP_via_API_FastAPI.md
- docs/en/Serving_Spark_NLP_via_API_SynapseML.md
Adds "Spark NLP via API" articles to nlp.johnsnowlabs.com
New articles have come up about serving Spark NLP via API, that have been shared in Medium and blog posts, and need to be available as documentation as well.
> "Serving Spark NLP via API" documentation

- docs/Gemfile
- docs/en/Serving_Spark_NLP_via_API_Databricks_and_MLFlow.md
- docs/en/Serving_Spark_NLP_via_API_FastAPI.md
- docs/en/Serving_Spark_NLP_via_API_SynapseML.md
This PR is aimed to fix all the format problems of API articles
After importing from Medium, a lot of format problems in the md were found.
> Fixes API articles format problems

- docs/_data/navigation.yml
- docs/en/licensed_serving_spark_nlp_via_api_databricks_mlflow.md
- docs/en/licensed_serving_spark_nlp_via_api_fastapi.md
- docs/en/licensed_serving_spark_nlp_via_api_synapseml.md
- docs/en/serving_spark_nlp_via_api_databricks_mlflow.md
Distributes API articles between Spark NLP and Spark NLP for Healthcare.
Distributes API articles between Spark NLP and Spark NLP for Healthcare.
There was information about Spark NLP for Healthcare in some of the articles, so they have been moved to Spark NLP for Healthcare.
Building locally the webpage
> Distributes API articles between Spark NLP and Spark NLP for Healthcare

- docs/en/ocr_release_notes.md
> fix in date

- docs/en/ocr_release_notes.md
> missing stuff

- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
This PR fixes the` bestModelMetric` param set by a user not being actually used.
> Make sure bestModelMetric is being used

- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_ca_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_cs_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_da_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_de_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_es_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_fr_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_hr_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_hu_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_id_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_it_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_lb_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_lt_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_mk_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_nl_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_ro_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_ru_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_sr_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_sv_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_tl_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_tr_3_0.md
- docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_ur_3_0.md
Updated `Scala` code inside Lemmatizer models.
> Updated lemmatizer models

- docs/_posts/luca-martial/2022-02-03-w2v_cc_300d_fr.md
Model title was incorrect (Fastext), fixed it to fastText
N/A
N/A
> fixed fastText model page title typo

- docs/_posts/HashamUlHaq/2021-03-31-ner_posology_en.md
- docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_medium_umls_uncased_en.md
- docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_medium_uncased_en.md
- docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_mini_umls_uncased_en.md
- docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_mini_uncased_en.md
- docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_tiny_umls_uncased_en.md
- docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_tiny_uncased_en.md
- docs/_posts/HashamUlHaq/2021-05-14-sbiobert_jsl_cased_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_augmented_billable_hcc_en.md
- docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_rxnorm_en.md
- docs/_posts/HashamUlHaq/2021-05-21-sbiobertresolve_icd10cm_slim_billable_hcc_en.md
- docs/_posts/HashamUlHaq/2021-06-30-ner_deid_subentity_augmented_en.md
- docs/_posts/muhammetsnts/2021-05-04-rxnorm_mesh_mapping_en.md
- docs/_posts/muhammetsnts/2021-05-04-rxnorm_umls_mapping_en.md
- docs/_posts/muhammetsnts/2021-05-04-snomed_umls_mapping_en.md
- docs/_posts/muhammetsnts/2021-05-25-sbertresolve_icd10cm_slim_billable_hcc_med_en.md
- docs/_posts/muhammetsnts/2021-05-25-sbiobertresolve_icd10cm_slim_billable_hcc_en.md
- docs/_posts/murat-gunay/2021-06-01-ner_deid_generic_augmented_en.md
- docs/_posts/murat-gunay/2021-09-03-ner_deid_subentity_augmented_en.md
@muhammetsnts let's keep this alive, once we are good we can merge it.
> Fix path to S3 for some models which were renamed

- docs/_posts/murat-gunay/2020-09-01-posology_re.md
Created md file for posology_re model
> Created md file for posology_re model

- docs/demos/analyze_spelling_grammar.md
- docs/demos/extract_relationships.md
- docs/demos/recognize_entitie.md
Correct Sentences Grammar
Switch Between Active and Passive voice
Switch Between Informal and Formal style
> Fixing and add new demos

- docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_anatomy_en.md
> fix model name in python script

- docs/en/annotator_entries/SentenceDetector.md
- docs/en/annotators.md
- docs/en/training_entries/conll.md
- python/sparknlp/annotator.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.scala
This PR updates documentation for the SentenceDetector to make it more transparent for the user. 
@maziyarpanahi You mentioned in the issue, that the user should be able to replicate the rules themselves. Is this [high-level description](https://github.com/JohnSnowLabs/spark-nlp/pull/7486/commits/3e89172134ab613a74c651acd45477096cc2e307#diff-79e3b9f663e2b5195f0f2c20f9867b6e2839bcfb244a06463f7736ba93707e93R6-R23) enough or should it be more explicit?
No code changes.
> Docs: Update SentenceDetector

- docs/en/licensed_release_notes.md
> updated md file

- docs/_posts/Ahmetemintek/2022-04-01-normalized_section_header_mapper_en_3_0.md
```The models that we upload to Modelshub should be upload using the version 3.4.2 because we resolve that models based on the open source version. ```
Uploads default Zero-shot RE for 3.4.2 (it was uploaded with 3.5.0)
```The models that we upload to Modelshub should be upload using the version 3.4.2 because we resolve that models based on the open source version. ```
> Models hub internal

- docs/_posts/Ahmetemintek/2022-03-31-drug_action_treatment_mapper_en_3_0.md
- docs/_posts/Ahmetemintek/2022-04-01-normalized_section_header_mapper_en_3_0.md
- docs/_posts/Ahmetemintek/2022-04-04-drug_action_treatment_mapper_en_3_0.md
- docs/_posts/Ahmetemintek/2022-04-04-normalized_section_header_mapper_en_3_0.md
Adds default pretrained zero_shot model for 3.4.2  and other two models
Adds default pretrained zero_shot model for 3.4.2 and other two models
By using "zero_shot_re" instead of "re_zeroshot_biobert", it was looking for 3.4.2 version o the model that is non-existing now. Also adds two models recently added.
> Models hub internal - zero_shot_re 3.4.2 and two more models

- docs/en/nlp_server/release_notes.md
Content for the release notes of NLP Server v060
1. Added Overview section
2. Added Release Details
3. Added Installation Prerequisites
4. Added Key Information
5. Added Major Features and Improvements
6. Added Other Improvements
7. Added Bug Fixes
8. Added Known Issues
https://user-images.githubusercontent.com/10699092/161738892-298b5fdd-47d7-47f3-85ee-4e15287a7306.mov
> Added first draft of release notes for NLP Server v060

- docs/en/alab/active_learning.md
- docs/en/alab/byol.md
- docs/en/alab/infrastructure.md
- docs/en/alab/preannotations.md
- docs/en/alab/release_notes.md
- docs/en/alab/visual_ner.md
> Annotation Lab 3.0.0 release notes

- docs/_posts/Ahmetemintek/2022-04-04-normalized_section_header_mapper_en_3_0.md
Adds 3.5.0 version cards for re_zeroshot_biober instead of 3.4.2
Adds 3.5.0 version cards for re_zeroshot_biober instead of 3.4.2
Adds 3.5.0 version cards for re_zeroshot_biober instead of 3.4.2
- [X ] My change requires a change to the documentation.
> Adds 3.5.0 version for re_zeroshot_biobert

- docs/_posts/murat-gunay/2022-04-08-bert_biolink_large_en_3_0.md
Fixes errors in description
Fixes errors in description
The description has typos
> Fixes errors in description (bert-biolink)

- docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_clinical_en.md
> Update output section of the model

- docs/_posts/josejuanmartinez/2022-04-05-re_zeroshot_biobert_en_3_0.md
Improves coding of the zeroshot md
Adds scala version and removes some ugly text
There was no scala version and there were some ugly portions of code
> Improves coding of the zeroshot md

- docs/en/ocr.md
- docs/en/ocr_install.md
- docs/en/ocr_object_detection.md
- docs/en/ocr_pipeline_components.md
- docs/en/ocr_release_notes.md
- docs/en/ocr_structures.md
- docs/en/ocr_table_recognition.md
- docs/en/ocr_visual_document_understanding.md
Add Tabacco-3482 dataset categories
> Corrections

- docs/en/ocr_release_notes.md
> added rn 3120

- python/run-tests.py
- python/sparknlp/annotator.py
- python/sparknlp/internal.py
- python/test/annotators.py
- src/main/scala/com/johnsnowlabs/nlp/annotator.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DeBertaForTokenClassification.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DeBertaForTokenClassificationTestSpec.scala
This PR introduces DeBertaForTokenClassification that can load DeBERTA Models v2 and v3 with a token classification head on top (a linear layer on top of the hidden-states output) e.g. for Named-Entity-Recognition (NER) tasks.
> Introducing DeBertaForTokenClassification annotator

- docs/en/licensed_release_notes.md
> 3.5.1 Released

- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
The get download size in not same as the resource downloader
> Get the download size the same as the model downloaded

- docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_multi_lg_xx.md
- docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_multi_xx.md
- docs/_posts/maziyarpanahi/2021-05-06-tfhub_use_multi_lg_xx.md
- docs/_posts/maziyarpanahi/2021-05-06-tfhub_use_multi_xx.md
> Added deprecated tag

- build.sbt
- project/Dependencies.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/DependencyInstance.java
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/DependencyPipe.java
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/PredictionParameters.java
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyParserApproach.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyParserModel.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/feature/SyntacticFeatureFactory.java
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/util/Alphabet.java
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/util/Dictionary.java
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/util/DictionarySet.java
- src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/util/FeatureVector.java
- src/test/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/PredictionParametersTest.java
- src/test/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyModelTestSpec.scala
Removes `trove4j` dependency and replaces with native Java data structures
The last time it was updated was in 2012 and for security reasons, we replaced this with native Java data structures
Unit tests
> Removing trove4j dependency

- docs/_posts/2020-07-08-ner_deid_enriched_en.md
- docs/_posts/2020-07-22-ner_deid_large_en.md
- docs/_posts/HashamUlHaq/2021-02-19-ner_deid_synthetic_en.md
- docs/_posts/HashamUlHaq/2021-03-02-ner_deid_enriched_en.md
- docs/_posts/HashamUlHaq/2021-03-15-ner_deid_large_en.md
- docs/_posts/HashamUlHaq/2021-03-31-ner_deid_augmented_en.md
- docs/_posts/HashamUlHaq/2021-03-31-ner_deid_enriched_en.md
- docs/_posts/HashamUlHaq/2021-03-31-ner_deid_large_en.md
- docs/_posts/HashamUlHaq/2021-03-31-ner_deid_synthetic_en.md
- docs/_posts/HashamUlHaq/2021-04-01-ner_deid_biobert_en.md
- docs/_posts/HashamUlHaq/2021-04-01-ner_deid_enriched_biobert_en.md
- docs/_posts/HashamUlHaq/2021-04-01-ner_deid_sd_en.md
- docs/_posts/HashamUlHaq/2021-04-01-ner_deid_sd_large_en.md
- docs/_posts/HashamUlHaq/2021-06-30-ner_deid_generic_augmented_en.md
- docs/_posts/HashamUlHaq/2021-06-30-ner_deid_subentity_augmented_en.md
- docs/_posts/aydinmyilmaz/2021-01-20-ner_deid_augmented_en.md
- docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_deid_en.md
- docs/_posts/murat-gunay/2021-06-01-ner_deid_generic_augmented_en.md
- docs/_posts/murat-gunay/2021-06-01-ner_deid_subentity_augmented_en.md
- docs/_posts/murat-gunay/2021-06-06-ner_deid_generic_glove_en.md
- docs/_posts/murat-gunay/2021-06-06-ner_deid_subentity_glove_en.md
- docs/_posts/murat-gunay/2021-09-03-ner_deid_subentity_augmented_en.md
- docs/_posts/murat-gunay/2021-09-13-bert_token_classifier_ner_deid_en.md
- docs/_posts/murat-gunay/2021-11-29-ner_deid_subentity_augmented_i2b2_en.md
The following comment was added to the description section of ner_deid_en models:
`We sticked to official annotation guideline (AG) for 2014 i2b2 Deid challenge while annotating new datasets for this model. All the details regarding the nuances and explanations for AG can be found here [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4978170/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4978170/)`
> Updated ner_deid_en models description

- docs/en/nlp_server/release_notes.md
Content for the release notes of NLP Server v061
1. Added Overview section
2. Added Key Information
3. Added Other Improvements
4. Added Bug Fixes
https://user-images.githubusercontent.com/10699092/167118036-e0d56490-4605-40e1-932f-c5ca88b902d4.mov
_P.S. The URLs for AWS and Azure images are yet to be updated which will be done after the images are published in respective marketplaces._
> Release notes content for NLP Server version 0.6.1

- docs/_includes/article-info-author.html
- docs/_sass/components/_article-info.scss
This commit will add Edit on Github button to the models' page (NMH-81)
> FEATURE NMH-81: Add the "Edit on GitHub" button [skip-test]

- .github/workflows/create_search_index.yml
- docs/_plugins/search_index.rb
Jira Ticket [NMH-78](https://johnsnowlabs.atlassian.net/browse/NMH-78)
Export models benchmarking information in a separate file
> FEATURE NMH-78: Export benchmarking information to json file [skip-test]

- docs/_frontend/src/models/FilterForm/FilterForm.js
Jira Ticket [NMH-91](https://johnsnowlabs.atlassian.net/browse/NMH-91)
> FEATURE NMH-91: Show All * versions if only exists [skip-test]

- .github/workflows/build_and_test.yml
- build.sbt
- project/Dependencies.scala
- remove spark30 and spark32 flags
- make sure the M1 package is included
- update Github actions for all 3 major spark releases
-
> Feature/unify Spark NLP released packages

- docs/_data/navigation.yml
- docs/en/CPU_NER_Benchmarks.md
> Add CPU_NER_Benchmarks.md

- docs/demos/analyze_medical_text_german.md
- docs/demos/deidentification.md
- docs/demos/entity_recognition.md
- docs/demos/european_languages.md
- docs/demos/extract_relationships.md
- docs/demos/languages_africa.md
- docs/demos/middle_eastern_languages.md
- docs/demos/oncology.md
- docs/demos/radiology.md
- docs/demos/recognize_biomedical_entities.md
- docs/demos/recognize_clinical_entities.md
- docs/demos/resolve_entities_codes.md
- docs/demos/social_determinants.md
Spark NLP: Demos to be Updated-MAY.18.2022
> Fixing some demos

- docs/en/alab/release_notes.md
> updaded 3.2.0 release notes

- docs/en/licensed_install.md
copied from https://nlp.johnsnowlabs.com/docs/en/install#windows-support
and added same
> added windows support

- docs/_plugins/search_index.rb
Hi @pabla ,
This PR fixes bug [NMH-96](https://johnsnowlabs.atlassian.net/browse/NMH-96)
> BUGFIX NMH-96: Delete changed models before indexing [skip-test]

- docs/_frontend/package.json
- docs/_frontend/src/models/App/App.js
- docs/_frontend/src/models/ModelItem/ModelItem.css
- docs/_frontend/src/models/ModelItem/ModelItem.js
- docs/_frontend/src/models/ModelItem/utils.js
- docs/_frontend/src/models/Tooltip/Tooltip.js
- docs/_frontend/src/models/Tooltip/Tooltip.module.css
- docs/_frontend/src/models/Tooltip/index.js
- docs/_frontend/yarn.lock
Add a toggle button for model naming conventions.
> FEATURE NMH-94: Add model naming conventions [skip test]

- docs/en/nlp_server/release_notes.md
Content for the release notes of NLP Server v070
1. Added Release Details
2. Added Overview section
3. Added Key Information
4. Added Major Features and Improvements
5. Added Other Improvements
https://user-images.githubusercontent.com/10699092/172338375-6c6a4d03-af77-46be-9b53-dc8351a832fc.mov
> Release notes content for v0.7.0

- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowClassifier.scala
- src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSentiment.scala
Sometimes, the accuracy can go above 1.0 by a small fraction due to division. This PR makes sure the accuracy stays between 0.0 and 1.0
> Make sure classifiers have accuracies between 0.0 and 1.0

- docs/_posts/murat-gunay/2022-06-08-distilbert_qa_AQG_CV_Squad_en_3_0.md
@josejuanmartinez 
Please take a look at this initial QA-DistilBert model for an example. I will upload 165 DistilBertQA models after your "OK".
> 2022-06-08-distilbert_qa_AQG_CV_Squad_en_3_0

- docs/en/ocr_release_notes.md
Spark OCR 3.13.0 release notes.
> added ocr 3130 release notes

- docs/_posts/HashamUlHaq/2021-03-31-ner_legal_de.md
- docs/_posts/luca-martial/2022-04-11-bert_embeddings_legal_bert_base_uncased_en_3_0.md
- docs/_posts/luca-martial/2022-04-11-bert_embeddings_legal_bert_small_uncased_en_3_0.md
- docs/_posts/luca-martial/2022-04-12-bert_embeddings_sec_bert_base_en_3_0.md
- docs/_posts/luca-martial/2022-04-12-bert_embeddings_sec_bert_num_en_3_0.md
- docs/_posts/luca-martial/2022-04-12-bert_embeddings_sec_bert_sh_en_3_0.md
- docs/_posts/luca-martial/2022-04-14-roberta_embeddings_bertin_roberta_base_spanish_es_3_0.md
- docs/_posts/vankov/2021-12-03-gpt2_en.md
- docs/_posts/vankov/2021-12-03-gpt2_medium_en.md
- docs/_posts/vankov/2021-12-03-gpt_large_en.md
This PR is aimed to improve bad titles and descriptions due to the lack of differentiating details in them.
Changs titles and descriptions in .md for some models.
We are going to "star" some models, and these ones are good candidates, but with bad titles or descriptions.
> Improves bad titles and descriptions for models in MH

- docs/_posts/Digaari/2021-09-06-sent_bert_base_uncased_legal_en.md
- docs/_posts/Digaari/2021-09-07-bert_base_uncased_legal_en.md
- docs/_posts/HashamUlHaq/2021-03-31-ner_legal_de.md
- docs/_posts/HashamUlHaq/2021-07-15-explain_clinical_doc_ade_en.md
- docs/_posts/HashamUlHaq/2021-10-22-ner_jsl_enriched_en.md
- docs/_posts/Meryem1425/2022-03-21-bert_token_classifier_ner_jsl_en_2_4.md
- docs/_posts/dcecchini/2021-05-27-ner_lener_pt.md
- docs/_posts/egenc/2022-01-17-sbertresolve_ner_model_finder_en.md
- docs/_posts/gadde5300/2022-04-25-rct_binary_classifier_biobert_pipeline_en_3_0.md
- docs/_posts/josejuanmartinez/2022-03-03-clinical_deidentification_augmented_es_2_4.md
- docs/_posts/josejuanmartinez/2022-03-22-clinical_deidentification_glove_augmented_en_3_0.md
- docs/_posts/josejuanmartinez/2022-04-14-clinical_deidentification_pt_3_0.md
- docs/_posts/luca-martial/2022-03-04-clinical_deidentification_fr_2_4.md
- docs/_posts/luca-martial/2022-03-28-clinical_deidentification_it_2_4.md
- docs/_posts/luca-martial/2022-04-12-bert_embeddings_sec_bert_base_en_3_0.md
- docs/_posts/luca-martial/2022-04-14-roberta_embeddings_bertin_roberta_base_spanish_es_3_0.md
- docs/_posts/maziyarpanahi/2020-08-25-biobert_clinical_base_cased.md
- docs/_posts/maziyarpanahi/2020-09-19-sent-biobert_clinical_base_cased.md
- docs/_posts/maziyarpanahi/2021-01-08-t5_base_en.md
- docs/_posts/maziyarpanahi/2021-09-26-roberta_base_token_classifier_ontonotes_en.md
- docs/_posts/maziyarpanahi/2021-09-28-xlm_roberta_token_classifier_ner_40_lang_xx.md
- docs/_posts/maziyarpanahi/2022-05-06-deberta_v3_base_token_classifier_ontonotes_en_3_0.md
- docs/_posts/murat-gunay/2021-12-06-xlm_roberta_large_token_classifier_masakhaner_xx.md
- docs/_posts/murat-gunay/2021-12-09-bert_token_classifier_scandi_ner_xx.md
- docs/_posts/murat-gunay/2021-12-26-xlm_roberta_large_token_classifier_hrl_xx.md
- docs/_posts/vankov/2021-12-03-gpt2_en.md
Mark some models as recommended according to Juan's list.
> FEATURE NMH-102: Mark some models as recommended [skip test]

- docs/_posts/egenc/2022-01-17-sbertresolve_ner_model_finder_en.md
- docs/_posts/josejuanmartinez/2022-03-22-clinical_deidentification_glove_augmented_en_3_0.md
- docs/_posts/maziyarpanahi/2021-09-26-roberta_base_token_classifier_ontonotes_en.md
- docs/_posts/maziyarpanahi/2021-09-28-xlm_roberta_token_classifier_ner_40_lang_xx.md
- docs/_posts/maziyarpanahi/2022-05-06-deberta_v3_base_token_classifier_ontonotes_en_3_0.md
Improves titles of starred models
Changes md to improve titles of starred models
Some models have been uploaded with long and ugly names. Since we are curating and starring some of them, this fix is to make titles prettier.
> Improving titles of curated / recommended model cards

- docs/_posts/Meryem1425/2022-06-06-sbiobertresolve_icdo_augmented_en_3_0.md
- docs/_posts/josejuanmartinez/2022-06-21-clinical_deidentification_pt_3_0.md
PT pipeline has been updated. This PR is to reflect the new PT pipeline card in master.
PT pipeline has been updated. This PR is to reflect the new PT pipeline card in master.
A new PT pipeline has been released, and we need to show the new card.
> Models hub internal to master

- docs/_posts/josejuanmartinez/2022-04-14-clinical_deidentification_pt_3_0.md
Unrecommend PT pipeline model with the broken Contextual Parser (will recommend the fixed version with the TextMatcher)
Unrecommend PT pipeline model with the broken Contextual Parser (will recommend the fixed version with the TextMatcher)
A new version of PT pipeline was required since some functionality of CP broke. Now we use a TextMatcher.
In notebook.
> Unrecommend old PT pipeline

- docs/en/licensed_install.md
> Spark NLP for Healthcare Installation Install with Poetry

- docs/en/alab/annotation_labs_releases/release_notes_3_3_0.md
- docs/en/alab/annotation_labs_releases/release_notes_3_3_1.md
- docs/en/alab/release_notes.md
> added release notes for 3.3.1

- python/sparknlp/annotator/normalizer.py
- python/sparknlp/annotator/spell_check/context_spell_checker.py
- python/sparknlp/annotator/token/regex_tokenizer.py
- python/sparknlp/annotator/token/tokenizer.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
This PR fixes some misspellings in the PyDoc
> Fix misspelling in the pydoc

- src/test/scala/com/johnsnowlabs/nlp/annotators/GraphExtractionTest.scala
Update slow (local) test for GraphExctaction
Maintain consistency in the sense that slow tests should passed
> Fix issue in Slow Test

- docs/_posts/luca-martial/2022-04-11-bert_embeddings_finbert_pretrain_yiyanghkust_en_3_0.md
Improves card information for Financial Embeddings model
Changes title, description, dataset and references.
The model had little information about the specific aim of this model, that is financial documents.
> Improves card information for Financial Embeddings model

- .github/workflows/build_and_test.yml
- python/sparknlp/internal/extended_java_wrapper.py
- python/sparknlp/training/conll.py
- python/sparknlp/training/conllu.py
- python/sparknlp/training/pos.py
- python/sparknlp/training/pub_tator.py
Adding a conditional creation of a DataFrame based on pyspark version
Some stuff is not compatible with Spark/PySpark 3.3. Like CoNLL(), POS(), or anything that uses spark._warpped
Error:
AttributeError: 'SparkSession' object has no attribute '_wrapped'
Python Unit Tests
> Refactoring to allow support for Pyspark3.3

- docs/_posts/luca-martial/2022-02-14-ner_deid_subentity_fr.md
Python code example was leading to error, fixed it
> Fixed issues in python usage example in model card

- docs/_posts/gadde5300/2022-06-03-bert_qa_bert_multi_cased_finedtuned_xquad_tydiqa_goldp_xx_3_0.md
- docs/_posts/gadde5300/2022-06-21-roberta_qa_ft_lr_cu_leolin12345_xx_3_0.md
- docs/_posts/gadde5300/2022-06-23-xlm_roberta_qa_distill_xlm_mrc_xx_3_0.md
- docs/_posts/gadde5300/2022-06-23-xlm_roberta_qa_xlm_roberta_base_vietnamese_vn_3_0.md
- docs/_posts/gadde5300/2022-06-23-xlm_roberta_qa_xlm_roberta_qa_chaii_xx_3_0.md
- docs/_posts/luca-martial/2022-03-14-w2v_cc_300d_eml_3_0.md
Some of the model hub cards had incorrect titles
Updated the titles of the models with respect to their respective languages.
> Updated unidentified languages

- docs/_plugins/search_index.rb
Jira Ticket [NMH-106](https://johnsnowlabs.atlassian.net/browse/NMH-106)
> BUGFIX NMH-106: Fix views/downloads reset after reindex [skip-test]

- docs/_posts/C-K-Loan/2021-03-09-pos_ud_padt_ar.md
Adding missing tokenizer stage in Scala and Python documentation
> Adding missing tokenizer stage

- docs/_plugins/search_index.rb
Jira Ticket [NMH-103](https://johnsnowlabs.atlassian.net/browse/NMH-103)
> FEATURE NMH-103: Improvement benchmarking parser [skip-test]

- docs/_plugins/search_index.rb
Jira Ticket [NMH-105](https://johnsnowlabs.atlassian.net/browse/NMH-105)
> FEATURE NMH-105: Extract and add references.json file [skip-test]

- docs/en/ocr_object_detection.md
> improved docs

- docs/_posts/HashamUlHaq/2021-03-16-sentence_detector_dl_healthcare_en.md
- docs/_posts/HashamUlHaq/2021-08-11-sentence_detector_dl_healthcare_en.md
- docs/_posts/vankov/2021-01-02-sentence_detector_dl_en.md
- docs/_posts/vankov/2021-01-02-sentence_detector_dl_xx.md
> fix button problem

- docs/en/licensed_release_notes.md
> updated licensed release notes

- docs/en/alab/annotation_labs_releases/release_notes_3_2_0.md
- docs/en/alab/annotation_labs_releases/release_notes_3_3_1.md
- docs/en/alab/annotation_labs_releases/release_notes_3_4_0.md
- docs/en/alab/release_notes.md
> Added release note for ALAB v3.4.0

- docs/demos/deidentification.md
> deidentification.md file for demos

- docs/_posts/josejuanmartinez/2022-08-03-legner_cuad_silver_en_3_2.md
- docs/demos/deidentification.md
> Models hub legal

- docs/_posts/josejuanmartinez/2022-08-03-finner_sec_conll_en_3_2.md
- docs/_posts/luca-martial/2022-08-03-finance_sequence_classifier_esg_en_3_2.md
> Models hub finance

- docs/_posts/galiph/2022-08-01-medication_resolver_transform_pipeline_en_3_0.md
> 2022 08 01 medication resolver transform pipeline en 3 0 jzk bdu eb0k4 ix ac e nd9 whm uv

- docs/demos/financial_entity_recognition.md
- docs/demos/recognize_clinical_entities.md
- docs/demos/recognize_entitie.md
Detect traffic information in German
Detect professions and occupations in Spanish
> Move demos

- docs/learn.md
- docs/learnhub.md
> Update learn menu

- docs/en/alab/annotation_labs_releases/release_notes_3_4_1.md
- docs/en/alab/release_notes.md
> added text changes of 3.4.1 with release notes

- docs/_includes/demomenu.html
- docs/demos/financial_text_classification.md
- docs/demos/legal_entity_recognition.md
- docs/demos/public_health.md
> Fixed some demos, add ESG News Classification demo

- docs/en/alab/install.md
> added instructions for azure deployments

- docs/_includes/demomenu.html
- docs/demos/databricks_solution_accelerators.md
- docs/demos/financial_company_normalization.md
Automated PHI Removal
Oncology Real-World Data Extraction With NLP
Adverse Drug Event Detection
Toxicity Detection for Gaming
> Databricks Solution Accelerators

- docs/en/alab/annotation_labs_releases/release_notes_3_4_1.md
- docs/en/alab/annotation_labs_releases/release_notes_3_5_0.md
- docs/en/alab/release_notes.md
> 350 ALAB release doc

- docs/_includes/demomenu.html
- docs/_includes/head.html
- docs/_sass/custom.scss
> Update demos order

- docs/demos/demolist.md
- docs/docs.md
- docs/learnhub.md
- docs/models.md
> Фdd seo titles

- docs/_data/navigation.yml
- docs/en/serving_spark_nlp_via_api_databricks_mlflow.md
> hide Serving Spark NLP& MLFlow on Databricks

- docs/_posts/HashamUlHaq/2021-04-01-ner_financial_contract_en.md
- docs/_posts/josejuanmartinez/2022-04-05-re_zeroshot_biobert_en_3_0.md
- docs/_posts/maziyarpanahi/2021-07-19-ner_wikiner_glove_840B_300_xx.md
- docs/_posts/maziyarpanahi/2021-07-19-ner_wikiner_xlm_roberta_base_xx.md
- docs/_posts/maziyarpanahi/2021-07-19-ner_xtreme_glove_840B_300_xx.md
- docs/_posts/maziyarpanahi/2021-07-19-ner_xtreme_xlm_roberta_xtreme_base_xx.md
* Updated md files:  2021-07-19-ner_wikiner_glove_840B_300_xx.md, 2021-07-19-ner_wikiner_xlm_roberta_base_xx.md, 2021-07-19-ner_xtreme_glove_840B_300_xx.md, 2021-07-19-ner_xtreme_xlm_roberta_xtreme_base_xx.md
* Updated python and scala codes
* Added results part
> Updated md files

- docs/en/licensed_release_notes.md
- docs/en/spark_nlp_healthcare_versions/release_notes_4_1_0.md
Licensed release notes files are updated with new changes.
> licensed release notes updated

- src/main/scala/com/johnsnowlabs/nlp/annotators/audio/util/transform/AudioProcessors.scala
The wav files need to be resampled to be processed correctly by wav2vec2
The code extends  `processAsWav` in Audio Processor
> Downsampling wav2vec2

- docs/demos/financial_entity_recognition.md
- docs/demos/financial_relation_extraction.md
- docs/demos/financial_text_classification.md
- docs/demos/legal_entity_recognition.md
- docs/demos/legal_relation_extraction.md
> Update demo`s order

- docs/_posts/Ahmetemintek/2022-08-23-drug_ade_mapper_en.md
- docs/_posts/Cabir40/2022-08-12-ner_clinical_bert_ro_3_0.md
- docs/_posts/Cabir40/2022-08-15-ner_deid_generic_bert_ro_3_0.md
- docs/_posts/Damla-Gurbaz/2022-09-01-medication_resolver_pipeline_en.md
- docs/_posts/HashamUlHaq/2021-02-19-t5_base_mediqa_mnli_en.md
- docs/_posts/Meryem1425/2022-07-28-bert_sequence_classifier_treatement_changes_sentiment_tweet_en_3_0.md
- docs/_posts/alierenak/2022-08-01-bert_sequence_classifier_covid_sentiment_en_3_0.md
- docs/_posts/alierenak/2022-08-10-bert_sequence_classifier_health_mentions_gbert_large_de_3_0.md
- docs/_posts/gokhanturer/2022-07-29-bert_sequence_classifier_self_reported_vaccine_status_tweet_en_3_0.md
- docs/_posts/gpirge/2022-08-13-ner_negation_uncertainty_es_3_0.md
- docs/_posts/gpirge/2022-08-14-disease_mentions_tweet_es_3_0.md
- docs/_posts/hsaglamlar/2022-07-29-bert_sequence_classifier_self_reported_stress_tweet_en_3_0.md
- docs/_posts/josejuanmartinez/2022-07-05-t5_question_generation_small_en_3_0.md
- docs/_posts/josejuanmartinez/2022-08-17-finner_orgs_prods_alias_en_3_2.md
- docs/_posts/josejuanmartinez/2022-08-30-finner_bert_roles_en.md
- docs/_posts/josejuanmartinez/2022-08-30-legmulticlf_edgar_en.md
- docs/_posts/josejuanmartinez/2022-08-31-finpipe_deid_en.md
- docs/_posts/josejuanmartinez/2022-08-31-legpipe_deid_en.md
- docs/_posts/josejuanmartinez/2022-09-02-finner_roberta_zeroshot_en.md
- docs/_posts/josejuanmartinez/2022-09-02-legner_roberta_zeroshot_en.md
- docs/_posts/josejuanmartinez/2022-09-06-finclf_augmented_esg_en.md
- docs/_posts/josejuanmartinez/2022-09-06-finner_financial_small_en.md
- docs/_posts/josejuanmartinez/2022-09-07-finvisualclf_vit_tickets_en.md
- docs/_posts/muhammetsnts/2022-07-28-bert_sequence_classifier_vaccine_sentiment_en_3_0.md
- docs/_posts/muhammetsnts/2022-08-29-zero_shot_ner_roberta_en.md
- docs/_posts/muhammetsnts/2022-08-30-ner_profiling_clinical_en.md
- docs/_posts/murat-gunay/2022-05-17-electra_embeddings_electricidad_base_generator_es_3_0.md
> Starring models

- docs/_includes/demomenu.html
> remove Financial Sentiment Analysis

- docs/_includes/demomenu.html
- docs/en/nlp_server/installation.md
> Add notebook section

- docs/_posts/josejuanmartinez/2022-09-19-legner_bert_indemnifications_en.md
- docs/_posts/josejuanmartinez/2022-09-19-legre_indemnifications_en.md
* Add model 2022-09-19-legre_indemnifications_en
* Add model 2022-09-19-legner_bert_indemnifications_en
Co-authored-by: josejuanmartinez <jjmcarrascosa@gmail.com>
> 2022-09-19-legre_indemnifications_en (#12758)

- docs/en/install.md
- docs/en/licensed_install.md
> updated typos

- docs/_data/navigation.yml
- docs/_includes/demomenu.html
- docs/_includes/programmingLanguageSelectScalaPython.html
- docs/_includes/programmingLanguageSelectScalaPythonMFL.html
- docs/_includes/scripts/programmingLanguageSwitcherScalaPython.js
- docs/_includes/templates/licensed_approach_model_medical_fin_leg_template.md
- docs/demos/analyze_medical_text_spanish.md
- docs/demos/analyze_non_english_medical_text.md
- docs/demos/analyze_non_english_text_documents.md
- docs/demos/analyze_spelling_grammar.md
- docs/demos/classify_documents.md
- docs/demos/classify_financial_documents.md
- docs/en/wiki.md
> Add wiki page in Spark NLP for Healthcare

- docs/_posts/josejuanmartinez/2022-09-27-finassertion_time_en.md
Co-authored-by: josejuanmartinez <jjmcarrascosa@gmail.com>
> Add model 2022-09-27-finassertion_time_en (#12833)

- docs/en/wiki.md
> Update wiki page title

- docs/_includes/scripts/programmingLanguageSwitcherScalaPython.js
- docs/_includes/templates/licensed_approach_model_medical_fin_leg_template.md
> Update docs tabs

- docs/en/licensed_install.md
> Update licensed_install.md Install on AWS SageMaker

- docs/_layouts/nlp_products.html
- docs/_sass/custom.scss
> ad finance and legal nlp lines

- docs/en/licensed_release_notes.md
- docs/en/spark_nlp_healthcare_versions/release_notes_4_2_0.md
oncology model notebook link added to release notes
> oncology model notebook link added to release notes

- docs/licensed/api/com/johnsnowlabs/nlp/annotators/deid/DocumentHashCoder.html
Check PR 4.2.0-healthcare-docs-a8196180c133b9b1d0a71f2965ce8d3addd466e3-15
> [skip ci] Create PR 4.2.0-healthcare-docs-a8196180c133b9b1d0a71f2965ce8d3addd466e3-15

- docs/_includes/scripts/lib/toc.js
- docs/_sass/custom.scss
- docs/en/alab/tutorials.md
> Add how to create a ner project in annotation lab video

- docs/en/alab/project_setup.md
> added details on relation constraints

- docs/_frontend/src/models/FilterForm/FilterForm.js
- docs/_frontend/src/models/ModelItem/ModelItem.js
- docs/_frontend/src/models/ModelItem/utils.js
Jira Ticket [NMH-128](https://johnsnowlabs.atlassian.net/browse/NMH-128)
@pabla
> FEATURE NMH-128: Used new product display name [skip-test]

- docs/_includes/scripts/programmingLanguageSwitcherScalaPython.js
> Update tabs js in docs

- docs/_includes/scripts/programmingLanguageSwitcherScalaPython.js
- docs/en/auxiliary.md
> Update tabs script

- docs/_includes/programmingLanguageSelectPythons.html
- docs/_includes/scripts/programmingLanguageSwitcherScalaPython.js
- docs/_sass/custom.scss
- docs/en/tab_example.md
> Add 4th tabs in documets

- docs/_includes/demomenu.html
- docs/_includes/programmingLanguageSelectPythons.html
Change Clinical NLP with Biomedical
> Update tab`s buttons

- docs/en/licensed_release_notes.md
- docs/en/spark_nlp_healthcare_versions/release_notes_4_2_1.md
updated notebook folder link from `_JSL` to `legacy` ones
updated some typos
> updated RelaseNotes

- src/main/scala/com/johnsnowlabs/nlp/annotators/RecursiveTokenizerModel.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/RecursiveTokenizerFixture.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/RecursiveTokenizerTest.scala
Modifies the code to include begin and end indexes in RecursiveTokenizer Annotationoutput
Check issue #12958
- Unit tests
- Google Colab
> Adding token indexes in RecursiveTokenizer output

- docs/en/ocr_release_notes.md
> updated OCR release notes

- docs/_posts/danilojsl/2022-06-29-dependency_conllu_en_3_0.md
The s3 link to the dependency_conllu model was accidentally modified in June to an old version (Spark NLP 3.0.0). I modified the link back to the latest version (Spark NLP 3.4.4).
> Updating s3 link for dependency_conllu model

- docs/_posts/Ahmetemintek/2022-10-12-cvx_code_mapper_en.md
- docs/_posts/Ahmetemintek/2022-10-12-cvx_name_mapper_en.md
- docs/_posts/Ahmetemintek/2022-10-12-cvx_resolver_pipeline_en.md
- docs/_posts/Ahmetemintek/2022-10-12-sbiobertresolve_cvx_en.md
- docs/_posts/mauro-nievoff/2022-10-01-ner_oncology_biomarker_wip_en.md
Several models were accidentally uploaded with Spark NLP for Healthcare version listed as 4.1.0. I am bumping those versions up to Spark NLP HC version 4.2.1
Several models were accidentally uploaded with Spark NLP for Healthcare version 4.1.0.
N/A
> Bump model card Spark NLP HC version to 4.2.1

- docs/_frontend/src/models/ModelItem/utils.js
- docs/_plugins/search_index.rb
Jira Ticket [NMH-133](https://johnsnowlabs.atlassian.net/browse/NMH-133)
> FEATURE NMH-133: Rename products in search [skip-test]

- src/main/scala/com/johnsnowlabs/nlp/IAnnotation.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/cv/ViTImageClassificationTestSpec.scala
Add an explanation and example use of `IAnnotation` for Scala users
Please check [this issue ](https://github.com/JohnSnowLabs/spark-nlp-internal/issues/1467)
> Add ScalaDoc for IAnnotation

- docs/_posts/2020-09-14-sentence_detector_dl_xx.md
Adds languages to sentence detector model card and fixes issue #13080
> added languages

- docs/_data/navigation.yml
- docs/en/alab/healthcare.md
Added content for healthcare nlp integration
1. Content for healthcare NLP integration (https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Annotation_Lab/Complete_ALab_Module_SparkNLP_JSL.ipynb)
https://user-images.githubusercontent.com/10699092/202962975-05bb48e2-c1e3-4f43-9054-89b3de51fe71.mov
> Added content for healthcare nlp integration

- docs/_data/navigation.yml
- docs/en/alab/troubleshooting.md
Added some content for troubleshooting section
Added some content for troubleshooting section
https://user-images.githubusercontent.com/10699092/202975839-3ad769e6-b42b-4815-b2ee-87bca1e41583.mov
> Added some content for troubleshooting section

- build.sbt
- project/Dependencies.scala
- project/plugins.sbt
- src/main/scala/com/johnsnowlabs/client/gcp/GCPGateway.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
- src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
- src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
- src/main/scala/com/johnsnowlabs/util/ConfigLoader.scala
Adding support to use GCP Storage as a cache folder for pre-trained models.
Check issue #12792
- Local Tests
> SPARKNLP-620 Provide GCP Support for Cache Folder

- src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
Currently, the printed error doesn't include the actual exception. Without knowing the actual exception (could be that the path doesn't exist) the printed error can be misleading. 
This PR incorporate the exception into the printed error message with more generic message that includes more possibilities.
> SPARKNLP-671 incorporate the exception into the error message

- docs/en/alab/annotation_labs_releases/release_notes_4_2_0.md
- docs/en/alab/annotation_labs_releases/release_notes_4_3_0.md
- docs/en/alab/release_notes.md
Added content for Annotation Lab v430 release notes
Content for Annotation Lab v430 release notes
> Added content for Annotation Lab v430 release notes

- docs/_posts/C-K-Loan/2021-03-09-pos_msri_bn.md
> fix python code sample for pos_msri_bn model

- docs/en/alab/annotation.md
- docs/en/alab/annotation_configurations.md
- docs/en/alab/annotation_labs_releases/release_notes_4_4_0.md
- docs/en/alab/productivity.md
- docs/en/alab/rules.md
- docs/en/alab/tasks.md
- docs/en/alab/training_configurations.md
Added content for 440 and 441
Added content for 440 and 441
> Added content for 440 and 441

- docs/en/alab/annotation.md
- docs/en/alab/annotation_configurations.md
- docs/en/alab/annotation_labs_releases/release_notes_4_4_0.md
- docs/en/alab/install.md
- docs/en/alab/productivity.md
- docs/en/alab/rules.md
- docs/en/alab/tasks.md
- docs/en/alab/training_configurations.md
Updated the EKS document
Updated the EKS document
> Updated the EKS document

- docs/_plugins/search_index.rb
Jira Ticket [NMH-142](https://johnsnowlabs.atlassian.net/browse/NMH-142)
> FEATURE NMH-142: Add annotator to models.json [skip-test]

- src/main/scala/com/johnsnowlabs/nlp/annotators/er/AhoCorasickAutomaton.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/er/AhoCorasickAutomatonTest.scala
Adding more details to alphabet error message in EntityRuler to better guide users in the solution.
Allow users to find a faster way to solve alphabet error
- Local Tests
- [Google Colab](https://colab.research.google.com/drive/1S8zH4-HA7MXq4EX84zFDR1Wii1BS9gdy?usp=sharing)
> SPARKNLP-676 Elaborating Alphabet Error Message in EntityRuler

- docs/en/install.md
This PR adds instructions on how to resolve RocksDB incompatibilities when using Spark NLP with an M1 machine.
Closes #13106.
> SPARKNLP-657, SPARKNLP-673: Update install.md

- src/main/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizer.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizerTestSpec.scala
This PR fixes issues with the indexing of tokens in the RegexTokenizer.
If the document was split into sentences, the index of the sentence inside the document was not taken into consideration for the indexes of the tokens. 
This would lead to further issues down the pipeline, where tokens would be filtered while unpacking them for other Annotators:
https://github.com/JohnSnowLabs/spark-nlp/blob/885ff94152b1dbf6c33a5a59b8810a881fb46b2e/src/main/scala/com/johnsnowlabs/nlp/annotators/common/TokenizedWithSentence.scala#L37-L40
An example would be, that NER Annotators would output a different amount of tokens than the output of the `RegexTokenizer`.
Old tests passing and a new test has been added.
> SPARKNLP-678: Fix indexing issue for RegexTokenizer

- docs/en/alab/install.md
> added one missing step in EKS install

- docs/_includes/scripts/custom.js
- docs/_sass/custom.scss
- docs/en/alab/install.md
> Update Install buttons

- docs/_posts/Cabir40/2022-12-20-generic_re.md
> generic_re

- docs/en/licensed_annotator_entries/AssertionDL.md
- docs/en/licensed_annotator_entries/AssertionFilterer.md
- docs/en/licensed_annotator_entries/AssertionLogReg.md
- docs/en/licensed_annotator_entries/ChunkFilterer.md
- docs/en/licensed_annotator_entries/ChunkKeyPhraseExtraction.md
- docs/en/licensed_annotator_entries/ChunkMerge.md
- docs/en/licensed_annotator_entries/ContextualParser.md
- docs/en/licensed_annotator_entries/DeIdentification.md
- docs/en/licensed_annotator_entries/DocumentLogRegClassifier.md
- docs/en/licensed_annotator_entries/DrugNormalizer.md
- docs/en/licensed_annotator_entries/FeaturesAssembler.md
- docs/en/licensed_annotator_entries/GenericClassifier.md
- docs/en/licensed_annotator_entries/IOBTagger.md
- docs/en/licensed_annotator_entries/NerChunker.md
- docs/en/licensed_annotator_entries/NerConverterInternal.md
- docs/en/licensed_annotator_entries/NerDisambiguator.md
- docs/en/licensed_annotator_entries/NerModel.md
- docs/en/licensed_annotator_entries/RENerChunksFilter.md
- docs/en/licensed_annotator_entries/ReIdentification.md
- docs/en/licensed_annotator_entries/RelationExtraction.md
- docs/en/licensed_annotator_entries/RelationExtractionDL.md
- docs/en/licensed_annotator_entries/SentenceEntityResolver.md
I added links to Python API for the documentation pages of licensed annotators.
For all `.md` files in the `docs/en/licensed_annotator_entries` path that had Python API links, I added the corresponding links using the appropriate format.
This is part of an internal effort to improve overall documentation quality. 
No tests were performed, as it is documentation improvement.
> Added links to Python API for licensed annotators

- docs/_includes/input_output_image.html
- docs/_sass/custom.scss
Add input output images on posts
> Input output images

- docs/_posts/josejuanmartinez/2022-08-09-legclf_conventions_en_3_2.md
The model is for Spanish texts, not English.
> Fix language of the model en => es

- src/main/scala/com/johnsnowlabs/nlp/annotators/common/SentenceSplit.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizerTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
This change makes the right computation of a sentence index based on metadata info
Check issue #13311
- Local tests
> SPARKNLP-715 Tokenizer Index Eerror

- docs/_posts/gadde5300/2023-01-13-bert_embeddings_Italian_Legal_BERT_it.md
- docs/_posts/gadde5300/2023-01-13-bert_embeddings_Legal_BERTimbau_base_pt.md
- docs/_posts/gadde5300/2023-01-13-bert_embeddings_Legal_BERTimbau_large_pt.md
- docs/_posts/gadde5300/2023-01-13-bert_embeddings_bert_large_portuguese_cased_legal_mlm_pt.md
- docs/_posts/gadde5300/2023-01-13-bert_embeddings_legal_bert_base_cased_ptbr_pt.md
- docs/_posts/gadde5300/2023-01-13-camembert_embeddings_Italian_Legal_BERT_SC_it.md
- docs/_posts/gadde5300/2023-01-13-camembert_embeddings_legal_camembert_fr.md
- docs/_posts/gadde5300/2023-01-13-camembert_embeddings_legal_distilcamembert_fr.md
- docs/_posts/gadde5300/2023-01-13-camembert_embeddings_lsg16k_Italian_Legal_BERT_SC_it.md
Uploaded the remaining legal embeddings.
> 2023-01-13-camembert_embeddings_Italian_Legal_BERT_SC_it

- docs/_posts/josejuanmartinez/2023-01-13-finmapper_wikipedia_parentcompanies_en.md
- docs/_posts/josejuanmartinez/2023-01-13-finmapper_wikipedia_parentcompanies_ticker_en.md
* Add model 2023-01-13-finmapper_wikipedia_parentcompanies_en
* Add model 2023-01-13-finmapper_wikipedia_parentcompanies_ticker_en
* Update 2023-01-13-finmapper_wikipedia_parentcompanies_en.md
Co-authored-by: josejuanmartinez <jjmcarrascosa@gmail.com>
Co-authored-by: Jose J. Martinez <36634572+josejuanmartinez@users.noreply.github.com>
> 2023-01-13-finmapper_wikipedia_parentcompanies_en (#13341)

- .github/workflows/create_search_index.yml
- docs/Gemfile
- docs/Gemfile.lock
- docs/_config.yml
- docs/_plugins/jekyll-incremental/.gitignore
- docs/_plugins/jekyll-incremental/Gemfile
- docs/_plugins/jekyll-incremental/Gemfile.lock
- docs/_plugins/jekyll-incremental/README.md
- docs/_plugins/jekyll-incremental/Rakefile
- docs/_plugins/jekyll-incremental/jekyll-incremental.gemspec
- docs/_plugins/jekyll-incremental/lib/jekyll-incremental.rb
- docs/_plugins/jekyll-incremental/lib/jekyll/incremental.rb
- docs/_plugins/jekyll-incremental/lib/jekyll/incremental/version.rb
- docs/_plugins/search_index.rb
Jira Ticket [NMH-151](https://johnsnowlabs.atlassian.net/browse/NMH-151)
[NMH-151]: https://johnsnowlabs.atlassian.net/browse/NMH-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FEATURE NMH-151: Speed up website build with Github Actions [skip-test]

- docs/_includes/scripts/article.js
- docs/_includes/scripts/programmingLanguageSwitcherScalaPython.js
> add tabs fix

- python/docs/reference/index.rst
- python/docs/user_guide/annotators.rst
- python/docs/user_guide/pretrained_pipelines.rst
- python/sparknlp/pretrained/resource_downloader.py
This PR adds PyDoc documentation for some hidden features of the ResourceDownloader.
No code changes except documentation.
> [skip ci] SPARKNLP-725: Add PyDoc documentation for ResourceDownloader

- docs/_sass/custom.scss
- docs/demos/deidentification.md
- docs/demos/public_health.md
Old Title:	New Title:
Classify Self Report Age - Tweet	Classify Self-Reported Age from Posts Classify Self-Reported Covid-19 Symptoms - Tweet	Classify Self-Reported Covid-19 Symptoms from Posts Detect Adverse Drug Events in Tweet	Detect Adverse Drug Events from Posts Classify Stance / Premise About Health Mandates in Tweets	Classify Stance About Public Health Mandates from Posts Classify Self Report Vaccination Status - Tweet	Classify Self Report Vaccination Status from Posts
> rename some demos

- docs/_includes/footer.html
- docs/_includes/scripts/custom.js
- docs/index.md
> Update Index and footer date

- docs/en/spark_ocr_versions/ocr_release_notes.md
- docs/en/spark_ocr_versions/release_notes_4_3_1.md
> Ocr release notes 4.3.1

- docs/_includes/docs-annotation-pagination.html
- docs/en/alab/annotation_labs_releases/release_notes_4_7_1.md
- docs/en/alab/playground.md
- docs/en/alab/prompts.md
- docs/en/alab/release_notes.md
> Docs/nlp lab release4.7.1

- docs/en/spark_nlp_healthcare_versions/licensed_release_notes.md
- docs/en/spark_nlp_healthcare_versions/release_notes_4_3_1.md
> update release notes

- docs/_posts/Mary-Sci/2023-03-10-finclf_10k_items_en.md
- docs/_posts/Mary-Sci/2023-03-10-finclf_twitter_news_en.md
- docs/_posts/bunyamin-polat/2023-03-04-finsum_us_news_headers_en.md
- docs/_posts/bunyamin-polat/2023-03-09-finner_responsibility_reports_en.md
- docs/_posts/gadde5300/2023-03-03-finclf_bert_news_tweets_sentiment_analysis_en.md
- docs/_posts/gadde5300/2023-03-10-finner_financial_xlarge_en.md
- docs/_posts/josejuanmartinez/2023-02-24-finner_deid_sec_en.md
- docs/_posts/josejuanmartinez/2023-02-24-finner_signers_en.md
- docs/_posts/josejuanmartinez/2023-02-27-finpipe_deid_en.md
> Finance NLP 1.9.0 Release

- docs/_includes/demomenu.html
- docs/demos/diagnoses_procedures.md
- docs/demos/public_health.md
- docs/demos/vaccinations.md
- docs/learnhub.md
> Update demos Vaccines & Public Health

- docs/_includes/demomenu.html
- docs/_posts/2020-04-22-ner_jsl_en.md
- docs/_posts/2020-04-22-ner_jsl_enriched_en.md
- docs/_posts/Ahmetemintek/2022-10-19-ner_jsl_en.md
- docs/_posts/HashamUlHaq/2021-03-31-ner_jsl_en.md
- docs/_posts/HashamUlHaq/2021-03-31-ner_jsl_enriched_en.md
- docs/_posts/HashamUlHaq/2021-04-01-ner_jsl_biobert_en.md
- docs/_posts/HashamUlHaq/2021-04-01-ner_jsl_enriched_biobert_en.md
- docs/_posts/HashamUlHaq/2021-08-13-ner_jsl_slim_en.md
- docs/_posts/HashamUlHaq/2021-09-05-ner_jsl_biobert_en.md
- docs/_posts/HashamUlHaq/2021-10-22-ner_jsl_enriched_en.md
- docs/_posts/Meryem1425/2022-03-21-bert_token_classifier_ner_jsl_en_2_4.md
- docs/_posts/ahmedlone127/2022-08-10-image_classifier_vit_vision_transformer_fmri_classification_ft_en_3_0.md
- docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_jsl_en.md
- docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_jsl_slim_en.md
- docs/_posts/muhammetsnts/2021-04-30-ner_jsl_en.md
- docs/_posts/muhammetsnts/2021-06-21-ner_jsl_en.md
- docs/_posts/muhammetsnts/2021-06-21-ner_jsl_greedy_en.md
- docs/_posts/muhammetsnts/2021-06-24-ner_jsl_en.md
- docs/_posts/muhammetsnts/2021-06-24-ner_jsl_greedy_en.md
- docs/_posts/muhammetsnts/2021-08-13-ner_jsl_greedy_biobert_en.md
- docs/_posts/muhammetsnts/2021-08-28-bert_token_classifier_ner_jsl_en.md
- docs/_posts/murat-gunay/2021-09-16-bert_token_classifier_ner_jsl_en.md
- docs/_posts/murat-gunay/2021-09-24-bert_token_classifier_ner_jsl_slim_en.md
> Updated md file added label definitions

- examples/util/Training_Helpers.ipynb
Adding notebook example for S3 in CoNLL, CoNLLU and POS training classes
Improve documentation
> SPARKNLP-88 Adding notebook example for S3 in CoNLL, CoNLLU and POS

- docs/demos/legal_text_classification.md
> replaced all of those mentions to hundreds in demo card.

- docs/_includes/docs-annotation-pagination.html
- docs/en/alab/annotation_labs_releases/release_notes_4_8_1.md
> release note for 481

- docs/_posts/maziyarpanahi/2023-02-07-image_classifier_swin_base_patch4_window12_384_in22k_en.md
- docs/_posts/maziyarpanahi/2023-02-07-image_classifier_swin_base_patch4_window7_224_en.md
- docs/_posts/maziyarpanahi/2023-02-07-image_classifier_swin_base_patch4_window7_224_in22k_en.md
- docs/_posts/maziyarpanahi/2023-02-07-image_classifier_swin_tiny_patch4_window7_224_en.md
The huggingface URLS in the swin modelhub cards were incorrect, I updated them
> fixed broken huggingface URLS in Swin modlelhub Cards

- docs/CNAME
> FEATURE NMH-157: Change CNAME to sparknlp.org

- docs/_posts/murat-gunay/2022-05-17-electra_embeddings_finance_koelectra_base_generator_ko_3_0.md
- docs/_posts/murat-gunay/2022-05-17-electra_embeddings_finance_koelectra_small_generator_ko_3_0.md
Improving descriptions and titles of korean financial LM
> Improving descriptions and titles of korean financial LM

- docs/_posts/gadde5300/2022-05-04-roberta_embeddings_financial_en_3_0.md
- docs/_posts/gadde5300/2022-12-07-sbert_chinese_qmc_finance_v1_distill_zh.md
- docs/_posts/gadde5300/2022-12-07-sbert_chinese_qmc_finance_v1_zh.md
- docs/_posts/gadde5300/2022-12-07-sbert_setfit_finetuned_financial_text_classification_en.md
- docs/_posts/luca-martial/2022-04-11-bert_embeddings_FinancialBERT_en_3_0.md
- docs/_posts/luca-martial/2022-04-11-bert_embeddings_bert_small_japanese_fin_ja_3_0.md
- docs/_posts/luca-martial/2022-04-11-bert_embeddings_german_financial_statements_bert_de_3_0.md
- docs/_posts/luca-martial/2022-04-11-bert_embeddings_mengzi_bert_base_fin_zh_3_0.md
Updated title and descriptions of financial embeddings.
> Updated Financial Embeddings

- .github/workflows/create_search_index.yml
- docs/_frontend/src/models/App/App.js
- docs/_frontend/src/models/common.js
- docs/_frontend/webpack.config.js
Jira Ticket [NMH-168](https://johnsnowlabs.atlassian.net/browse/NMH-168)
Requires this PR to work https://github.com/JohnSnowLabs/models-hub/pull/158
[NMH-168]: https://johnsnowlabs.atlassian.net/browse/NMH-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FEATURE NMH-168: Hide licensed models from spark-nlp search [skip-test]

- python/sparknlp/annotator/seq2seq/bart_transformer.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/BartTransformer.scala
This PR Update default model name of BART models
> Update default model name of BART models

- src/main/scala/com/johnsnowlabs/ml/ai/Bart.scala
- src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Generate.scala
- src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/Logit.scala
- src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitProcess/MinLengthLogitProcessor.scala
- src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitProcess/NoRepeatNgramsLogitProcessor.scala
- src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitProcess/RepetitionPenaltyLogitProcessor.scala
- src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitProcessorList.scala
- src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitWarper/TemperatureLogitWarper.scala
- src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitWarper/TopKLogitWarper.scala
- src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitWarper/TopPLogitWarper.scala
- src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Search/BeamHypotheses.scala
- src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Search/BeamScorer.scala
- src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Search/BeamSearchScorer.scala
This PR changes Tensorflow models from INT64 TO INT32
> Update INT64 to INT32

- docs/_posts/ahmedlone127/2023-04-20-distilbert_base_zero_shot_classifier_turkish_cased_allnli_tr.md
- docs/_posts/ahmedlone127/2023-04-20-distilbert_base_zero_shot_classifier_turkish_cased_multinli_tr.md
- docs/_posts/ahmedlone127/2023-04-20-distilbert_base_zero_shot_classifier_turkish_cased_snli_tr.md
- docs/_posts/ahmedlone127/2023-04-20-distilbert_base_zero_shot_classifier_uncased_mnli_en.md
- docs/_posts/ahmedlone127/distilbert_base_zero_shot_classifier_turkish_cased_snli_en.md
- docs/_posts/gokhanturer/2022-10-11-beto_sentiment_es.md
- docs/_posts/josejuanmartinez/2022-10-20-legal_longformer_base_en.md
- docs/_posts/maziyarpanahi/2022-11-28-t5_grammar_error_corrector_en.md
- docs/_posts/maziyarpanahi/2023-02-08-camembert_base_qa_fquad_fr.md
- docs/_posts/maziyarpanahi/2023-02-08-zero_shot_ner_roberta_en.md
- docs/_posts/maziyarpanahi/2023-04-09-bart_large_cnn_en.md
Jira Ticket [NMH-171](https://johnsnowlabs.atlassian.net/browse/NMH-171)
[NMH-171]: https://johnsnowlabs.atlassian.net/browse/NMH-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BUGFIX NMH-171: Fix multiselect for existing opensource docs [skip-test]

- python/sparknlp/annotator/seq2seq/bart_transformer.py
- python/sparknlp/internal/__init__.py
- src/main/scala/com/johnsnowlabs/ml/ai/Bart.scala
- src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Generate.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/BartTransformer.scala
- Optimised models for Bart
- Implement Cache for Bart
- Add generate method for text generation
> Sparknlp 826 upload new optimized models for bart and Generate function

- docs/_posts/Mary-Sci/2023-05-25-distilcamembert_french_legal_fr.md
> Update title for 2023-05-25-distilcamembert_french_legal_fr.md

- docs/_posts/gadde5300/2023-01-13-bert_embeddings_Italian_Legal_BERT_it.md
- docs/_posts/gadde5300/2023-01-13-bert_embeddings_Legal_BERTimbau_base_pt.md
- docs/_posts/gadde5300/2023-01-13-bert_embeddings_Legal_BERTimbau_large_pt.md
- docs/_posts/gadde5300/2023-01-13-bert_embeddings_bert_large_portuguese_cased_legal_mlm_pt.md
- docs/_posts/gadde5300/2023-01-13-bert_embeddings_legal_bert_base_cased_ptbr_pt.md
- docs/_posts/gadde5300/2023-01-13-camembert_embeddings_Italian_Legal_BERT_SC_it.md
- docs/_posts/gadde5300/2023-01-13-camembert_embeddings_legal_camembert_fr.md
- docs/_posts/gadde5300/2023-01-13-camembert_embeddings_legal_distilcamembert_fr.md
- docs/_posts/gadde5300/2023-01-13-camembert_embeddings_lsg16k_Italian_Legal_BERT_SC_it.md
Jira Ticket [NMH-175](https://johnsnowlabs.atlassian.net/browse/NMH-175)
[NMH-175]: https://johnsnowlabs.atlassian.net/browse/NMH-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FEATURE NMH-175: Add Copy to s3 on open source models [skip-test]

- docs/_includes/head.html
- docs/_includes/snippets/get-article-modeltitle.html
changes model title like:
Chunk Entity Resolver RxNorm-scdc | chunkresolve_rxnorm_scdc_clinical | Healthcare NLP 3.0.0+
> update SEO titles

- examples/python/transformers/onnx/ONNX_Configs_in_Spark_NLP_AlbertForQuestionAnswering.ipynb
- src/main/scala/com/johnsnowlabs/ml/onnx/OnnxWrapper.scala
- src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
- src/main/scala/com/johnsnowlabs/util/ConfigLoader.scala
This change allows users to define ONNX session configuration through spark session.
Flexibility for users when using ONNX models
> SPARKNLP-907 Allows setting up ONNX configs through spark session

- examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_DistilBertForQuestionAnswering.ipynb
- examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_DistilBertForSequenceClassification.ipynb
- examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_DistilBertForTokenClassification.ipynb
- src/main/scala/com/johnsnowlabs/ml/ai/DistilBertClassification.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForQuestionAnswering.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForSequenceClassification.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForTokenClassification.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForZeroShotClassification.scala
Adding ONNX support for:
- DistilBertForSequenceClassification 
- DistilBertForTokenClassification
- DistilBertForQuestionAnswering
Adding ONNX support for classification annotators for faster inference
- Local Tests
> Adding ONNX support for DistilBertClassification

- src/main/scala/com/johnsnowlabs/ml/ai/Whisper.scala
This PR fixes a bug with the Whisper annotator, that would not allow every model to be imported.
The issue is, that the number of cache tensors for the decoder model was hard coded. However, the number of cache tensors varies with model sizes.
Tests are passing.
> WhisperForCTC: Fix for dynamic state tensor sizes

- examples/util/Load_Model_from_Azure_Storage.ipynb
Adding an example to load a model directly from Azure using `.load()` method
Helping users to understand how to set spark-nlp to load models from Azure
> Improving Load Model Azure Storage notebook example

- examples/util/Spark_NLP_Structured_Streaming.ipynb
Adding notebook example for structured streaming in spark-nlp using NERDL annotator
Help users to understand how to setup  structured streaming with Spark NLP
> Adding notebook example for structured streaming in spark-nlp

- examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_RoBertaForSequenceClassification.ipynb
Removed code for connection to google drive
> HuggingFace_ONNX_in_Spark_NLP_RoBertaForSequenceClassification updated

- examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_RoBertaForTokenClassification.ipynb
removed code for connection to google drive
> HuggingFace_ONNX_in_Spark_NLP_RoBertaForTokenClassification updated

- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
fixes https://github.com/JohnSnowLabs/spark-nlp/issues/14127
> adding BGEEmbeddings to resource downloader

- build.sbt
- project/Dependencies.scala
- src/main/scala/com/johnsnowlabs/client/aws/AWSGateway.scala
- src/main/scala/com/johnsnowlabs/client/azure/AzureClient.scala
- src/main/scala/com/johnsnowlabs/ml/ai/OpenAICompletion.scala
- src/main/scala/com/johnsnowlabs/ml/ai/OpenAIEmbeddings.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherMultiLanguageTestSpec.scala
Refactoring to use `aws-java-sdk-s3` library instead of `aws-java-sdk-bundle` dependency
Reduce jar size and dependency. Check issue #14128
- Databricks
- EMR
- Google Colab Tests:
- CoNLL read dataset [notebook](https://colab.research.google.com/drive/1lHzfQgdFXy-RZUxCvwmJmQVIez9tICiC#scrollTo=TSuHNDtWtkVg)
- Loading Model from S3 [notebook](https://colab.research.google.com/drive/1KNoDHzyLM_qMwioATuA0etu5k6QXSqwu#scrollTo=PCMnZVr1GqVx)
- NER with S3 Graphs [notebook](https://colab.research.google.com/drive/18T8-iarE_0_wQHQByQIzLAsHPL099mo7?usp=sharing#scrollTo=gTFj-0gxG9xg)
- LoadingSaved HuggingFace Model [notebook](https://colab.research.google.com/drive/1GGv6LoSFWVdVv0l47sxTylALxJ7cto4A?usp=sharing#scrollTo=RTvRX7dvNrr5)
- NER Training Logs …
> [SPARKNLP-978] Refactoring to use aws-java-sdk-s3 library

- python/sparknlp/annotator/er/entity_ruler.py
- python/sparknlp/base/light_pipeline.py
- python/test/annotator/er/entity_ruler_test.py
- src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
- src/test/resources/entity-ruler/url_regex.json
Fixing optional input column validations.
To solve errors as in EntityRuler that outputs duplicated entities.
- Local Tests
- Google Colab [notebook](https://colab.research.google.com/drive/1qgeGb7FheH8ezpF9gpJIP-i7DcRwFg3F?usp=sharing) for EntityRuler
> [SPARKNLP-986] Fixing optional input col validations

- examples/python/transformers/HuggingFace_in_Spark_NLP_DeBertaForSequenceClassification.ipynb
- examples/python/transformers/HuggingFace_in_Spark_NLP_DeBertaForTokenClassification.ipynb
Fixing DeBerta notebooks URIs
Display notebooks examples for DeBerta transformers
> [SPARKNLP-984] Fixing Deberta notebooks URIs

- src/main/scala/com/johnsnowlabs/nlp/annotator.scala
> Add MPNetEmbeddings to annotator

- README.md
- docs/_data/navigation.yml
- docs/en/advanced_settings.md
- docs/en/features.md
- docs/en/install.md
- docs/en/pipelines.md
This PR focuses on restructuring the README and documentation to enhance clarity, organization, and accessibility.
- **Improved User Experience**: Enhanced readability and navigability make it easier for users to find information.
- **Better Maintenance**: Organized structure simplifies future updates and maintenance.
- **Increased Accessibility:** Clear and comprehensive documentation ensures that users at all levels can understand and utilize spark-nlp effectively.
> [SPARKNLP-1015] Restructuring Readme and Documentation

- examples/python/transformers/HuggingFace_in_Spark_NLP_CamemBertForZeroShotClassification.ipynb
- examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_CamemBertForZeroShotClassification.ipynb
- python/sparknlp/annotator/classifier_dl/__init__.py
- python/sparknlp/annotator/classifier_dl/camembert_for_zero_shot_classification.py
- python/sparknlp/internal/__init__.py
- python/test/annotator/classifier_dl/camembert_for_zero_shot_classification_test.py
- src/main/scala/com/johnsnowlabs/ml/ai/CamemBertClassification.scala
- src/main/scala/com/johnsnowlabs/nlp/annotator.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForZeroShotClassification.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceMetadata.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForZeroShotClassificationTestSpec.scala
This pull request introduces the CamemBertForZeroShotClassification model implementation for both TensorFlow and ONNX frameworks.
To provide support for zero-shot classification tasks using the `CamemBert` model across multiple platforms.
- Local Tests
- Google Colab
- Databricks
> Introducing CamemBertForZeroShotClassification annotator

- examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_MiniCPM.ipynb
- examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_NLLB.ipynb
- examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_Nomic.ipynb
- examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_Phi3.ipynb
- examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_QWEN.ipynb
Openvino export Notebooks for new models
> 550 rc export notebooks

- docs/en/annotator_entries/AutoGGUF.md
- python/sparknlp/annotator/seq2seq/auto_gguf_model.py
- src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFModel.scala
This PR changes the default pretrained model for AutoGGUF models. The pretrained model is at PR
https://github.com/JohnSnowLabs/spark-nlp/pull/14410/
> [SPARKNLP-1027] Change Default AutoGGUF pretrained model

- docs/_data/navigation.yml
- docs/en/tasks/automatic_speech_recognition.md
- docs/en/tasks/dependency_parsing.md
- docs/en/tasks/image_captioning.md
- docs/en/tasks/image_classification.md
- docs/en/tasks/landing_page.md
- docs/en/tasks/question_answering.md
- docs/en/tasks/summarization.md
- docs/en/tasks/table_question_answering.md
- docs/en/tasks/text_classification.md
- docs/en/tasks/text_generation.md
- docs/en/tasks/text_preprocessing.md
- docs/en/tasks/token_classification.md
- docs/en/tasks/translation.md
- docs/en/tasks/zero_shot_classification.md
- docs/en/tasks/zero_shot_image_classification.md
**Tasks added:**
- Automatic Speech Recognition
- Dependency Parsing
- Image Captioning
- Image Classification
- Landing Page
- Question Answering
- Summarization
- Table Question Answering
- Text Classification
- Text Generation
- Text Preprocessing
- Token Classification
- Translation
- Zero Shot Classification
- Zero Shot Image Classification
> tasks-docs-integration

- python/sparknlp/annotator/classifier_dl/__init__.py
- python/sparknlp/annotator/classifier_dl/bert_for_multiple_choice.py
- python/sparknlp/internal/__init__.py
- python/test/annotator/classifier_dl/bert_for_multiple_choice_test.py
- src/main/scala/com/johnsnowlabs/ml/ai/BertClassification.scala
- src/main/scala/com/johnsnowlabs/ml/ai/XXXForClassification.scala
- src/main/scala/com/johnsnowlabs/ml/ai/util/PrepareEmbeddings.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForMultipleChoice.scala
- src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForMultipleChoiceTestSpec.scala
This PR adds the `BertForMultipleChoice` model, extending the BERT architecture to handle multiple-choice tasks.
This transformer enhances BERT’s versatility by allowing users to tackle tasks that involve multiple-choice scenarios, such as:
- Standardized test questions
- Survey or quiz automation
- Local Tests
> Introducing BertForMultipleChoice transformer

- docs/en/install.md
This PR adds instructions on how to upgrade cuDNN on Databricks to infer ONNX models with GPU.
Additionally, the Databricks sections have been cleaned up a bit (removed redundant installation Instructions)
> [SPARKNLP-1095] Add installation instructions for ONNX GPU on Databricks

- examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_AlbertForMultipleChoice.ipynb
- examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_AlbertForMultipleChoice.ipynb
- python/sparknlp/annotator/classifier_dl/__init__.py
- python/sparknlp/annotator/classifier_dl/albert_for_multiple_choice.py
- python/sparknlp/internal/__init__.py
- python/test/annotator/classifier_dl/albert_for_multiple_choice_test.py
- src/main/scala/com/johnsnowlabs/ml/ai/AlbertClassification.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForMultipleChoice.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForMultipleChoiceTest.scala
This PR adds the AlbertForMultipleChoice model, extending the ALBERT architecture to handle multiple-choice tasks.
This transformer enhances ALBERT’s versatility by allowing users to tackle tasks that involve multiple-choice scenarios, such as:
- Standardized test questions
- Survey or quiz automation
- Local Tests
- Databricks notebooks
> [SPARKNLP-1105] Introducing AlbertForMultipleChoice Transformer

- examples/python/reader/SparkNLP_TXT_Reader_Demo.ipynb
- python/sparknlp/reader/sparknlp_reader.py
- python/test/sparknlp_test.py
- src/main/scala/com/johnsnowlabs/reader/SparkNLPReader.scala
- src/main/scala/com/johnsnowlabs/reader/TextReader.scala
- src/test/resources/reader/txt/simple-text.txt
- src/test/scala/com/johnsnowlabs/reader/TextReaderTest.scala
This pull request introduces a new feature that enables reading and parsing Text files (.txt) into a structured Spark DataFrame. Leveraging this functionality allows for efficient processing and analysis of text files, seamlessly integrating with Spark NLP for enhanced downstream natural language processing tasks.
**Important: Please do not merge this PR until https://github.com/JohnSnowLabs/spark-nlp/pull/14491 is merged.**
- Structured Data Representation: By transforming txt files content into a well-defined DataFrame structure, we enable seamless integration with Spark’s powerful analytical and data processing capabilities.
- Scalability: Leveraging Spark’s distributed architecture, this feature supports the efficient processing of large volumes of txt files data, which is critical …
> [SPARKNLP-1113] Adding Text Reader

- python/sparknlp/annotator/classifier_dl/roberta_for_multiple_choice.py
Solving package typo error in Python wrapper for `RoBertaForMultipleChoice`
- Local Tests
> [SPARKNLP-1177] Solving typo in Python for RoBertaForMultipleChoice

- examples/python/reader/SparkNLP_PDFToText_Annotator_Demo.ipynb
- examples/python/reader/SparkNLP_PDF_Reader_Demo.ipynb
- examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_MPNetForQuestionAnswering.ipynb
- examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_DistilBertForMultipleChoice.ipynb
- examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_LLAVA.ipynb
- examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_XLMRoBERTaForMultipleChoice.ipynb
Fixing notebook bugs + updating package versions
> Fixing typos in notebooks

- examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_BartTransformer.ipynb
Adding notebook for BartTransformer
> BartTransformer Notebook

- examples/python/reader/SparkNLP_PowerPoint_Reader_Demo.ipynb
Fix reference copy pasted from Excel reader
The notebook is for Power Point parsing but mentions Excel parsing
Not tested it's just for documentation correctness.
> Fix reference copy pasted from Excel reader

- docs/_posts/AbdullahMubeenAnwar/2025-07-15-all_mpnet_base_v2_openvino_en.md
- docs/_posts/AbdullahMubeenAnwar/2025-07-15-bge_medembed_base_v0_1_openvino_en.md
- docs/_posts/AbdullahMubeenAnwar/2025-07-15-bge_medembed_large_v0_1_openvino_en.md
- docs/_posts/AbdullahMubeenAnwar/2025-07-18-nuextract_2.0_2B_en.md
https://colab.research.google.com/drive/1Up3NIQz8rjRvQGZOZt7ziS0UcAAvb-zA?usp=sharing
Notebook used for uploading these models:
bge_medembed_base_v0_1
bge_medembed_large_v0_1
all_mpnet_base_v2
> 2025-07-15-bge_medembed_base_v0_1_openvino_en

- project/Dependencies.scala
- python/sparknlp/annotator/seq2seq/auto_gguf_model.py
- python/sparknlp/annotator/seq2seq/auto_gguf_vision_model.py
- python/test/annotator/embeddings/auto_gguf_embeddings_test.py
- python/test/annotator/seq2seq/auto_gguf_model_test.py
- python/test/annotator/seq2seq/auto_gguf_vision_model_test.py
- src/main/scala/com/johnsnowlabs/ml/gguf/GGUFWrapper.scala
- src/main/scala/com/johnsnowlabs/ml/gguf/GGUFWrapperMultiModal.scala
- src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFVisionModel.scala
- src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFModelTest.scala
- src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFVisionModelTestSpec.scala
- src/test/scala/com/johnsnowlabs/nlp/embeddings/AutoGGUFEmbeddingsTestSpec.scala
This PR fixes several issues:
- AutoGGUFVisionModel python initialization fixed
- CUDA compatability extended for older GPUs
- `save` now allows for prepended file protocols
old and new tests passing
> [SPARKNLP-1280] [SPARKNLP-1284] AutoGGUF Improvements

- examples/python/data-preprocessing/SparkNLP_Reader2Table_Demo.ipynb
- python/sparknlp/reader/reader2doc.py
- python/test/reader/reader2doc_test.py
- src/main/scala/com/johnsnowlabs/reader/Reader2Doc.scala
- src/main/scala/com/johnsnowlabs/reader/Reader2Table.scala
- src/test/scala/com/johnsnowlabs/reader/Reader2DocTest.scala
This PR enhances the Reader2Doc annotator with additional configuration options for more flexible output handling.
Changes:
- Introduces outputAsDocument parameter to return all sentences as a single concatenated document.
- Adds excludeNonText parameter to filter out non-text elements (e.g., tables, images).
These improvements make the annotator more versatile, enabling cleaner document outputs and giving users control over excluding irrelevant content.
- Unit tests
> [SPARKNLP-1282] Adding improvements to Reader2Doc
