python/sparknlp/annotator.py
python/test/annotators.py
src/main/scala/com/jsl/nlp/Finisher.scala
src/main/scala/com/jsl/nlp/annotators/RegexMatcher.scala
src/test/resources/application.conf
src/test/resources/regex-matcher/rules.txt
src/test/scala/com/jsl/nlp/AnnotatorBuilder.scala
src/test/scala/com/jsl/nlp/annotators/RegexMatcherBehaviors.scala
src/test/scala/com/jsl/nlp/annotators/RegexMatcherTestSpec.scala

- RegexMatcher now accepts rulesList and rulesFile params

RegexMatcher modifications to accept the a list of rules as Param

---

python/sparknlp/annotator.py
python/test/annotators.py
src/main/scala/com/jsl/nlp/annotators/sbd/pragmatic/PragmaticContentFormatter.scala
src/main/scala/com/jsl/nlp/annotators/sbd/pragmatic/PragmaticMethod.scala
src/main/scala/com/jsl/nlp/annotators/sbd/pragmatic/SentenceDetectorModel.scala
src/test/scala/com/jsl/nlp/annotators/sbd/pragmatic/PragmaticApproachTestSpec.scala
src/test/scala/com/jsl/nlp/annotators/sbd/pragmatic/PragmaticDetectionBehaviors.scala

Adds the possibility to set a parameter to define custom text that explicitly breaks up sentence
Simply change through spark params in a String Array form that is used by the RuleFactory to split through text manually.
Many user provided text, tended to have its own separator characters on their unstructured raw data. This helps with splitting out content.
Unit tests covering self provided separators and correct example combined with normal sentence breakers. No side effects known as this is just a new parameter in sentence detection

Custom bound separators

---

src/main/scala/com/jsl/nlp/DocumentAssembler.scala
src/test/scala/com/jsl/nlp/DocumentAssemblerTestSpec.scala

DocumentAssembler was indexing the `end` field with sentence.length instead of sentence.length - 1, which is wrong as the `begin` and `end` fields are zero based.
Bugfix with a accompanying test
Unknow bugs. Found while testing
Added new test case for the DocumentAssembler
- [x ] My code follows the code style of this project.
- [x ] All new and existing tests passed.

- FIX BUG: DocumentAssembler was annotating with the wrong `end` field

---

python/sparknlp/annotator.py
python/test/annotators.py
src/main/scala/com/jsl/nlp/Annotation.scala
src/main/scala/com/jsl/nlp/annotators/EntityExtractor.scala
src/main/scala/com/jsl/nlp/annotators/Lemmatizer.scala
src/main/scala/com/jsl/nlp/annotators/RegexMatcher.scala
src/main/scala/com/jsl/nlp/annotators/RegexTokenizer.scala
src/main/scala/com/jsl/nlp/annotators/ner/regex/NERRegexApproach.scala
src/main/scala/com/jsl/nlp/annotators/pos/perceptron/PerceptronApproach.scala
src/main/scala/com/jsl/nlp/annotators/sda/pragmatic/PragmaticScorer.scala
src/main/scala/com/jsl/nlp/annotators/sda/pragmatic/SentimentDetectorModel.scala
src/main/scala/com/jsl/nlp/annotators/spell/norvig/NorvigSweetingApproach.scala
src/main/scala/com/jsl/nlp/util/io/ResourceFormat.scala
src/main/scala/com/jsl/nlp/util/io/ResourceHelper.scala
src/test/scala/com/jsl/nlp/annotators/pos/perceptron/PerceptronApproachBehaviors.scala
src/test/scala/com/jsl/nlp/annotators/spell/norvig/NorvigSweetingBehaviors.scala

- No impact on functionalities
- SpellChecker now defines corpusFormat for dataset training of txt files
- ResourceHelper now uses ResourceFormat
- ResourceHelper now more lightweight, annotator specific manipulation moved to annotator
- Config management moved to annotator specific
ResourceHelper was doing too much too many things that should have been done by annotators  themselves
ResourceHelper now only does very general input management. It also supports one extra additional data format called TXTDS for reading text path as dataset.
It improves code clearness for input management, delegating more to annotators instead of resource helper.
Unit tests updated. There is one side effect, making Finisher smarter when generating annotators output

Code improvements in ResourceHelper

---

python/test/util.py

The sparkContext used for testing was set to use all the available threads in a previous commit. In this commit we re-set it to 4 in order to clean a test error. 
It fixes a failing tests. In the test we read a saved parquet file of 4 partitions, and we assume ordering in the dataframe. In machines with more than 4 cores, the use of read.parquet and limit(100) the test fails because the expected row that we test against is not actually there.

Re-setting the use of 4 threads in the sparkContext used for python tests

---

README.md
build.sbt
docs/components.html
python/sparknlp/base.py
src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
src/main/scala/com/johnsnowlabs/nlp/Finisher.scala
src/test/scala/com/johnsnowlabs/nlp/FinisherTestSpec.scala

Allow the finisher to output an array type column which may be useful for other SparkML transformers
Add a parameter setting which defines the output type of the Finisher. Defaults to StringType
It allows using the annotations result in other transformers that may need the result in the specific form of array. For example, SparkML StopWordsRemover transformer.
Unit tests updated

Finisher output as Array

---

docs/components.html

There is a typo in documentations for POSTagger annotator. 
Current: `setIterations`
Fixed: `setNIterations`

fixing typos in POSTagger documentation

---

src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticSentenceExtractor.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizerBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetectorModelBoundsSpec.scala

Fix for correct bounds returned by SentenceDetectorModel

Correct bounds in SentenceDetectorModel

---

src/main/resources/application.conf
src/main/scala/com/johnsnowlabs/nlp/HasFeatures.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/Lemmatizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfModel.scala
src/main/scala/com/johnsnowlabs/nlp/serialization/Feature.scala
src/test/resources/application.conf

Parquet proved to be too heavy on heap memory. Switching to an optional configuration setting, plus defaulting to RDD Objects returns good results.
Large corpus files make some pipelines very heavy on memory consumption on the driver. This helps there.

Serialization object Broadcasted

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParser.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/parser/dep/GreedyTransition/GreedyTransitionApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingApproach.scala
src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
src/test/scala/com/johnsnowlabs/nlp/SparkAccessor.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/parser/dep/GreedyTransition/GreedyTransitionApproachTest.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentTestSpec.scala

- Improved vivekn training performance
- Fixed dependency parser tests
- Separated wordCount from vivekn wordCount
- New params to customize tokens from corpus
Vivekn Sentiment analysis was causing a bottleneck on training and memory consumption. This helps there by reducing the amount of redudant calls during word count.
This has been tested utilizing a third party sentiment analysis corpora, works best together with the broadcast and rdd object serialization.

Improved Vivekn sentiment analysis training performance

---

docs/components.html
python/sparknlp/annotator.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/annotators/Normalizer.scala
src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/NormalizerBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/NormalizerTestSpec.scala

I've noted that Normalizer lowercases all tokens that are fed into it. I added `lowercase` parameter that, when set to `false`, doesn't lowercase tokens. By default it's `true` so it behaves like previous version.
It seems it could be advantageous to not lowercase some inputs (for example if someone wanted to feed output of SparkNLP pipeline to some other algorithms that are case-sensitive).
I've checked old tests for Normalizer and they still work, and I added tests for `lowercase = true`.

Make lowercasing by Normalizer optional

---

python/example/crf-ner/ner.ipynb
python/sparknlp/annotator.py
python/sparknlp/base.py
src/main/resources/log4j.properties
src/main/scala/com/johnsnowlabs/nlp/AnnotatorApproach.scala
src/main/scala/com/johnsnowlabs/nlp/HasRecursiveFit.scala
src/main/scala/com/johnsnowlabs/nlp/HasWordEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/RecursivePipeline.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParser.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingApproach.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/ApproachWithWordEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/EmbeddingsReadable.scala
src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
src/test/scala/com/johnsnowlabs/ml/crf/CoNLL2003PipelineTest.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/LemmatizerTestSpec.scala

An alternative pipeline that provides annotators with knowledge about their last-state pipeline. This allows some annotator machine learning models re-utilize current pipelines among different datasets, avoiding to have to create inner-pipelines to just run a few NLP tasks within an annotator.
Recursive Pipelines are backwards compatible and are an optional alternative which should boost training performance in some scenarios. As of this writing, Recursive pipelines only help to the CRF NER approach training stage.
Avoid unnecessary waste of time in re-creating inner pipelines just to perform nlp tasks within an annotator. Facilitates the annotator with a tool to re-utilize already trained pipeline instead.

Recursive pipeline

---

src/main/scala/com/johnsnowlabs/nlp/annotators/EntityExtractor.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/Lemmatizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcher.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingApproach.scala
src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala

- Added easier external resource API setters in scala
- Added appropriate NER CRF ExternalResource validations
- Removed unnecessary normalization in wordcount dataset pipeline
- Added support for recursive pipelines in SpellChecker
To avoid having to import and create custom ExternalResource objects to set paths to external files, easier setters have been created to allow user directly set path and delimiters of such files for spark reading defaults.
Avoid extra code when using ExternalResources

Easier ExternalResource API setters

---

build.sbt
src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala

Dumped rocksdb version to 5.2.1 to match the one present in the Databricks classpath.
In this older version LRU cache is set on native code, so that option cannot be passed to the library, that's why it was removed.
I tested for performance and the change in the cache seems not to affect the times.

Dumped rocksdb version to make it run on databricks platform

---

docs/components.html
python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/annotators/EntityExtractor.scala
src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/EntityExtractorTestSpec.scala

Changed the Scala API for EntityExtractor so setEntities() method receives individual parameters instead of an ExternalResource object.
This removes knowledge about internal storage of parameters from a user facing API, and makes things consistent with Python. Also updated documentation.

Fixes to make Scala and Python APIs consistent

---

src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala

- Fixed stop words dots not being recognized properly as sub tokens
- Fixed composite tokens not working properly when the user changes the default target pattern
It improves tokenization accuracy overall

Fixed tokenizer stop words and composite token recognition bugs

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/ApproachWithWordEmbeddings.scala

User reported NER CRF not working due a None.get exception in embeddings() function. This is due the attempt of the annotator to utilize word embeddings when these have not been provided.

Fixed NERCRF not working when not using word embeddings

---

python/run-tests.py
python/sparknlp/__init__.py
python/sparknlp/annotator.py
python/sparknlp/base.py
python/sparknlp/util.py
python/test/misc.py

SparkNLP annotators are now loadable on their own. New changes allow to resolve the java class name of the annotators when they are loaded via the read and load methods.
- New SparkNLPMLReader and SparkNLPMLReadable classes to help resolving the annotators java class
- The annotators python class now holds a "private class attribute" with the name of the java class used by the objects above.
SparkNLP annotators were not loadable on their own
#91 
New python tests used for writing/reading the annotators

SparkNLP annotators are now loadable on their own

---

python/run-tests.py
python/sparknlp/annotator.py
python/sparknlp/base.py
python/sparknlp/common.py
python/test/annotators.py
python/test/misc.py

Automatic generation of getters for all python annotator's params
- Added a new class ParamsGetters which creates a callback to resolve "get*" methods for the python annotators returning the corresponding param (*) value.
Python annotators didn't provide getters for the params
Specific tests in the python test suite
- [X ] My code follows the code style of this project.

Automatic generation of getters for all python annotator's params

---

src/main/scala/com/johnsnowlabs/nlp/HasWordEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/ApproachWithWordEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/serialization/Feature.scala

On com.johnsnowlabs.nlp.serialization.Feature a FileSystem object is created, and used to verify that the provided path exists, if we don't pass the path at creation of the object the default filesystem is used.
We want the filesystem of the path to be used, instead.
Fixes issue #121 
I created a script that writes a model to S3, and then reads it back from the same location.
Ubuntu.
- [ x] Code improvements with no or little impact

passing uri to retrieve the correct FileSystem

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/ApproachWithWordEmbeddings.scala
src/main/scala/com/johnsnowlabs/pretrained/S3ResourceDownloader.scala
src/main/scala/com/johnsnowlabs/util/ZipArchiveUtil.scala

Fixes model downloader not working under windows environment due to backlash character in path

Correct windows backlash into S3 linux slash

---

python/sparknlp/annotator.py
python/sparknlp/base.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/annotators/Stemmer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala

-pyspark getters now properly work when accessing default values
-fixed stemmer language param name
-fixed tokenizer infix param name
-added addInfix param into pyspark
User reported missing addInfixPattern in pyspark and this lead to discovery that default value getters weren't working. This fixes all related issues.

Fixed default value getters in pyspark

---

build.sbt
src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala

This reverts commit c6617309dab6563642b7cf1de0c2d3bac2ec5dac.
Version 5.2.1 does not work on Windows, hence we are reverting rocksdb downgrade, and come back to the newest release, since databricks platform issue can be worked around.

Revert rocksdb to support windows

---

src/main/scala/com/johnsnowlabs/collections/SearchTrie.scala
src/test/scala/com/johnsnowlabs/collections/SearchTrieSpec.scala

Search Trie nodes aren't topological sorted
Fix Search Trie nodes processing according their's topological order.

Fix Search Trie

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/SparkWordEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala

Most common when using Light Pipelines, loading word embeddings generates a race condition within an executor when trying to create and load appropriate temporary files
Sporadically, loading word embeddings based models returned a Null Pointer exception when executors tried to utilize the same resources at the same time. This ensures loading the files is not overlapped.

Fixed race condition in word embeddings setup and load

---

python/example/model-downloader/ModelDownloaderExample.ipynb
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala

Fixes downloader not using proper file system when downloading and caching pretrained models.
Possible Fixes: https://github.com/JohnSnowLabs/spark-nlp/issues/179
Fixes: https://github.com/JohnSnowLabs/spark-nlp/issues/140
Model downloader not working in cluster environments or settings with different filesystems

Makes downloader work with spark filesystem

---

src/main/scala/com/johnsnowlabs/nlp/AnnotatorModel.scala

This reads word embeddings only once when a model was created. Prevents some race condition which happen more frequently in cluster environments or large number of cores.

Preloads word embeddings before annotate udf

---

src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModelTestSpec.scala

Fixes serialization of Symmetric delete annotator, which is not working in 1.5.2

Fix symmetric delete annotator serialization

---

python/sparknlp/base.py

Light Pipelines in python are significantly slower than their scala counterpart. This change prefetches results son annotating large arrays doesn't hit in run-time but only once when called, and put into python memory. Shows performance boost.

Light pipelines prefetch annotation results in pyspark

---

build.sbt
src/main/scala/com/johnsnowlabs/collections/SearchTrie.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala

We recently tried to use *johnsnowlabs-1.5.4* to do a small proof-of-concept with a pretrained model for NER Tagging. We were also trying to load the data from an Amazon S3 bucket (url format: s3://bucket-name/bucket-file)
The data should load from the S3 servers, and model evaluation should happen as expected.
The code errors out with the following stacktrace:
```
java.lang.NoSuchMethodError: com.amazonaws.services.s3.transfer.TransferManager.<init>(Lcom/amazonaws/services/s3/AmazonS3;Ljava/util/concurrent/ThreadPoolExecutor;)V
at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:287)
at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
at …
```

Refactor library to use AWS-sdk-java 1.7.4

---

python/sparknlp/annotator.py
python/sparknlp/base.py
src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala

- Tokenizer allows option to not include defaults
- Fixed pyspark tokenizer infix patterns order
- Added missing finisher's include metadata
Allows user to set whether he wants the Tokenizer to include default patterns as a bundle. If not, tokenizer will resort to user-provided rules only, or target pattern default (e.g. \\S+). Also fixes related bugs.

Tokenizer include defaults

---

python/run-tests.py
python/sparknlp/annotator.py
python/test/annotators.py

Fixes https://github.com/JohnSnowLabs/spark-nlp/issues/227
Simple change to prepend the infix patterns rather than append. Unit test is added to verify correctness.

Prepend infix patterns added via `addInfixPatterns` in Pyspark

---

src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteApproach.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModelTestSpec.scala

Changes in SymmetricDelete annotator to handle an empty dataset
A require validation for a non-empty dataset was included when corpus parameter is not set
An error reported by a user in spark-nlp Slack in questions channel
With the unit test testEmptyDataset

Symspell empty dataset

---

src/main/scala/com/johnsnowlabs/nlp/annotators/assertion/dl/TensorflowSerializeModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLPythonReader.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/SparkWordEmbeddings.scala

Infer embeddings filesystem from path not configuration
May solve @S_L issue of embeddings being read from hdfs instead of s3 when utilized 
REQUIRES cluster testing

Infer embeddings filesystem from path not configuration

---

python/sparknlp/base.py
src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala

Fixed disabling trim for NerCRF training. Added missing getters and setters.
Fixes very low accuracy bug, introduced in 1.6.0. Causing very low performance in NerCRF when training new models.

Fixed NerCRF not training properly due to DocumentAssembler trim

---

src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModelTestSpec.scala

Added a control to determine the case type of a word to be corrected, so that it can return the corrected word in the original case form. e.g. Problex corrected as Problem
Added a support to words with punctuation or symbols. Sym spell now returns the same word instead of dropping the token e.g. Convention: corrected as Convention:  instead of dropping it.
Fix some issues that could make spell checker to deliver unexpected behavior
Unit tests added to SymmetricDeleteModelTestSpec and SymmetricDeleteBehaviors

Sym spell corrections

---

build.sbt

AWS dependency includes old apache-commons library. This seems to be in conflict with Apache-zeppelin dependencies and might make it fail (particularly in python interpreter)

Exclude apache commons codec from aws dependency

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/ClusterWordEmbeddings.scala

Word embeddings are being copied to local executors. But in high parallelism, more than one container may be launched on the same process. Copying cluster files to local may block the process and or return errors.

deepCopy was causing bottleneck and race conditions

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/EmbeddingsHelper.scala

Added support for providing the s3 location directly in EmbeddingHelpers.load method. It will use the aws credentials sets in the application.conf file
Earlier to work with pubmed embeddings which are available on s3 the files need to downloaded seperately to a local location and then read in EmbeddingsHelper. Now the file could be directly read from s3 url. The user needs to provide s3a://the path to the file
The feature was testing by providing s3a uri (s3a://auxdata.johnsnowlabs.com/clinical/resources/PubMed-shuffle-win-2.bin) to EmbeddingsHelper.load method .

added support for s3 file location in embeddings helper load method

---

python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/embeddings/ApproachWithWordEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/ClusterWordEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/EmbeddingsHelper.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/HasEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/ModelWithWordEmbeddings.scala

A problem was arising in local mode when spark files was pointing to the local filesystem in the driver location. This caused word embeddings to change during executions and making crc fail.

Dont copy embeddings if current filesystem is local

---

src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteApproach.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModelTestSpec.scala

The documentation for the SymmetricDeleteApproach.setCorpus method suggests that it can be called with a single String argument. This is true in Python, but not in Scala.
Refer to [issue 345](https://github.com/JohnSnowLabs/spark-nlp/issues/345)

Allow single string argument for corpus parameter (fix git issue 345)

---

build.sbt
src/main/scala/com/johnsnowlabs/nlp/embeddings/ClusterWordEmbeddings.scala

Fixed sporadic too many open files error when predicting large datasets with large embeddings files

Fixed too many open files

---

python/sparknlp/annotator.py
python/test/annotators.py

Fix DataMatcher param name in Python, this makes it in sync between Scala and Python.
Pipelines train by one language, cannot be used in another language. This will fix it.

Fix DataMatcher param name in Python

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala

allow_growth tensorflow gpu improves memory management, reduced default NerDL batch sizes for lesser memory pressure

smaller default nerdl batch size and allow_growth tensorflow gpu option

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala

If a user provides an infix pattern such as `(\\\\n)`, without this fix, most matches wouldn't work unless this pattern covered the entire target. A text like `\\n2.` would not match the infix since it is not covering the entire target. User should add this infix pattern instead `(.*)(\\\\n)(.*)` to allow the rest of the target to be tokenized normally.
This branch helps the user to make infix pattern more intuitive.

Users infix patterns should include non covered surroundings

---

src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala

For long text the Context Spell Checker can have poor performance. By limiting the number of tokens the Spell Checker uses for deciding the best correction candidate, running time is bounded.
The default value is 5. This value has been shown to keep accuracy almost unmodified and still be ~ twice faster than the no limit situation in some test datasets.

Limit the context information for Context Spell Checker

---

.travis.yml
Dockerfile
src/main/scala/com/johnsnowlabs/nlp/functions.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/SpellCheckersPerfTest.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingTestSpec.scala
src/test/scala/com/johnsnowlabs/util/ExportCSVToolTestSpec.scala

Before, the explodeAnnotations() function only worked when the two input parameters were the same. Now it will work both for the case when the user wants to replace the existing column with the exploded one(column == outputCol), and for the case when the user wants to create a new column for the exploded annotations(column != outputCol).

fix explode annotations

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/ClusterWordEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/PretrainedPipeline.scala

- Kryo deserialization support for wrapper rollback
- NerDLModel added missing get proto bytes
- Improved cluster embeddings message to consider cluster mode without hdfs
- Removed lazy model downloading on pretrained
- Fixed URI construction for cluster embeddings on non defaultFS configurations

Fixed kryo and cluster nerdl support

---

docs/en/quickstart.md

The utilization of the OcrHelper in the documentation is wrong.
The OcrHelper is a class and can't be used without instantiating.

fix the use of the OcrHelper in QuickStart.md

---

build.sbt
src/main/scala/com/johnsnowlabs/nlp/embeddings/EmbeddingsHelper.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala

Now AWS credentials can be passed using the default chain instead of application.conf.
for details on AWS chain please check https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html
If AWS credentials are not set using any option provided above it will also look into spark Hadoop configuration for keys at "fs.s3n.awsAccessKeyId" and "fs.s3n.awsSecretAccessKey" these can be set using the following code in pyspark
```
sc=spark.sparkContext
hadoop_conf=sc._jsc.hadoopConfiguration()
hadoop_conf.set("fs.s3n.awsAccessKeyId", access_id)
hadoop_conf.set("fs.s3n.awsSecretAccessKey", access_key)
```
If application.conf does not contain the AWS credentials then the DefaultAWSChain is used to access the resources. If none of the options of DefaultAWSChain is set then the hadoop …

Aws credentials load

---

python/sparknlp/internal.py
python/sparknlp/util.py
src/main/scala/com/johnsnowlabs/util/ConfigLoader.scala

- environment variable SPARKNLP_CONFIG_PATH to be checked first as overridden config path
- removed set config

changed code to look for enviornment variable as first priority application conf

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala

This pull request introduces 2 new features in NerDLApproach:
1. Evaluates the model against the proportion of training dataset after each Epoch by setting `setTrainValidationProp(Float)` - value is between `0.0` and `1.0` where `0.0` is off and `1.0` is against 100% of the training dataset
2. Add support for extended logs in the validation stage. By setting `setValidationLogExtended` to true, the validation logs will be extended to having the time it took and label by label evaluation (perc, recall, and F1). 
Example:
```scala
val ner = new NerDLApproach()
.setInputCols("sentence", "token", "embeddings")
.setOutputCol("ner")
.setLabelColumn("label")
.setOutputCol("ner")
.setLr(1e-3f)
.setPo(5e-3f)
.setDropout(5e-1f)
.setMaxEpochs(10)
.setRandomSeed(0)
.setVerbose(0) …
```

Adding support for NerDLApproach evaluation during training

---

src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala

This adds the Spell Checker score to the annotation metadata structure. The score represents the penalty that is connected to recognizing text by the Spell Checker. 
The higher the value the more difficult it was for the algorithm to recognize the text as valid English.

added spell checker score to metadata

---

python/sparknlp/annotator.py
python/sparknlp/base.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/common/TokenizedWithSentence.scala
src/main/scala/com/johnsnowlabs/nlp/util/regex/RuleFactory.scala
src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
src/test/scala/com/johnsnowlabs/nlp/DataBuilder.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala

based on the long user feedback on DocumentAssembler and Tokenizer, we were having the following troubles:
1. People reported wrong start/end offsets relative to the original document
2. People reported Tokenizer difficult to customize and use
3. People reported confusion regarding language agnostic Tokenizer
4. People reported difficulties understanding Document default cleanup rules, hard to follow new lines cleanup
Given this, the following changes are being planned and implemented for release 2.1:
1. DocumentAssembler no longer applies clean up by default. Default will be to keep source as is (i.e. new lines, tabs, junk)
2. DocumentAssembler will receive a cleanup parameter that will allow it to be customized in the way it cleans up
* disabled -> will leave document untouched …

Tokenizer revisited

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala

Example:
```scala
val conll = CoNLL()
val training_data = conll.readDataset(ResourceHelper.spark, "python/tensorflow/ner/conll2003/eng.testa")
val test_data = conll.readDataset(ResourceHelper.spark, "python/tensorflow/ner/conll2003/eng.testb")
val embeddings = WordEmbeddingsModel.pretrained().setOutputCol("embeddings")
val trainData = embeddings.transform(training_data)
val testData = embeddings.transform(test_data)
testData.write.mode("overwrite").parquet("./tmp_conll_test")
val ner = new NerDLApproach()
.setInputCols("sentence", "token", "embeddings")
.setOutputCol("ner")
.setLabelColumn("label")
.setOutputCol("ner")
.setLr(1e-1f) //0.1
.setPo(5e-3f) //0.005
.setDropout(5e-1f) //0.5
.setMaxEpochs(1)
.setRandomSeed(0)
.setVerbose(0)
.setTrainValidationProp(0.1f) …
```

Introducing test evaluation in NerDLApproach

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala

Loading a BERT model from source, was not triggering contrib to be loaded. This is a fix for it.

Load contrib to cluster when reading a python bert model

---

src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.scala

Since the refactor of DocumentAssembler cleanupMode, empty sentences can happen. This avoids errors later on in the pipeline  to cleanup empty sentences from SentenceDetector

Filter empty sentences, improve error message in flush

---

src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
src/test/scala/com/johnsnowlabs/nlp/FinisherTestSpec.scala

As of 2.0, `Finisher` and `LightPipeline` show the token string when the embeddings column is part of the output, it should now show the embeddings instead.

Finisher and Light Pipelines deal with embeddings accordingly

---

python/sparknlp/base.py
python/sparknlp/common.py
python/test/annotators.py

Allows python setInputCols to receive args so user input does not require a list to pass column names. Just makes usage of the library more practical.

Python input cols args

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/annotators/sda/pragmatic/SentimentDetector.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/sda/pragmatic/SentimentDetectorModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/sda/pragmatic/PragmaticSentimentTestSpec.scala

Added a flag to allow for the score from the SentimentDetector/Model to output as a double rather than the current "positive" or "negative". I also added the python support.
This change allows for sorting and comparing sentiment scores on articles, rather than the binary positive or negative before. It will allow greater analysis and insight into the text.
I built and deployed this change on a Spark cluster and tested the functionality with success. The cluster are all linux boxes. I also then disabled the flag (by letting it default) and ran it again, with the original expected result.
N/A

enableScore flag for SentimentDetector/Model to output score as double

---

src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala

If sparknlp.settings.pretrained.credentials.aws_profile_name setting is set then the profile name will be used to make s3 connection.
The credential method will now give the first priority to the aws profile name set in application conf for variable sparknlp.settings.pretrained.credentials.aws_profile_name. Followed by the AWS Keys i.e sparknlp.settings.pretrained.credentials.access_key_id and sparknlp.settings.pretrained.credentials.secret_access_key
if the settings are not found it will then lookup default profile with name spark_nlp. If Even that is not found then it will use the AWS Default credential chain lookup.
it will allow user to have a specific profile in there aws config or set up spark_nlp as a profile name in aws config which can be automatically looked up if set.
tested …

Aws profile name resource download

---

src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/LemmatizerModel.scala
src/test/java/com/johnsnowlabs/nlp/GeneralAnnotationsTest.java

Fixed bad Lemmatizer trait caused Lemmatizer to download a Tokenizer model instead and fail.
Workaround is to call `LemmatizerModel.pretrained("lemma_antbnc")`

fix of lemmatizer bad trait

---

src/main/scala/com/johnsnowlabs/nlp/HasInputAnnotationCols.scala
src/main/scala/com/johnsnowlabs/nlp/HasPretrained.scala
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/LemmatizerModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyParserModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModel.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
src/test/java/com/johnsnowlabs/nlp/GeneralAnnotationsTest.java

In java, calling an AnnotatorModels `pretrained()` would return `PipelineStage` type instead of itself. This adds Java compliant overrides to solve that case.

Java pretrained compliant

---

python/run-tests.py
python/sparknlp/base.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/EmbeddingsFinisher.scala
src/test/scala/com/johnsnowlabs/nlp/EmbeddingsFinisherTestSpec.scala

`EmbeddingsFinisher` transforms annotators with embeddings into an acceptable schema for Spark ML. It can be both `Array[Array[Float]]` or `Array[Vector]` which both are acceptable in Spark ML functions whenever Vectors `features` are expected.
```scala
val embeddingsFinisher = new EmbeddingsFinisher()
.setInputCols("sentence_embeddings", "embeddings")
.setOutputCols("finished_sentence_embeddings", "finished_embeddings")
.setOutputAsVector(true)
.setCleanAnnotations(false)
```

Introducing EmbeddingsFinisher Transformer

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/ClusterWordEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala

In some local mode scenarios, saving embeddings to disk yielded `crc` checksum errors. This is due to a move optimization made in the past. This optimization is now reverted in favor of stability.

Reverted embeddings move to copy due to crc issue

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddings.scala
src/test/scala/com/johnsnowlabs/nlp/EmbeddingsFinisherTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddingsTestSpec.scala

When the input of `SentenceEmbeddings` is empty it crashes with `IndexOutOfBoundsException`. Sometimes, the input of WordEmbeddings or BertEmbeddings can be `StopWordsCleaner` which results in not having any tokens inside the results. 
This used to crashes in `SentenceEmbeddings`, now it outputs an empty array as expected.

Fix IndexOutOfBoundsException in SentenceEmbeddings

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
src/main/scala/com/johnsnowlabs/nlp/EmbeddingsFinisher.scala
src/main/scala/com/johnsnowlabs/nlp/base.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddingsTestSpec.scala

This PR intends to deal with `BertEmbeddings` annotator memory consumption.
reference: https://github.com/tensorflow/tensorflow/issues/8244#issuecomment-285459455

Optimize BertEmbeddings memory consumption

---

src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
src/main/scala/com/johnsnowlabs/nlp/AnnotatorType.scala
src/main/scala/com/johnsnowlabs/nlp/EmbeddingsFinisher.scala
src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala

Make ChunkEmbeddings output to be compatible with SentenceEmbeddings 

---

src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
src/main/scala/com/johnsnowlabs/nlp/AnnotatorType.scala
src/main/scala/com/johnsnowlabs/nlp/EmbeddingsFinisher.scala
src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddingsTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala

In some cases when there are no tokens due to normalizations or removing stop words. the BertEmbeddings crashes instead of resulting an empty result. This PR will fix this issue.

Fix BertEmbeddings crashing on empty input

---

src/main/scala/com/johnsnowlabs/nlp/annotators/common/EmbeddingsWithSentence.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/common/SentenceWithEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/common/TokenizedWithSentence.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/TextMatcherTestSpec.scala

Just avoiding the filtering of sentences with no tokens. Filtering sentences seems to have no use case at all, it actually makes everything from then on untraceable.
To be consistent with sentence indexing all throught the annotation Pipeline
Same tests run

Keep original index for the sentence-token columns pair

---

python/sparknlp/__init__.py
python/sparknlp/annotation.py
python/sparknlp/base.py
python/sparknlp/functions.py
src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
src/main/scala/com/johnsnowlabs/nlp/functions.scala
src/test/scala/com/johnsnowlabs/nlp/FunctionsTestSpec.scala

Adds `map_annotations`, `map_annotations_strict`, `map_annotations_col`, `filter_by_annotations_col` and `explode_annotations_col` to python side. Renamed Scala side functions to be the same.

Adds python UDF ready functions to deal with annotations

---

src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcher.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTestSpec.scala

Flexible dates in DateMatcher returned `java.lang.NumberFormatException: For input string: ""` 
This fixes the error and also adds missing metadata of its annotations.

Date matcher fix flexible dates

---

python/sparknlp/functions.py

Because of a sys.modules hack to workaround serialization issues, importing of `Annotation` will fail after calling map functions the second time.
This alleviates the issue by moving the import to top level, however, Importing manually `Annotation` after a function is called will still fail.

Move import to top level to avoid import fail

---

docs/en/annotators.md
python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/annotators/NGramGenerator.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/NGramGeneratorTestSpec.scala

Include a parameter in NGramGenerator to allow for a separator/delimiter string.By default it will use " " (space) to join the tokens.
Include the parameter
Implement its consumption inside the mkstring function
It allows the user to flexibly meet the token format of the previously stored embeddings (delimiter for composed tokens)
Specific test for the setDelimiter and getDelimiter functionality
Test for expected results
- [X ] My code follows the code style of this project.
- [ X] My change requires a change to the documentation.
- [ X] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [ X] I have added tests to cover my changes.
- [ X] All new and existing tests passed.

Delimiter param for NGramGenerator

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala

When a chunk is fully composed by OOV words, and the parameter skipOOV is set to true, there might be a chance of an empty bag of vectors. When that happens this the result should just be the aggregation of whatever OOV vectors arrived.
Mainly a line selecting which vectors to make part of the pooling calculation.
Sometimes we want to discard the OOV vectors from downstream tasks.
Unit test for the feature

SkipOOV parameter for ChunkEmbeddings

---

python/sparknlp/annotator.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala

This PR introduces two new params for Tokenizer. The `minLenght` and `maxLength` are very useful when dealing with broken sentences like Tweets, OCR results, etc. where the user wants to make sure the length of tokens going through the pipeline.
These features also ensure resources are being used over tokens within the target size only. When any token less than 3 characters won't matter to the user, there will be filtered out so they won't be used in the next annotators such as POS tagging, embeddings, NER, etc.
Example:
```scala
val tokenizer = new Tokenizer()
.setInputCols("document")
.setOutputCol("token")
.setMinLength(4)
.setMaxLength(10)
```
The results will be tokens larger equal than `4` characters and less than equal than `10` characters.

Introducing minLength and maxLength features in Tokenizer

---

python/sparknlp/annotator.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/SentenceDetectorParams.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetector.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticApproachTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticDetectionBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetectorBoundsSpec.scala

This PR introduces two new params for SentenceDetector. The **minLenght** and **maxLength** are very useful to filter out sentences based on min and max sentence's length.
**BREAKING CHANGES:** The old `maxLength` which was intended to truncate the sentence and split it into multiple sentences based on the target length now is renamed to `splitLength` in SentenceDetector and DeepSentenceDetector.
Example:
```scala
val sentence = new SentenceDetector()
.setInputCols(Array("document"))
.setOutputCol("sentence")
.setMinLength(16)
.setMaxLength(26)
```
The results are, sentences larger equal than 16 characters and less than equal than 26 characters.

Introducing minLength and maxLength features in SentenceDetector

---

docs/en/annotators.md
python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/annotators/NGramGenerator.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/NGramGeneratorTestSpec.scala

Include a parameter in NGramGenerator to allow for a separator/delimiter string.By default it will use " " (space) to join the tokens.
Include the parameter
Implement its consumption inside the mkstring function
It allows the user to flexibly meet the token format of the previously stored embeddings (delimiter for composed tokens)
Specific test for the setDelimiter and getDelimiter functionality
Test for expected results

Ngram delimiter param

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala

ChunkEmbeddings was getting the chunk id by using head in the metadata (first key)
This PR changes it to get the explicit "chunk" key
ChunkEmbeddings was failing on NER because the first index in an NER chunk is the actual entity
This is not a new feature
All tests passed

Get the chunk metadata by its name rather than by its index

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala

Tokenizer split chars review for multiple occurences, deleted the split char from retrieved tokens
TokenizerModel's splitChars was not working correctly when there were multiple splitChars in the same token. This fixes that behavior, and also removes the split char itself from the output tokens.

Tokenizer split chars review

---

python/sparknlp/common.py
src/main/scala/com/johnsnowlabs/storage/HasStorageModel.scala
src/main/scala/com/johnsnowlabs/storage/StorageHelper.scala

Annotators with `HasStorageModel` can now call `saveStorage(path, sparkSession)` to save their indexed storage. This allows them to be loaded later through `loadStorage(path, sparkSession, ref)`

Storage annotators can now explicitly save their storage

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSerializeModel.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/ElmoEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoder.scala

Currently, the BertEmbeddings and UnviersalSentenceEncoder annotators cannot be saved individually or inside a pipeline. This PR fixes this issue.

Fix reading, loading and saving TF SavedModel

---

src/main/scala/com/johnsnowlabs/nlp/annotators/NGramGenerator.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/NGramGeneratorTestSpec.scala

NorvigSweetingModel doesn't add `sentence` to its metadata which has the id of each sentence. This causes problems in further annotators such as NGramsGenerator where the sentence ID is needed.
https://github.com/JohnSnowLabs/spark-nlp/issues/780

Fix NorvigSweetingModel missing sentence ID in its metadata

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoder.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoderTestSpec.scala

In some scenarios when a document or a sentence is empty the UniversalSentenceEncoder crashes:
https://github.com/JohnSnowLabs/spark-nlp/issues/782

Fix UniversalSentenceEncoder crashing with empty sentences

---

python/run-tests.py
python/sparknlp/annotator.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala

Due to the wrong type in `downloadModel` it wasn't possible to download and load the ElmoEmbedings model in `pretrained()`. 
Also, `poolingLayer` is supposed to be a `string`, not `int`.

Fix ElmoEmbeddings.Pretrained() in Python

---

python/run-tests.py
python/sparknlp/annotator.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowClassifier.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
src/test/resources/classifier/sentiment.csv

Introducing ClassifierDL annotator for training multi-class text classification

---

src/main/scala/com/johnsnowlabs/nlp/serialization/Feature.scala
src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala

Fix ConfigLoader.retrieve not to use the config or fallback config as String and also cleaned up unrequired settings from Feature.scala.
Detailed tests: https://github.com/JohnSnowLabs/spark-nlp/issues/832

Fix java.io.UTFDataFormatException in cluster-mode and some Databricks runtime versions

---

src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala

In the current `splitChars` implementation, the requirement defined below is problematic when splitting on characters which are regex meta characters.
```
def setSplitChars(v: Array[String]): this.type = {
require(v.forall(_.length == 1), "All elements in context chars must have length == 1")
set(splitChars, v)
}
```
For example, attempting to split on the `|` character as implemented will behave improperly.
```
scala> test
res4: String = he,ll@o(mike)||t
scala> test.split("|")
res5: Array[String] = Array(h, e, ,, l, l, @, o, (, m, i, k, e, ), |, |, t) // BAD!
scala> test.split("\\|")
res6: Array[String] = Array(he,ll@o(mike), "", t) // GOOD, but rejected by require.
```
Implements a `splitPattern` param where users can directly provide the splitting regex. `splitPattern` takes priority …

splitPattern alternative for Tokenizers

---

python/sparknlp/annotator.py
python/sparknlp/functions.py
python/tensorflow/ner/create_models.py
src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala

In the current `splitChars` implementation, the requirement defined below is problematic when splitting on characters which are regex meta characters.
```
def setSplitChars(v: Array[String]): this.type = {
require(v.forall(_.length == 1), "All elements in context chars must have length == 1")
set(splitChars, v)
}
```
For example, attempting to split on the `|` character as implemented will behave improperly.
```
scala> test
res4: String = he,ll@o(mike)||t
scala> test.split("|")
res5: Array[String] = Array(h, e, ,, l, l, @, o, (, m, i, k, e, ), |, |, t) // BAD!
scala> test.split("\\|")
res6: Array[String] = Array(he,ll@o(mike), "", t) // GOOD, but rejected by require.
```
Implements a `splitPattern` param where users can directly provide the splitting regex. `splitPattern` takes priority …

Splitpattern and splitchars patch

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala

The batchSize is not used inside NerDLModel and it is not presented in Python. I removed the param as it has no advantage.

Removing unused param in NerDLModel

---

python/sparknlp/base.py
src/main/scala/com/johnsnowlabs/nlp/TokenAssembler.scala
src/test/scala/com/johnsnowlabs/nlp/TokenAssemblerTestSpec.scala

Changed TokenAssembler to be able to process the formating of the sentences. Used `setPreservePosition` parameter and added it to the Python. Format of annotator changed - input columns should be `Array(initial_sentence, tokens)`
Previously TokenAssembler couldn't process special characters and returned new text without any formating.
Created tests for 3 use cases - plain text, text with special characters, and text with stop words removal.

Token assembler should preserve the new lines from DocumentAssembler

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/Logging.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowClassifier.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala
src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala

It is now possible to use `setOutputLogsPath` param in `NerDLApproach` and `ClassifierDLApproach` when `setEnableOutputLogs` is set to `true` to set the output folder to save the logs during training.

Introducing new outputLogsPath for NerDLApproach and ClassifierDLApproach

---

src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala

Changed code to handle dbfs file system separately to fix setGraph Path issue in nerDL.
The following file system are now supported
1) HDFS
2) normal File based systems
3) DBFS
S3 is still not supported though
To use dbfs file system path 
use file:/dbfs/<mounted dbfs folder> (mounted path are shown at [https://docs.databricks.com/data/databricks-file-system.html](dbfs)
or file:/<driver folder path>
for example
file:/dbfs/FileStore/tables/ -- if you uploaded the graph file directly using file upload interface of dbfs 
file:/databricks/driver/ -- if you downloaded the graph files from internet.
Note: for faster lookup make sure you copy the graph files into a specific folder and give that folder path. directly.

fixed databricks setGraph Path issue.

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcher.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcherModel.scala
src/test/resources/entity-extractor/test-phrases-par.txt
src/test/scala/com/johnsnowlabs/nlp/annotators/TextMatcherTestSpec.scala

Currently the TextMatcher  builds the chunk from the raw sentence
I included a param to generate the chunk from the tokens, not to lose any preprocessing done on them.

253 text matcher from tokens

---

src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala

If symbols are not in the dictionary ContextSpellChecker not working correctly (return empty corrected token). Added placeholder for the tokens (symbols) not in the dictionary
Tested with the sentence "(Cannot be symptom-based): " - was failing before

fix symbols check in decodeViterbi

---

docs/en/concepts.md

fixed multi-language selection tabs here https://nlp.johnsnowlabs.com/docs/en/concepts
Tested by running Jekyll server locally and verifying everything works fine.

fixed multi language selection tabs on "general concepts" docs page

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/StopWordsCleaner.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/StopWordsCleanerTestSpec.scala

This PR introduces `pretrained()` function to `StopWordsCleaner` annotator. This allows users to downloads pre-trained models for all languages and other custom stop words lists.
Deliver stop words lists as pre-trained models

Add pretrained support to StopWordsCleaner annotator

---

python/sparknlp/__init__.py

This PR fixes the error in `LanguageDetectorDL` pipeline: 
```
ModuleNotFoundError: No module named 'com.johnsnowlabs.nlp.annotators.ld'; 'com.johnsnowlabs.nlp.annotators' is not a package
```

Fix ModuleNotFoundError in LanguageDetectorDL pipelines

---

python/sparknlp/annotator.py

Due to a bad default value in Python RegexTokenizer crashes. This PR will fix that.

Fix a bug in RegexTokenizer on Python side

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbert.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlnet.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddings.scala

This PR fixes the following issues:
- BertEmbeddings and AlbertEmbeddings do not support sequences longer than 512 because of trainable positional embeddings. A condition was added to `maxSentenceLength` to ensure it is less than equal 512.
- In AlbertEmbeddings even with `maxSentenceLength` less than 512 it is possible to generate more SentencePiece IDs, so we have to ensure that the max sequence length after generating SentencePiece. (we cut the sentence by maxSentenceLength before generating SentencePiece to save extra computations over tokens which won't be part of the output anyway)
Note: The issue of `maxSentenceLength` being larger than 512 has been hidden since the best practice is to feed `sentence` into AlbertEmbeddings, BertEmbeddings, XlnetEmbeddings, and ElmoEmbeddings. Even …

Fix max sequence length issue in AlbertEmbeddings and BertEmbeddings

---

docs/_data/navigation.yml
docs/en/examples.md
docs/en/licensed_annotators.md
docs/en/licensed_install.md
docs/en/licensed_release_notes.md
python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/SentenceDetectorParams.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticContentFormatter.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticMethod.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticDetectionBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetectorBoundsSpec.scala

Added a parameter, detectLists, to SentenceDetector so the split of sentences in a list of items can be disabled.
This behavior was necessary to deal with numbers around sentence boundaries.
All test suits cases Scala/Python.

added parameter to enable/disable list detection in SentenceDetector

---

src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala

SentimentDL model only accepts 2 labels, but we check for up to 3. This results in other errors related to TF where those layers for 3 labels don't exist.
This PR fixes this issue by communicating with users more clearly when they have more or less than 2 labels/classes during the training.

Better error handling in SentimentDLApproach

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala

This PR fixes the issue when the exported BERT models don't require `init_all_tables` in the graph. This only improves the quality of the BERT models exported from checkpoints and doesn't change the models from TF Hub module.

Fix BERT loadSavedModel

---

python/run-tests.py
python/sparknlp/annotator.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLSpec.scala

This PR fixes the` Unsupported Model` error in SentenceDetectorDLModel when it is used with `.pretrained()`, adds unit tests for Scala and Python using the pretrained model, and sets a default pretrained model's name for Python side.

Fix SentenceDetectorDL Unsupported Model error

---

src/main/scala/com/johnsnowlabs/nlp/util/LruMap.scala

Fixes a race condition in Lru that can cause NullPointerException during a LightPipeline operations with embeddings.
When using a LightPipeline on a large collection with a pipeline containing embeddings (for example explain_document_dl), a race condition triggers and quite often can trigger a NullPointerException in `LruMap:61`. This clause addresses this problem, with no significant performance impact.
Solves a NullPointerException in LruMap
Unit tests, manual testing.

Fixed race condition in LruMap

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala

This PR fixes the issue when the sentence is longer than 512 tokens as the new calculation released in 2.6.0 with dynamic shape fails with a correct calculation/trimming.

Fix BERT max sequence length calculation

---

build.sbt

This PR makes the default Apache Spark of Spark NLP the `2.4.7`.

Upgrade to the latest Apache Spark 2.4.x release

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala

Fix bug in producing multiple annotations per sentence when the number of sentences in a row exceeds the batch size
The problem was that TensorflowBert.calculateSentenceEmbeddings was grouping the data into batches and then using the ungrouped sentence collection to get the sentence details
TensorflowBert.calculateSentenceEmbeddings updated
There were multiple records for the same sentence when there were more than batchSize sentences per row. The bug affected the sentence string (i.e. result) and other details (begin, end, metadata), but not the embeddings itself.
I've tested it manually
- [ x] My code follows the code style of this project.
- [ x] All new and existing tests passed.

Fix bug in bert sentence embeddings resulting in multiple annotations per sentence

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala

I noticed the following bugs in the Python API
- Bad default values for pretrained T5 and Wordsegmenter ( fixed)
- Missing reference for PythonRessource Downloaded (fixed)
- WordSegmenter not loadable (fixed)
- T5.pretrained() and WordSegmenter.pretrained() threw errors'model not found' because of bad pretrained values
- WordSegmenter  model not creatable, throwing JavaErrors when creating it in Python 
- Created FatJar and loaded it  in spark-nlp 2.7.0 python Enviroment. This fixed all issues marked as fixed
- [] All new and existing tests passed. Did not run the tests

2.7.0 py api bug fixes T5, WordSegmenter

---

README.md

Updated Slack link, valid for 30 days from today (till Feb 6th, 2021)

Slack link updated

---

src/main/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizer.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizerTestSpec.scala

Fix to restore the actual regex tokenizer tag algorithm which is used by default.
Fix is necessary to restore the existent tagging algorithm behavior.
Locally restoring the RegexTokenizer suite in regression tests.
Adding the new test for the new algorithm.
- [x ] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.

Fix to restore the regex tokenizer tag algorithm

---

src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherBehaviors.scala

Currently, RegexMatcher resets the beginning and the end of each chunk regardless of the start and the end of each sentence. This PR fixes this issue by recalculating each CHUNK's start and end based on the sentence's start and end.

Fix chunks begin and end in RegexMatcher

---

python/sparknlp/annotator.py

Bugfix to change the default value for action parameter in Python wrapper for DocumentNormalizer annotator.
The DocumentNormalizer annotator Python wrapper has a default value for parameter action set to "clean_up" instead of "clean" so the bugfix is needed to let the default value work.
User notification of the error.
Scala code has been tested with unit tests, Python code has been tested with unit tests but both cases force explicit parameters not covering faulty default values.

Fixing action default value in DocumentNormalizer Python wrapper

---

docs/en/annotators.md
python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcherUtils.scala
src/main/scala/com/johnsnowlabs/nlp/util/regex/RuleFactory.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTestSpec.scala

This commit adds `anchorDateYear`, `anchorDateMonth`, and `anchorDateDay` params to `DateMatcher` to set a base Date to relative dates. For instance, `tomorrow` can be a day after those dates or if they are not set it will be a day after the current date.

Add anchorDate params to DateMatcher and MultiDateMatcher

---

README.md
python/README.md

Fix typo in /README.md and /python/README.md
Befor, The doc is "# sparknlp.start(sparrk23=True) is when you have Apache Spark 2.3.x installed",
if users copy it and run it in their kernel, a bug will exist.
TypeError: start() got an unexpected keyword argument 'sparrk23'.
I check the source code, the right argument is 'spark23'.
Fix typo and make examples run.
No, it's just a typo, not affect the source code.

Fix typo in /README.md and /python/README.md

---

src/main/scala/com/johnsnowlabs/nlp/functions.scala
src/test/scala/com/johnsnowlabs/nlp/FunctionsTestSpec.scala

FIx to compile and execute functions utilities in Spark 3 TF 2 branch
Untyped UDF is no more allowed in new Scala version so we have to fix functions utilities methods signature to be compliant.
Making UDF untyped fixes the issue.
Full non-regression tests are green for both Scala 2.11 and 2.12 .

Fixing functions utilities making udf untyped

---

src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcherUtils.scala

Some pattern matchings in `DateMatcherUtil` don't have the catch any option and may fail to match a correct case. This PR addresses this issue.

Add catch all to case matchers

---

python/sparknlp/base.py
src/main/scala/com/johnsnowlabs/nlp/Finisher.scala
src/test/scala/com/johnsnowlabs/nlp/FinisherTestSpec.scala

Add default parameters for the splitters in finisher (output as array)
https://github.com/JohnSnowLabs/spark-nlp/issues/808

bug fix for setOutputAsArray(false), add default parameters

---

.github/workflows/build_and_test.yml
.gitignore
build.sbt
project/build.properties
project/plugins.sbt
python/sparknlp/__init__.py
src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserModelTestSpec.scala

Starting the Spark NLP 3.0.0 release the default Spark NLP packages will be based on Apache Spark 3.0.x and Scala 2.12. This means the following packages will be by default Apache Spark 3.0.x/Scala 2.12:
- `spark-nlp`
- `spark-nlp-gpu`
For Apache Spark 2.3.x and Apache Spark 2.4.x:
- `spark-nlp-spark23`
- `spark-nlp-spark24`
- `spark-nlp-gpu-spark23`
- `spark-nlp-gpu-spark24`
Spark NLP start functions in Python and Scala are also updated for these changes.

Make Spark NLP on Apache Spark 3.0 a default package

---

build.sbt

This PR will shade `hadoop-aws` and `aws-java-sdk` for outside of Spark NLP. Since Hadoop AWS and AWS Java SDK are presented in the classpath in EMR, we don't need to provide them. We only use these two within Spark NLP from now on.

Shading Hadoop AWS and AWS Java SDK for better EMR intgration

---

src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingBehaviors.scala

Error handler for NorvigSweetingApproach chaged in new Spark 3.1.1 version
The returned exception is now at catalyst level (AnalysisException).
Exception handling changed.
All non-reg tests run successfully locally.

Added error message handler at catalyst level in NorvigSweetingApproach

---

src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingBehaviors.scala

Norvig Sweeter Approach test spec handle the exception differently when a dataset without array annotation is provided across Spark 2.x and 3.1.x versions.
Added a flow to handle both Spark 2.x and 3.x versions.
Spark 3.1.x moved this exception handler to catalyst level.
Non regression locally.

Added Spark cross version exception handler in Norvig Approach

---

build.sbt

I shade the com.amazonaws. llibrary because in the spark-nlp-internal was a compilation error because that libary was a conflict.
I create a new rule in build sbt to shade in a proper way the com.amazonaws. 
The new version of spark-nlp library doesnt work in spark-nlp-jsl because the are a conflict in the com.amazonaws libary y fix that using a new shade rule.
This change was tested manually on spark-nlp-jsl using the jar with the new change.

fix shadding package

---

python/run-tests.py
python/sparknlp/annotator.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/annotators/Normalizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/NormalizerModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala

Tokenizer has the ability to filter tokens by min and max lengths. However, Normalizer can break those tokens into other tokens which require to have independent min and max length params to control it.

Add minLength and maxLength params to Normalizer

---

build.sbt

- the .shaded sub domain caused some issue with other projects trig to extend spark-nlp via Fat JAR that has the shade rule
- this won't change anything if the library extends spark-nlp via Maven artifacts since the Maven doesn't have shading
This fixes other libraries to extend spark-nlp internal functionality via Fat JARs without issue with sharing

Adjust shading rule for amazonaws

---

src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/parser/SpecialTokensParser.scala

Scala/Java conversions that were used previously only worked with Scala 2.11.x. These changes enable using the same conversion code for 2.11/2.12.

added proper conversions for Scala 2.11/2.12

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/NerDatasetEncoder.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/common/Tagged.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/common/TaggedSentence.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/common/TaggedWord.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
src/test/scala/com/johnsnowlabs/nlp/SparkAccessor.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproachTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfCustomCase.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala

Currently, both `NerDLModel` and `NerCrfModel` only provide a confidence score for the predicted tag like the following:
```
[[named_entity, 0, 4, B-LOC, [word -> Japan, confidence -> 0.9998], []]
```
This PR introduces a full list of confidence scores with all the available tags in that model when `setIncludeConfidence` is set to `true` like the following:
```
[[named_entity, 0, 4, B-LOC, [B-LOC -> 0.9998, I-ORG -> 0.0, I-MISC -> 0.0, I-LOC -> 0.0, I-PER -> 0.0, B-MISC -> 0.0, B-ORG -> 1.0E-4, word -> Japan, O -> 0.0, B-PER -> 0.0], []]
```

Provide confidence scores for all available tags in NerDLModel and NerCrfModel

---

src/main/scala/com/johnsnowlabs/nlp/annotators/common/Tagged.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverter.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverterTest.scala

This PR introduces an average of confidence scores for predicted tags as entities. It also makes sure the sentences/documents have valid tokens to avoid exceptions when chunks don't belong to a sentence/document.
Example of metadata in NerConverter when `setIncludeConfidence` is set to `true`:
```
[chunk, 30, 37, john, [entity -> PERSON, sentence -> 0, chunk -> 0, confidence -> 0.44035]
```

Add confidence score to NerConverter metadata and fix a bug for dirty documents

---

docs/_posts/HashamUlHaq/2021-03-31-ner_radiology_en.md
docs/_posts/aydinmyilmaz/2021-01-18-ner_radiology_en.md
docs/_posts/aydinmyilmaz/2021-01-18-re_bodypart_directions_en.md
docs/_posts/aydinmyilmaz/2021-01-18-re_bodypart_problem_en.md
docs/_posts/aydinmyilmaz/2021-01-18-re_bodypart_proceduretest_en.md
docs/_posts/aydinmyilmaz/2021-01-18-re_date_clinical_en.md
docs/_posts/aydinmyilmaz/2021-01-20-ner_deid_augmented_en.md
docs/_posts/aydinmyilmaz/2021-01-27-ner_clinical_en.md
docs/_posts/aydinmyilmaz/2021-01-28-deidentify_dl_en.md

-     2021-01-18-ner_radiology_en.md
-     2021-03-31-ner_radiology_en
-     2021-01-18-re_bodypart_directions_en.md
-     2021-01-18-re_bodypart_problem_en.md
-     2021-01-18-re_bodypart_proceduretest_en.md
-     2021-01-18-re_date_clinical_en.md
-     2021-01-20-ner_deid_augmented_en.md
-     2021-03-31-ner_deid_augmented_en
-     2021-01-27-ner_clinical_en.md
-     2021-01-28-deidentify_dl_en.md

added scala example code to licensed models

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddings.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddingsTestSpec.scala

In some cases when the length of the sentences is longer than available word embedding, we end up with Chunks without any embedding to match. This is due to max sequence limitation in some word embedding such as BERT, ALBERT, ELMO, XLNet, etc. 
This PR fixes the `Array out of bounds` exception by making sure the chunks have corresponding word embeddings.

Fix ChunkEmbeddings Array out of bounds exception

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/DistilBertEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaEmbeddings.scala

This PR introduces a new annotator for RoBertaEmbeddings based on RoBERTa models (for instance [roberta-base](https://huggingface.co/transformers/model_doc/roberta.html)). 
Import the following models:

Introducing RoBertaEmbeddings annotator based on RoBERTa models

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMarian.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSerializeModel.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/sign/ModelSignatureConstants.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/sign/ModelSignatureManager.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/DistilBertEmbeddings.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddingsTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddingsTestSpec.scala

- In this PR MarianTransformer will only support models exported in TensorFlow v2 architecture with the support of ModelSignatureConstants. This change helps to take advantage of new optimizations in TensorFlow 2.x and also made the process of exporting and maintaining the code easier for the team
- Some improvements were done in ModelSignatureConstants to preserve `saveDef` required values in signature for saving/restoring of TF v2 models.
**WARNING:** Due to this change, the previous models (online/offline) will not work. Around 640+ models/pipelines must be exported and uploaded again for the upcoming Spark NLP 3.1.0 release.

Migrate MarianTransformer to TensorFlow v2 architecture and improve ModelSignatureConstants

---

src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcherUtils.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTestSpec.scala

There is a bug in DateMatcher when try to recognize the followings values `day after tomorrow` and `day before yesterday`
There is a bug in DateMatcher when try to recognize the followings values `day after tomorrow` and `day before yesterday`

fix datematecher utils for relatives dates

---

python/sparknlp/training.py
src/main/scala/com/johnsnowlabs/nlp/training/PubTator.scala
src/test/resources/corpus_pubtator_not_padding.txt
src/test/scala/com/johnsnowlabs/nlp/util/PubTatorTestSpec.scala

The Pubtutor class doesn't work in python
We need to use a case class instead of an object.The Pubtotor python class cannot load the object from scala.
We also add a parameter to allow work with Pubtator files that don't have codes with paddings.

python pubtator fix

---

scripts/colab_setup.sh

Downgraded  Pyspark to 3.0.2  and Spark NLP to 3.1.0 because of compatibility issues for some pretrained pipelines in the training workshop certification notebooks.
To reproduce issues, run [this notebook](https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/1.SparkNLP_Basics.ipynb) with old default versions
```
SPARKNLP="3.1.1"
PYSPARK="3.0.3"
```

updated script for colab

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlmRoberta.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/SentencepieceEncoder.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddings.scala

Prior to this PR, the special tokens inside XlmRobertaEmbeddings were had-coded based on their actual values taken from the SentencePiece model. This PR uses the `pieceToId` function to access the values dynamically to allow support for custom SP models with different special token ids.

Dynamically extract special tokens ids from SP models in XlmRobertaEmbeddings

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/NerDatasetEncoder.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/common/Tagged.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverterTest.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala

This param allows outputting only the confidence score for the predicted label instead of all labels. In some cases with lots of NER tags, this param helps to improve the speed. (by default it's set to false)

Add includeAllConfidenceScores param to NerDLModel and NerDLApproach

---

docs/en/annotator_entries/ContextSpellChecker.md
python/sparknlp/annotator.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcher.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/btm/BigTextMatcher.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/btm/BigTextMatcherModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ws/WordSegmenterApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ws/WordSegmenterModel.scala
src/test/scala/com/johnsnowlabs/benchmarks/annotators/ws/WordSegmenterBenchmark.scala
src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
src/test/scala/com/johnsnowlabs/nlp/LightPipelineTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/WordSegmenterTest.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/SpellCheckerUseCase.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala

Hi @DevinTDHa 
- ContextSpellCheckerApproach, yes, the variables are the same in both but the setters and getters are different! I'll match the Scala with Python
- `WordSegmenterApproach`, `setPosCol` is for both Scala and Python. However, `setNIterations` is being synced for both Python and Scala
- `ViveknSentimentApproach` now has `setPruneCorpus` synced between both Scala and Python
- 'RegexMatcher' now has `setExternalRules` in both Scala and Python
- `PerceptronApproach` now has `setPosColumn` in both Scala and Python
- `ContextSpellCheckerApproach` has synced parameters between Python and Scala

Synchronize Scala and Python parameters' names

---

README.md

Another small typo fix: it appears that the code block end "```" are missing between two code blocks so the two have been merged into one.

Add missing code block end

---

src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModelTestSpec.scala

Fixes #5701. SymmetricDeleteModel was dividing by 0, because of `normalizeFrequencyValue`. The value is set to `1`, if `$(maxFrequency)` and  `$(minFrequency)` are the same.
Added new test and ran all the old tests. Tests are passing.

Resolve Issue #5701  With SymmetricDeleteModel

---

docs/_posts/muhammetsnts/2021-06-15-sbertresolve_snomed_bodyStructure_med_en.md
docs/en/annotator_entries/RegexMatcher.md
src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcher.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala

This PR adds the missing `signatures` required to access the correct inputs/output in TF SavedModel 2.x.

Fix the issue with BertSentenceEmbeddings model in TF v2

---

python/docs/Makefile
python/docs/README.md

This ensures the pydoc will be available under spark-nlp/docs/api/python

PyDoc: Move generated HTML to api folder

---

python/sparknlp/annotator.py
python/sparknlp/internal.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBertTokenClassification.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowDistilBertTokenClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForTokenClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForTokenClassification.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForTokenClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForTokenClassificationTestSpec.scala

This PR allows the use of models trained/saved in HF for `DistilBertForTokenClassification` in Spark NLP

Introducing DistilBertForTokenClassification annotator

---

python/sparknlp/__init__.py

This PR fixes the wrong return version when `sparknlp.version()` is used in Python. This is not affecting any functionality, however, it is important to return a correct version when users need to make sure they have upgraded `spark-nlp`.

Fix wrong version return in sparknlp.version()

---

python/docs/Makefile
python/docs/move_folders_for_gh.sh
python/docs/user_guide/training.rst
python/sparknlp/annotator.py
python/sparknlp/base.py
python/sparknlp/common.py
python/sparknlp/training.py
src/main/scala/com/johnsnowlabs/nlp/Chunk2Doc.scala
src/main/scala/com/johnsnowlabs/nlp/Doc2Chunk.scala
src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
src/main/scala/com/johnsnowlabs/nlp/Finisher.scala
src/main/scala/com/johnsnowlabs/nlp/TokenAssembler.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/Chunker.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcher.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcher.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/keyword.yake/YakeModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyParserModel.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoder.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
src/main/scala/com/johnsnowlabs/nlp/training/CoNLLU.scala
src/main/scala/com/johnsnowlabs/nlp/training/PubTator.scala

This PR continues to create a PyDoc documentation for the Python Spark NLP package in the [numpydoc style](https://numpydoc.readthedocs.io/en/latest/format.html).
The PR also includes some minor fixes for the scala doc and other documentation related sources.
Improves usability for the python package, especially with showing doc strings for functions in notebooks.
No changes to functionality, Tests have been re run

Pydoc Update

---

python/sparknlp/training.py
src/main/scala/com/johnsnowlabs/nlp/training/CoNLL.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddingsTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/DistilBertEmbeddingsTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/ElmoEmbeddingsTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsTestSpec.scala

This PR introduces a `delimiter` param to CoNLL() in both Scala and Python. Usually, the delimiter in the CoNLL file is whitespace `' '`, however, some CoNLL files may use a different delimiter like tab `\t` etc. From now on the delimiter can be set during reading the CoNLL file:
```python
CoNLL(conllLabelIndex=1, delimiter='\t') \
.readDataset(spark, 'train.conll')
```

Add delimiter feature to CoNLL class

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaEmbeddings.scala

This PR makes sure a bad input inside the merges.txt won't result in an exception during the use of `.loadSavedModel` function. if for any reason the delimiter in the merges.txt file is not a whitespace, it will discard that row.

Avoid exceptions due to corrupt merges in RoBERTa tokenizer 

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/common/SentenceSplit.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddingsTestSpec.scala

This PR extends the Sentence case class with metadata to be used when necessary to preserve metadata generated by previous annotators.

Preserve existing metadata in BertSentenceEmbeddings

---

python/sparknlp/annotator.py

This PR fixes the wrong default language for `sent_xlm_roberta_base` model used in `XlmRoBertaSentenceEmbeddings.pretrained()` which should be `xx` and not `en`.

Fix default language for XlmRoBertaSentenceEmbeddings pretrained model

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/AnnotatorType.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/keyword.yake/YakeModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/keyword.yake/YakeParams.scala

In order to have more available features after the YakeModel annotator such as Chunk2Doc or ChunkEmbeddings, I have changed the output type from KEYWORD to CHUNK.

Change KEYWORD to CHUNK output type in YakeModel

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/LongformerEmbeddings.scala

This PR makes sure a bad input inside the merges.txt won't result in an exception during the use of the `.loadSavedModel` function. if for any reason the delimiter in the merges.txt file is not a whitespace, it will discard that row.

Avoid exceptions due to corrupt merges in Longformer tokenizer

---

src/main/scala/com/johnsnowlabs/util/Benchmark.scala
src/main/scala/com/johnsnowlabs/util/CoNLLGenerator.scala
src/main/scala/com/johnsnowlabs/util/ConfigLoader.scala
src/main/scala/com/johnsnowlabs/util/FileHelper.scala
src/main/scala/com/johnsnowlabs/util/PipelineModels.scala
src/main/scala/com/johnsnowlabs/util/TrainingHelper.scala
src/main/scala/com/johnsnowlabs/util/Version.scala
src/main/scala/com/johnsnowlabs/util/ZipArchiveUtil.scala
src/main/scala/com/johnsnowlabs/util/spark/MapAccumulator.scala

This PR refactors the way Spark NLP annotators based on TensorFlow are being saved. The performance gain with the new refactoring is between 50x to 60x times faster.
Example: Saving XlmRoBertaEmbeddings `large` model takes around 20 minutes, with the new refactorings it will take up to 20 seconds!

Saving Spark NLP models 50x-60x times

---

docs/_posts/HashamUlHaq/2021-04-02-chunkresolve_loinc_clinical_en.md

Fixes a wrong pipeline var name (rxnorm) by the correct one (loinc)
In the fit() execution line, the name of the variable representing the pipeline (pipeline_rxnorm) is the corrected to (pipeline_loinc)
This change is required because executing the python code was raising an error, since pipeline_rxnorm is not declared.
Executing the snipped in SparkNLP raises the issue. But applying this commit the issue gets fixed.

Fixing var name in chunkresolve_loinc_clinical_en

---

src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala

This PR makes sure EntityRulerApproach has the same name from `import com.johnsnowlabs.nlp.annotator._`. It also adds `EntityRulerModel` to ResourceDownloader for future pretrained models.

Fix EntityRulerApproach name from import and add the model to ResourceDownloader

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala

This PR fixes a bug that was introduced in Spark NLP 3.1.2 that doesn't pass batchSize param value to the predict function. Therefore, the value of batchSize stayed always at 8. Although, batchSize of 8 can be fine for CPU, is very low for GPU. This resulted in bad performance when NerDLModel was used on GPU after Spark NLP 3.1.2 releases.

Fix a bug in NerDLModel that degrades GPU performance

---

docs/_posts/muhammetsnts/2021-06-01-redl_date_clinical_biobert_en.md

Updated redl_date_clinical_biobert_en pipeline.
Wrong pipeline example was uploaded previously.
It fixes the issue [#734](https://github.com/JohnSnowLabs/streamlit-demo-apps/issues/734)

Updated 2021-06-01-redl_date_clinical_biobert_en.md

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/Logging.scala
src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala

Modifies naming convention to save the logs on disk for training annotators (e.g NerDLApproach, ClassifierDL, etc)
The current naming format is: `annotator_uid.log`
This change will make the format: `annotator_uid_timestamp.log`
An example for NerDLApproach: `NerDL_bfab02716caf_1636467507.log`
When there are many classifiers trained, it is difficult to match the name of log files. By adding the timestamp, it would be easier to identify and match log files with trained models.

Adding timestamp in logging file's name

---

scripts/sagemaker_setup.sh

New script for automatically setting up Spark and Spark NLP on AWS SageMaker, in the same fashion as the Google Colab and Kaggle ones.
The goal is to make it easier to use Spark NLP along with the good Spark version on AWS SageMaker with a single curl bash command.
I have tested it on SageMaker, and I get the good PySpark version (which is different from the one which is already installed).

feature: script for setting up spark and spark nlp on a sagemaker kernel

---

docs/_posts/muhammetsnts/2021-06-01-redl_date_clinical_biobert_en.md
docs/en/install.md
docs/en/licensed_install.md

installation docs are updated amazon linux 2 for both open source and healthcare.

amazon linux 2 installation

---

src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala

This PR adds support for labels with Long type when training ClassifierDLApproach and SentimentDLApproach annotators.

Add support to labels as LongType in ClassifierDL and SentimentDL

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMarian.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformerTestSpec.scala

This PR fixes the following issues in MarianTransformer
- Makes sure the max sequence is 512 even when we add `eos` or sometimes `langId` tokens. It should take the extra token ids into account to not exceed 512 which the MAX_LENGTH of MarianMT models
- Filter empty annotations to avoid exception - the previous filter on `.result` was not a good choice, we should filter on the actual Annotation to filter empty Annotations

Fix MarianTransformer crashing on both empty sequence  or longer than 512

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala

This is an optimization of batch processing in BertSentenceEmbeddings and BertEmbeddings model which improves performance of single machine setups where there are few/single sentence per row.
The HasBatchedAnnotate trait lets models process several rows at once. The idea is to enable batching annotations across rows which can significantly speed up processing, especially on GPU hardware. However, the current implementation of batchAnnotate method in BertSentenceEmbeddings and BertEmbeddings doesn't actually allows this as they process rows one by one therefore and can therefore batch only annotations within a single row.  This PR solves the problem by adding all annotations which are passed to batchAnnotate, regardless of which row they belong to, to a single collection and then passing …

Optimized batch processing for Bert sentence and word embeddings

---

python/sparknlp/training.py
src/main/scala/com/johnsnowlabs/nlp/training/CoNLL.scala

This change adds a new capability to the CoNLL reader, allowing it to read multiple CoNLL files at the same time into a single Dataframe. Example,
```
df = CoNLL().readDataset(spark, './path/to/conlls/*', partitions=12)
```
The difference with previous behavior is the path ending in an `*`. The original mechanism continues to work as before.
Two additional params that work only for the multi file situation,
partitions : minimum number of partitions used to create the Dataframe. Defaults to 8.
storage_level : pyspark.StorageLevel for the Dataframe. Defaults to pyspark.StorageLevel.DISK_ONLY.

Optimized Conll Reader

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForSequenceClassification.scala

This PR fixes the issue when loading models in DistilBertForSequenceClassification annotator and it fails due to a wrong name.

Fix the wrong name for DistilBertForSequenceClassification in Python

---

python/run-tests.py
python/sparknlp/annotator.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForTokenClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForTokenClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForTokenClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/LongformerForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/LongformerForTokenClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForTokenClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForTokenClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlnetForTokenClassification.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForSequenceClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForTokenClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForSequenceClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForTokenClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForSequenceClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForTokenClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/LongformerForSequenceClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/LongformerForTokenClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForSequenceClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForTokenClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForSequenceClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForTokenClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlnetForTokenClassificationTestSpec.scala

This PR introduces a new `.getClasses` function to retrieve labels that model was trained on to all `ForTokenClassification` and `ForSequenceClassification` annotators:
- AlbertForTokenClassification
- XlnetForTokenClassification
- BertForTokenClassification
- DistilBertForTokenClassification
- RoBertaForTokenClassification
- XlmRoBertaForTokenClassification
- LongformerForTokenClassification
- AlbertForSequenceClassification
- XlnetForSequenceClassification
- BertForSequenceClassification
- DistilBertForSequenceClassification
- RoBertaForSequenceClassification
- XlmRoBertaForSequenceClassification
- LongformerForSequenceClassification

Add new getClasses function to retrieve labels from pretrained models

---

build.sbt
python/setup.py
python/sparknlp/annotator.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/GPT2Transformer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5Transformer.scala
src/main/scala/com/johnsnowlabs/util/Build.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/GPT2TestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5TestSpec.scala

Add HasBatchAnnotate trait to T5 and GPT2. Batch processing will only work for clusters.
I've removed the HasSimpleAnnotate trait from T5 and GPT2 and implemented HasBatchAnnotate. The batch size parameter is added to the python wrapping. 
Note that batch processing will not make any difference on a single machine with a GPU. This is because the documents are currently processed one by one within a single process. The only to speed up processing by using batches is if you have multiple concurrent processes running on the same device (i.e. a GPU) - our experience so far suggests this only happens when Spark runs in a cluster.
I've also checked MarianMT transformer. It already implements HasBatchAnnotate and supports batch processing with batchSize > 1. So the only case in which MarianMT …

Enable batch processing for GPT2 and T5

---

build.sbt
python/setup.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/GPT2Transformer.scala
src/main/scala/com/johnsnowlabs/util/Build.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/GPT2TestSpec.scala

GPT2 tests updated to use the pretrained models uploaded to the repo. I also updated the sparknlp version to be able to download the models.
This was needed because the tests referred to local copies of the model
I've re-run the Scala and Python gpt2 tests.
- [x ] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

GPT2 tests updated

---

.github/workflows/create_search_index.yml

Fixes issue [NMH-55](https://johnsnowlabs.atlassian.net/browse/NMH-55)
- When merges are directly pushed to the master branch (without pull requests), only the last commit will trigger the github action `create_search_index.yml`. This fix will index all the changes to the post made since the last commit to the master branch.

BUGFIX-NMH55: Fix all commits dont trigger github action when merged [skip test]

---

python/sparknlp/annotator.py

This PR fixes the wrong type of `configProtoBytes` param on the Python side.

Fix configProtoBytes param type in Python

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala

In order to use bestModel, we need the actual weights rather than the reference to a TF session.

Preserve the actual trained weights from NerDLApproach

---

src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5Transformer.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5TestSpec.scala

Currently, if a pretrained T5 model has the task already set during saving to disk, then it is not possible to change the task when the model is loaded again. This PR changes this behaviour the redefine the task.
Current tests are passing and A new test was been added to validate the behaviour.

Allow T5 models to change task

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala

If Java serialization is not set to Kyro or sometimes for a random reason user may get `NullPointerException` in TensorflowWrapper when we use `Session` as Optional.

Revert back to none optional session for more reliable serializations

---

src/main/scala/com/johnsnowlabs/nlp/annotators/RecursiveTokenizerModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala

This PR fixes an issue when there is a `RecursiveTokenizer` annotator inside a saved PipelineModel. Previously, a saved PipelineModel with `RecursiveTokenizer` couldn't be loaded back. Now it can be saved and loaded back without any problem.

Fix RecursiveTokenizerModel not being readable in a saved Pipeline

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala

This PR introduces a new param to NerDLApproach `bestModelMetric` to set to either `f1_micro` or `f1_macro`. This will be the metric to keep track of during the training when `useBestModel` is set to `true`. (by default it will be `f1_micro`)

Add bestModelMetric param to choose between Micro-average or Macro-average for best model

---

src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala

The contextSpellcheker return wrong order when we use a sentence detector.
I create a test to return the correct order.

fix tokens order based in ContextSpellCheckerModel when there are sentences

---

.github/workflows/build_and_test.yml
python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerModel.scala
src/main/scala/com/johnsnowlabs/util/spark/SparkUtil.scala
src/test/resources/entity-ruler/patterns.csv
src/test/resources/entity-ruler/patterns.json
src/test/resources/entity-ruler/patterns.jsonl
src/test/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerTest.scala
src/test/scala/com/johnsnowlabs/util/JsonParserTest.scala
src/test/scala/com/johnsnowlabs/util/ResourceHelperTestSpec.scala

Adding `sentenceMatch` parameter to allow finding matches at the sentence level.
There are scenarios that require multi-token matches. Since this annotator finds matches at the token level it was not possible. 
By adding `sentenceMatch` parameter (set to true), the annotator allows finding a match at the sentence level, which will allow matching words with spaces. 
Adding unit test to the test suite

Adding sentence match parameter to EntityRuler

---

docs/_posts/josejuanmartinez/2021-11-01-roberta_base_biomedical_es.md
docs/_posts/josejuanmartinez/2021-11-03-robertaresolve_snomed_es.md
docs/_posts/josejuanmartinez/2021-11-04-bert_sequence_classifier_question_statement_en.md
docs/_posts/josejuanmartinez/2021-11-04-roberta_ner_diag_proc_es.md
docs/_posts/josejuanmartinez/2021-11-05-bert_sequence_classifier_question_statement_clinical_en.md
docs/_posts/josejuanmartinez/2022-01-04-electra_medal_acronym_en.md

Adds several "new" missing for non-class methods in Scala.
When instantiating a class, we need to use `new` in Scala. This does not apply to pretrained(), because it's a class method.
There were some missing news that preventing the code to run properly due to missing `new` reserved word.

Scala fixes

---

src/main/scala/com/johnsnowlabs/nlp/annotators/GraphExtraction.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/GraphExtractionTest.scala

This PR fixes an exception that happens during the following scenario:
- One of the inputCols in GraphExtraction is `document` instead of `sentence`
- `.fullAnnotate` is used from `LightPipeline`
Then it crashes due to not having a `sentence` index inside metadata coming from `.fullAnnotate`

Fix GraphExtraction crashing when fullAnnotate and document are used at the same time

---

src/main/scala/com/johnsnowlabs/nlp/annotator.scala

This PR fixes casting Word2VecModel to Doc2VecModel by mistake in annotator object.

Fix Word2VecModel being cast to Doc2VecModel by mistake

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala

In Spark NLP 3.3.3 release we introduced a bug that uses a rowIndex for sentence's index rather than preserving an already existing sentence's index in metadata. This PR fixes this bug.

Fix broken BertEmbeddings wrong sentence indexing

---

python/run-tests.py
python/sparknlp/annotator.py
python/test/annotators.py
src/test/resources/token_exception_list.txt
src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala

This PR fixes the wrong type of exceptionsPath param and add a setter to Tokenizer in Python APIs.

Fix broken setExceptionsPath in Tokenizer in Python

---

docs/_plugins/search_index.rb

Fix for Jira Ticket [NMH-68](https://johnsnowlabs.atlassian.net/browse/NMH-68)
Models hub does not provide relevant search results on model name

NMH-58: Simple analyzer for model name [skip-test]

---

docs/_frontend/src/models/Sidebar/Sidebar.js
docs/_frontend/src/models/Sidebar/Sidebar.module.css
docs/_plugins/search_index.rb

Sorting models by downloads UI
This commit will add UI for sorting models by their downloads count 
- New feature

Feature NMH-65: Collect and use statistics on downloads of model

---

python/sparknlp/annotator.py
python/sparknlp/common.py
python/test/annotators.py
src/main/scala/com/johnsnowlabs/nlp/HasEnableCachingProperties.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/Doc2VecApproach.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/Word2VecApproach.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/Doc2VecTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/Word2VecTestSpec.scala

This PR introduces a new param `enableCaching` in Doc2VecApproach and Word2VecApproach which if enabled speeds up the training.

Introducing enableCaching param in Doc2Vec and Word2Vec trainable annotators

---

python/sparknlp/annotator.py
python/sparknlp/internal.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowDeBerta.scala
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/DeBertaEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/DeBertaEmbeddingsTestSpec.scala

This PR introduces `DeBertaEmbeddings` for DeBERTa v2 and v3 models using the `SentencePiece` model for tokenization. 
```python
embeddings = DeBertaEmbeddings\
.pretrained()\
.setInputCols(["token", "sentence"])\
.setOutputCol("embeddings")\
.setCaseSensitive(True)\
.setMaxSentenceLength(512)\
.setBatchSize(16)
```

Introducing DeBERTa annotator

---

python/sparknlp/internal.py
python/sparknlp/pretrained.py
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/pretrained/MockResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderMetaSpec.scala

Add a method to download a specific model from s3.
We going to use the code as following
```python
ResourceDownloader.downloadModelDirectly("public/models/bert_base_cased_es_3.2.2_3.0_1630999631885.zip","clininal/models")
```

Add a new functionality to download and extract models from S3 via direct link

---

src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala

The current Tokenizer implementation has performance issues if a large number of exceptions are used. 
For example:
When tokenizing `src/test/resources/spell/sherlockholmes.txt`, on my machine it will take an average of 0.58 seconds for 20 iterations. If there are 100 exceptions, it will take on average 3.17 seconds, for 200 it will jump to 5.8 seconds. The following benchmark was used for testing: [TokenizerTestSpec](https://github.com/DevinTDHa/spark-nlp/blob/c2506ceb90ee33998e02449b9f6f623523972092/src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala#L665)
There is double the compilations of regular expressions and a severe performance drop. 
The issue lies with how the exceptions are checked. 
1. Regex are compiled for each sentence that is tagged. This can be done …

Tokenizer: Optimized tokenization with exceptions

---

python/sparknlp/annotator.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowUSE.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoder.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoderTestSpec.scala

This PR migrate UniversalSentenceEncoder from single-row UDF to BatchAnnotate via mapPartition to feed more rows/sentences at once to improve performance, especially on GPU devices.
The GPU utilization varies depending on the size and complexity of the model. For instance, the `tfhub_use` is not computational enough to go beyond 20%-30%, however, it will be faster or equal to the CPU with this PR unlike previously when the GPU performed slower. On the other hand, the `tfhub_use_lg` model is computationally more expensive so the GPU utilization is around 90% and more depending on the batchSize, number of partitions, and how many sentences are in 1 document. This model also was slower on GPU prior to the 3.4.4 release under extreme circumstances like having only 1 sentence per row. With …

Add support for BatchAnnotate to UniversalSentenceEncoder

---

docs/_frontend/src/models/FilterForm/FilterForm.js
docs/_plugins/search_index.rb

Jira Ticket [NMH-74](https://johnsnowlabs.atlassian.net/browse/NMH-74)
- Add Spark OCR in filter fields.
- Modify search_index script to consider Spark OCR Versions

FEATURE NMH-74: Integrate spark ocr version in editions

---

build.sbt
project/Dependencies.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceMetadata.scala
src/main/scala/com/johnsnowlabs/util/TrainingHelper.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherMultiLanguageTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderMetaSpec.scala
src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderSpec.scala

Removes `json4s-ext` dependency used in ResourceMetadata to serialze/deserialize enumerate types
`json4s-ext` dependency forces us to publish/release spark-nlp and spark-nlp-spark32. By removing it, we only need to publish/release 1 package for spark-nlp and 1 for spark-nlp-gpu
Scale unit tests
We need to test it thoroughly when merged with 4.0.0

Removing json4s-ext dependency

---

.github/workflows/build_and_test.yml
project/Dependencies.scala
project/plugins.sbt
src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerUtil.scala
src/test/scala/com/johnsnowlabs/nlp/AssertAnnotations.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerUtilTest.scala

This PR updates the Scala from 2.12.10 to 2.12.15 to make the transition to Scala 3.x later on easier. (there are also many enhancements, bug fixes, etc. in the releases after 2.12.10)

Migrate to Scala 2.12.15

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlmRoberta.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/DeBertaEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/DistilBertEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/LongformerEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddings.scala

The transformer-based word embedding models benefit massively from being computed on GPU devices (locally and in a cluster). However, there is one use case (worst-case scenario) where there is 1 sentence per row. In this scenario, the local GPU device suffers a big performance drawback compared to cluster mode or multiple sentences per row.
This PR follows the work that was done for BERT (word and sentence embeddings) annotators here which improves utilizing GPU device locally for the following model architecture: https://github.com/JohnSnowLabs/spark-nlp/pull/6462
Done previously:

Optimizing batch processing for transformer-based Word Embeddings on GPU

---

src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/Gpt2Tokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/XlmTokenizer.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizerBehaviours.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/Gpt2TokenizerTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizerTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/XlmTokenizerTestSpec.scala

This PR adds a flag for the BpeTokenizer, so that not always a space is prepended to the input.
- added new flag whether to add a space to the initial input sentence
- slight improvement to test structure
Added new test to reflect the change and other tests for BpeTokenizers are passing.

BpeTokenizer: add flag for "AddPrefixSpace"

---

docs/en/transformer_entries/AlbertForQuestionAnswering.md
docs/en/transformer_entries/BertForQuestionAnswering.md
docs/en/transformer_entries/DeBertaForQuestionAnswering.md
docs/en/transformer_entries/DistilBertForQuestionAnswering.md
docs/en/transformer_entries/LongformerForQuestionAnswering.md
docs/en/transformer_entries/RoBertaForQuestionAnswering.md
docs/en/transformer_entries/XlmRoBertaForQuestionAnswering.md

Fixed docs for transformer question answering annotators 
All questions Answer Transformers use
```
documentAssembler = MultiDocumentAssembler() \
.setInputCols(["question", "context"]) \
.setOutputCols(["document_question", "document_context"])
```
But the docs are wrong and say
```
documentAssembler = MultiDocumentAssembler() \
.setInputCols(["question", "context"]) \
.setOutputCol(["document_question", "document_context"])
```

fixed docs for transformers question answering annotaters

---

python/sparknlp/annotator/sentence/sentence_detector.py
python/test/annotator/sentence/pragmatic_test.py
src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/SentenceDetectorParams.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticMethod.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetectorBoundsSpec.scala

Currently, if users provide custom bounds to the SentenceDetector, they will not be returned at all. This PR adds a flag which will enable returning the custom bounds with separate sentences. There are also different sentence break policies which the user can choose from (either prepend or append the sentence break)
with `setCustomBounds([r"\.", ";"])`
```
This is a sentence. This one uses custom bounds; As is this one;
```
Without the flags will result in 
```python
["This is a sentence", "This one uses custom bounds", "As is this one"]
```
With the new flag:
```python
.setCustomBounds([r"\.", ";"])
.setCustomBoundsStrategy("append")
```
the result will be
```python
["This is a sentence.", "This one uses custom bounds;", "As is this one;"]
```
Similarly with prepend:
```
1. This is a …
```

[SentenceDetector] Added Flag for returning custom bounds

---

src/main/scala/com/johnsnowlabs/nlp/annotators/GraphExtraction.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/PretrainedAnnotations.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/GraphExtractionTest.scala

Refactoring `PretrainedAnnotations` object to instantiate classes in driver
GraphExctraction is forcing to create spark session on executors when setting setMergeEntities=true in Spark > 3.0.
The error raised is: 
`Caused by: java.lang.IllegalStateException: SparkSession should only be created and accessed on the driver.`
- Unit tests
- Google Colab Notebooks
- Databricks Notebooks

Fix bug that attempts to create spark session on executors

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowForClassification.scala

This PR allows all XXXForTokenClassification annotators to pass confidence scores to NerConverter annotator for post-filtering entities by their final probabilities.

Allow passing confidence scores from all XXXForTokenClassification annotators to NerConverter

---

src/main/scala/com/johnsnowlabs/storage/RocksDBConnection.scala

This PR adds an additional error message for RocksDBConnection based annotators if no shared filesystem is used for clusters. 
Specifically, this mentions the case of Kubernetes clusters and recommends using the `setEnableInMemoryStorage` parameter.
BytesKey error still persists.
Tested with a WordEmbeddings pipeline on a local K8s cluster with 5 executors.

RocksDBConnection: Add error message mentioning K8s clusters

---

python/sparknlp/training/_tf_graph_builders/ner_dl/create_graph.py
python/sparknlp/training/_tf_graph_builders/ner_dl/ner_model.py

When TFGraphBuilder is used with TF2 to generate NerDL graphs, the resulting graphs raise an exception when the sequence length is 1. This commit fixes the problem.
The problem is that the NerDL graph builder calls tf.compat.v1.disable_v2_behavior(). One of the side effects if this function is that the tensor shapes are represented in TF 1 style. Part of the NerDL graph uses a function called crf_decode from tf_addons which checks the shape of the tensors and generates different graphs depending on whether the input is static or dynamic. When the tensor shapes are in TF1 style, the function fails to detect that their shape is dynamic and generates a static graph which only works for sequences of size >1.
The problem is fixed by calling  tf.compat.v1.enable_v2_tensorshape() after …

Fix bug in generating NER TF2 graphs when sequence length is 1

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbert.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowCamemBert.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowDeBerta.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowDistilBert.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowElmo.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowRoBerta.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlmRoberta.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlnet.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/CamemBertEmbeddingsTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/DeBertaEmbeddingsTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddingsTestSpec.scala

In 4.0.0 the following annotators were migrated to BatchAnnotate to improve their performance, especially on GPU. However, a bug was introduced in sentence indices which when it is combined with SentenceEmbeddings to average them for Text Classifications (ClassifierDLApproach, SentimentDLApproach, and ClassifierDLApproach) tasks will result in very low accuracy:
- AlbertEmbeddings
- CamemBertEmbeddings
- DeBertaEmbeddings
- DistilBertEmbeddings
- LongformerEmbeddings
- RoBertaEmbeddings
- XlmRoBertaEmbeddings
- XlnetEmbeddings

Fix a bug introduced in 4.0.0 release between Transformer-based Word Embeddings and SentenceEmbeddings

---

python/sparknlp/annotation.py
python/sparknlp/base/light_pipeline.py
python/test/base/multi_document_assembler_test.py
src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
src/test/scala/com/johnsnowlabs/nlp/LightPipelineTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/MultiDocumentAssemblerTest.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/multipleannotations/MultiAnnotationsSpec.scala

Now, `fullAnnotate` and `annotate` can receive two input two arrays of strings arguments. This will allow `LightPipeline` to support functionality such as the Question Answering feature.
Currently, only one context and question at a time are supported in LightPipeline for Question Answering features. Now, we can create a list of contexts and questions to send to LightPipeline, making it easier for the user.

LightPipeline support for 2 Array Targets

---

src/main/scala/com/johnsnowlabs/client/aws/AWSGateway.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
src/test/scala/com/johnsnowlabs/util/ResourceHelperTestSpec.scala

This change increases the `S3ResourceDownloader` functionality to download, unzip, and upload model content to an external S3 URI.
Some users do not have write access to HDFS or Driver/Executors file systems e.g in K8 environments. To solve this, we include the option to define an S3 URI in `cache_folder` configuration such that these users can use their S3 bucket to store pre-trained models.
Check issues #10755 and #10786
Tested by adding an S3 URI in `cache_folder`, checking the models are uploaded in S3 and that the output is the expected one, in the following environments:
- Bare Metal Server (physical local computer)
- Google Colab
- Databricks
- GCP

Adding support for S3 in cache folder config

---

python/sparknlp/annotator/classifier_dl/__init__.py
python/sparknlp/annotator/classifier_dl/camembert_for_token_classification.py
python/sparknlp/internal/__init__.py
python/test/annotator/classifier_dl/camembert_for_token_classification_test.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowCamemBertClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForTokenClassification.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForTokenClassificationTestSpec.scala

This is a WIP to introduce CamemBERT for Token Classification such as NER or POS tasks.

Introducing CamemBERT for Token Classification

---

python/sparknlp/annotator/ner/ner_overwriter.py
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerOverwriter.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerOverwriterTest.scala

Add in NerOverwriter the test that allows us to replace some entities by another entities using the .setReplaceWords({"B-PER" : "B-PERSON" }) method.
Example :
```
documentAssembler = DocumentAssembler() \
.setInputCol("text") \
.setOutputCol("document")
tokenizer = Tokenizer() \
.setInputCols(["document"]) \
.setOutputCol("token")
tokenClassifier = AlbertForTokenClassification.pretrained() \
.setInputCols(["token", "document"]) \
.setOutputCol("label") \
.setCaseSensitive(True)
nerOverwrite  = NerOverwriter().setInputCols("label").setOutputCol("label2").setReplaceEntities({"B-PER" : "B-PERSON" })
pipeline = Pipeline().setStages([
documentAssembler,
tokenizer,
tokenClassifier,
nerOverwrite
])
data = SparkContextForTest.spark.createDataFrame([["John Lenon was born in London and lived in …
```

Implement setReplaceEntities feature in NerOverwriter annotator

---

README.md
docs/_layouts/landing.html
python/README.md
python/sparknlp/__init__.py
src/test/scala/com/johnsnowlabs/nlp/annotators/audio/Wav2Vec2ForCTCTestSpec.scala

When `PretrainedPipeline` is used in Python with ImageAssembler as one of the stages it will fail with `AttributeError: module 'sparknlp' has no attribute 'ImageAssembler'`. This PR fixes this issue.

Fix AttributeError for ImageAssembler in PretrainedPipeline

---

docs/_posts/josejuanmartinez/2022-09-19-legner_bert_indemnifications_en.md
docs/_posts/josejuanmartinez/2022-09-19-legre_indemnifications_en.md
docs/_posts/josejuanmartinez/2022-09-20-legclf_cuad_confidentiality_clause_en.md
docs/_posts/josejuanmartinez/2022-09-20-legclf_cuad_indemnifications_clause_en.md
docs/_posts/josejuanmartinez/2022-09-20-legclf_cuad_licenses_clause_en.md
docs/_posts/josejuanmartinez/2022-09-20-legclf_cuad_obligations_clause_en.md
docs/_posts/josejuanmartinez/2022-09-20-legclf_cuad_whereas_clause_en.md
docs/_posts/josejuanmartinez/2022-09-27-legassertion_time_en.md
docs/_posts/josejuanmartinez/2022-09-27-legclf_cuad_indemnifications_clause_en.md
docs/_posts/josejuanmartinez/2022-09-27-legclf_cuad_licenses_clause_en.md
docs/_posts/josejuanmartinez/2022-09-27-legner_bert_indemnifications_en.md
docs/_posts/josejuanmartinez/2022-09-27-legner_br_base_pt.md
docs/_posts/josejuanmartinez/2022-09-27-legner_br_large_pt.md
docs/_posts/josejuanmartinez/2022-09-28-legclf_enforceability_clause_en.md
docs/_posts/josejuanmartinez/2022-09-28-legclf_enforcement_clause_en.md
docs/_posts/josejuanmartinez/2022-09-28-legclf_environmental_matters_clause_en.md
docs/_posts/josejuanmartinez/2022-09-28-legner_br_bert_base_pt.md
docs/_posts/josejuanmartinez/2022-09-28-legner_br_bert_large_pt.md
docs/_posts/josejuanmartinez/2022-09-28-legner_law_money_es.md
docs/_posts/josejuanmartinez/2022-09-28-legner_laws_treaties_es.md
docs/_posts/josejuanmartinez/2022-09-28-legre_indemnifications_en.md
docs/_posts/josejuanmartinez/2022-10-02-legner_arabert_arabic_ar.md
docs/_posts/josejuanmartinez/2022-10-02-legner_bert_base_courts_de.md
docs/_posts/josejuanmartinez/2022-10-02-legner_bert_large_courts_de.md
docs/_posts/josejuanmartinez/2022-10-02-legner_courts_de.md

Models hub legal

---

python/sparknlp/annotation.py
python/sparknlp/base/light_pipeline.py
python/test/annotator/cv/vit_for_image_classification_test.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowViTClassifier.scala
src/main/scala/com/johnsnowlabs/nlp/ImageAssembler.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/cv/util/io/ImageIOUtils.scala
src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/cv/ViTImageClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/cv/feature_extractor/ImageUtilsTestSpec.scala

This change handles the errors that can rise when reading an image in the `fullAnnotateImage` method for `LightPipeline`.
When an error is raised, LightPipeline will output an empty Annotation to allow other images to process without any issue.
When a user wants to run inference from a list of images, if one image is corrupted it will stop the process and throw an error. It’s best not to interrupt the whole process if there are some paths that cannot be loaded
- Unit Tests
- Local Tests
- Google Colab Notebook

Improve Error Handling to fullAnnotateImage in LightPipeline

---

src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala

ContextSpellCheckerModel throws nullPointer exception when updateVocabClass with an array and `append=true`. 
For some reason the `vocab` attribute of the specialTransducers classes is not properly initialized.
Tested in Scala, added new test with re-produces the error in Spark-NLP 4.2.0 and added fix with a simple null check.

FIX: ContextSpellCheckerModel updateVocabClass Nullpointer

---

python/sparknlp/annotation.py
python/sparknlp/annotation_audio.py
python/sparknlp/annotation_image.py

Unifies annotatorType name in Python and Scala for spark schema in `Annotation`, `AnnotationImage` and `AnnotationAudio`
Check issue #12934
- Local Testing
- [Google Colab notebook](https://colab.research.google.com/drive/182DKGCdBEg19SZ6DbwE9c2dXyphCZvI6?usp=sharing)

Fix Inconsistent Names Annotator Schema

---

src/main/scala/com/johnsnowlabs/ml/util/LoadExternalModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
src/test/scala/com/johnsnowlabs/util/ResourceHelperTestSpec.scala

This PR changes how the link to the local resource of copyToLocal is returned to enable cross platform compatibility.
Tested on all platforms and tests passing.

SPARKNLP-561: Adjust return format of copyToLocal 

---

docs/_frontend/package.json
docs/_frontend/src/models/FilterForm/FilterForm.js
docs/_frontend/src/models/Form/Form.js
docs/_frontend/src/models/ModelItemList/ModelItemList.js
docs/_frontend/src/models/ModelItemTag/ModelItemTag.js
docs/_frontend/src/models/Pagination/Pagination.js
docs/_frontend/src/models/SearchForm/SearchForm.js
docs/_frontend/src/models/Select/Select.js
docs/_frontend/src/models/Sidebar/Sidebar.js
docs/_frontend/src/models/Spinner/Spinner.js
docs/_frontend/src/models/index.js
docs/_frontend/webpack.config.js
docs/_frontend/yarn.lock
docs/_layouts/models.html

This PR fixes the problem with the unavailable packages from the external CDN unpkg.com.

Embed React and ReactDOM instead of packages from unpkg [skip test]

---

python/sparknlp/internal/extended_java_wrapper.py

Some environments will have an alphanumeric version of Spark. This PR will make a safer comparison when it comes to whether or not we are in Spark `3.3.0` environment (needed for some operations).
We could use 
```python
cleaned_version = re.findall(r'(?:(\d+\.(?:\d+\.)*\d+))', self.sc.version)
```
or `LooseVersion` from `distutils.version`
```python
LooseVersion(self.spark_version()) >= LooseVersion("3.3.0")
```

SPARKNLP 643 detecting spark version in a safer way

---

src/main/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizer.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizerTestSpec.scala

Resolves #13015. 
The RegexTokenizer Annotator outputs wrong indexes if the pattern includes splits that are not followed by a space. This PR resolves this issue.
All tests passing, additional assertions for index alignment have been added and are also passing.

SPARKNLP-642: Fix indexing issue for regex splits without space

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowViTClassifier.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/cv/ViTForImageClassification.scala

A lot of the VIT models were prdicting NaNs because in their labels some were saved as BigInts while others were saved as Strings , I added code for corss checking
Tested it locally on models that were predicting Nan before the change

Fix a bug in Vision Transformer annotator that results in NaNs for some models

---

docs/en/annotator_entries/RegexMatcher.md
docs/en/annotators.md
python/sparknlp/annotator/matcher/regex_matcher.py
python/test/annotator/matcher/regex_matcher_test.py
src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcher.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherBehaviors.scala

This PR adds the feature to define strings instead of files to the RegexMatcher annotator. This will enable users to 
prototype faster, especially on cloud environments.
Resolves #12824.
- new parameter `rules` where users can provide an array of rules
- new parameter `delimiter` to split the rules
New and old tests passing.

SPARKNLP-621: Add string support to RegexMatcher in addition to a file

---

docs/en/annotator_entries/ClassifierDL.md
docs/en/annotator_entries/MultiClassifierDL.md
docs/en/annotator_entries/NerDL.md
docs/en/annotator_entries/SentimentDL.md
docs/en/install.md
python/sparknlp/annotator/classifier_dl/classifier_dl.py
python/sparknlp/annotator/classifier_dl/multi_classifier_dl.py
python/sparknlp/annotator/classifier_dl/sentiment_dl.py
python/sparknlp/annotator/ner/ner_dl.py
python/sparknlp/annotator/param/evaluation_dl_params.py
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/param/EvaluationDLParams.scala

This PR updates the documentation so it is more clear how to use `setTestDataset` in `*DLApproach` annotators.
In addition installation instructions for M1 machines were also updated.
Resolves #13070 and #13079.
No code changes.

SPARKNLP-656 & SPARKNLP-657: Updated Documentation

---

python/sparknlp/annotator/ner/ner_converter.py
python/sparknlp/common/annotator_properties.py
python/test/annotator/ner/ner_converter_test.py

This PR adds a missing parameter on the Python side for the NerConverter.
- Also adds missing `inputAnnotatorTypes` for NerConverter
- New test added
New and old tests passing.

SPARKNLP-661: Add missing setPreservePosition in NerConverter

---

project/Dependencies.scala

- Updating to `tensorflow-java:0.4.2` based on `TensorFlow 2.7.4` with bug and CVE fixes
Tests:
TensorFlow 2.7.4
=============
Note: This is the last release in the 2.7.x series
This releases introduces several vulnerability fixes:
-   Fixes a `CHECK` failure in tf.reshape caused by overflows ([CVE-2022-35934](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-35934))
-   Fixes a `CHECK` failure in `SobolSample` caused by missing validation ([CVE-2022-35935](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-35935))
-   Fixes an OOB read in `Gather_nd` op in TF Lite ([CVE-2022-35937](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-35937))
-   Fixes a `CHECK` failure in `TensorListReserve` caused by missing validation …

SPARKNLP-665 Updating to TensorFlow 2.7.4

---

python/sparknlp/annotator/tf_ner_dl_graph_builder.py

Adds validation for  the number and type of columns set in `TFNerDLGraphBuilder`
Avoiding a wrong definition of columns when using `TFNerDLGraphBuilder` in a pipeline
- [Google Colab Notebook](https://colab.research.google.com/drive/1ynDZwFH3-KtQq5K02cnWv-o5nuRjSqXk?usp=sharing)

SPARKNLP-664 Adding inputColsValidation to TFNerDLGraphBuilder

---

.github/workflows/build_and_test.yml
build.sbt
project/Dependencies.scala
project/M2Resolvers.scala
project/Resolvers.scala
project/assembly.sbt
project/build.properties

- now we actually build the whole Spark NLP with a specific Spark major release before testing it in GA (missed this part before)
- updating `sbt-assembly` to `2.0.0`. This has lots of performance improvements which we can benefit from when packaging Fat JARs (4 different architectures, lots of sbt dependencies)
- There is another Resolvers in `sbt` so `sbt._` had a conflict with our object called Resolvers.
- Update `sbt` to `1.8.0` with improvements and bug fixes, but mostly for CVEs fixes:
-   Updates to Coursier 2.1.0-RC1 to address [https://github.com/advisories/GHSA-wv7w-rj2x-556x](https://github.com/advisories/GHSA-wv7w-rj2x-556x "https://github.com/advisories/GHSA-wv7w-rj2x-556x")
-   Updates to Ivy 2.3.0-sbt-a8f9eb5bf09d0539ea3658a2c2d4e09755b5133e to address …

SPARKNLP 680 Update sbt, sbt-assembly, and GA for Scala unit tests

---

python/sparknlp/annotator/classifier_dl/__init__.py
python/sparknlp/annotator/classifier_dl/camembert_for_sequence_classification.py
python/sparknlp/internal/__init__.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowCamemBertClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForSequenceClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForSequenceClassificationTestSpec.scala

CamemBertForSequenceClassification can load CamemBERT Models with sequence classification/regression head on top (a linear layer on top of the pooled output) e.g. for multi-class document classification tasks.

SPARKNLP-473-implement-camembert-for-sequence-classification-annotator

---

src/main/scala/com/johnsnowlabs/client/aws/AWSGateway.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderMetaSpec.scala

This change removes getObjectFromS3 allowing AWS SDK to rise the correspondent error. 
In addition, this change refactors ResourceDownloader to reflect the intention of each credential type on the downloader.
Attempting the public credentials on a private folder will throw access errors. The result is that users will continue to try different credentials over, and over just to realize that the issue was a wrong/nonexistent path. We should report the error properly here, and stop, instead of attempting public access.
- Local Tests
- Google Colan [notebook](https://colab.research.google.com/drive/11EXU_RGnOhKnU92wa_xh_xjul8wjhFDY?usp=sharing)

SPARKNLP-682 Refactoring Error Handling Resource Downloader 

---

src/main/scala/com/johnsnowlabs/nlp/annotators/btm/TMEdgesReadWriter.scala
src/test/resources/entity-extractor/test-overlapping.txt
src/test/scala/com/johnsnowlabs/nlp/annotators/btm/BigTextMatcherTestSpec.scala

This PR fixes an issue with the BigTextMatcher Annotator, where it would not match entities with overlapping definitions. 
For Example, if both `lung` and `lung cancer` are defined, `lung` would not be matched in a given text.
This was due to an abstraction error of one of the subclasses of the BigTextMatcher during construction of the underlying data structure.
Resolves #13168.
Old tests passing and added new test to cover the bug.

SPARKNLP-675: BigTextMatcher matches entities with overlapping definitions

---

python/sparknlp/annotator/dependency/typed_dependency_parser.py
src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala

This change solves two issues:
1. Corrects inputAnnotatorTypes values in Python
2. Opens cachePath variable access since it is used in other APIs
Keep consistency between Scala and Python implementations
- x ] My code follows the code style of this project.

SPARKNLP-689 Fix inputAnnotatorTypes in TypedDependencyParser

---

python/sparknlp/annotator/spell_check/context_spell_checker.py

Removed the duplicated definition of method `setWeightedDistPath` from `ContextSpellCheckerApproach`.

Removed duplicated method definition (ContextSpellCheckerApproach)

---

python/sparknlp/base/light_pipeline.py
python/sparknlp/internal/annotator_transformer.py
python/test/pretrained/pretrained_pipeline_test.py

This change adds `outputAnnotatorType` to `AnnotatorTransformer` to avoid loading `outputAnnotatorType` attribute when components don't use it.
Pretrained Pipelines or Light Pipelines that use a stage that does not use `outputAnnotatorType` data, raises the following error:
```
AttributeError: 'Finisher' object has no attribute 'getOutputCol'
```
This change will solve two issues:
1) Any pipeline that uses `Finisher`, `GraphFinisher` or `EmbeddingsFinisher`
2) When PipelineModel is part of stages
- Local Tests
- Google Colab:
- [Finisher Issue Notebook](https://colab.research.google.com/drive/1coAmaqk4A1YvQ6Md38jjXDehHnPyJCID?usp=sharing)
- [PipelineModel Issue Notebook](https://colab.research.google.com/drive/1K_5vhKJ11aJxpYioJbH8sFadWyHhiXIf?usp=sharing)

SPARKNLP-703 Fix Finisher outputAnnotatorType Issue

---

src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala

This PR fixes an issue for the Tokenizer, when a custom pattern is used with lookahead/-behinds that have 0 width matches, indexes would not be calculated correctly. This can lead to further issues down a pipeline.
Other changes:
- resolved some warnings
- refactored tokenizer tests and added new index alignment check
Existing tests are passing (and appended with an additional index check), new tests have been added to cover this scenario

SPARKNLP-667: Fix indexing issue for custom pattern

---

python/sparknlp/annotation.py
python/sparknlp/base/light_pipeline.py
python/test/base/light_pipeline_test.py
python/test/pretrained/pretrained_pipeline_test.py
src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
src/test/scala/com/johnsnowlabs/nlp/LightPipelineTestSpec.scala

This change enables the output of embeddings for `fullAnnotate` when `parseEmbeddings` argument is set to True.
`parseEmbeddings` argument is used to include embeddings data in the output of a `LightPipeline.` However, it only works in `annotation` method and not in `fullAnnotate` which is wrong. It should work for both methods.
- Local Tests
- Google Colab [notebook](https://colab.research.google.com/drive/1zdMaq2yFU-mJKNLwBZr5QPKHhcVrGgGD?usp=sharing)

SPARKNLP-708 Enabling Embeddings output in LightPipeline.fullAnnotate

---

src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala

Restores previous behavior, where all exceptions were caught while applying custom patterns/chars in TokenizerModel.
If a user provided pattern/char can not be applied, a message will be logged instead of throwing an exception
All tests passing

SPARKNLP-667: Added try-catch block for custom pattern/char

---

src/main/scala/com/johnsnowlabs/nlp/annotators/GraphExtraction.scala
src/test/scala/com/johnsnowlabs/nlp/GraphFinisherTest.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/GraphExtractionTest.scala

1. Modifies default values of `explodeEntities` and `mergeEntities` parameters
2. Adds a warning message when there are empty paths to better guide the user on how to configure `GraphExtraction` to output meaningful relationships.
Defining these parameters by default to true, makes this annotator to have and output, avoiding users to think it does not work.
- Local Tests
- Google Colab [notebook](https://colab.research.google.com/drive/1ev7nu39IDr05YlUF-QMmST-dNvjwqY1A?usp=sharing)

SPARKNLP-713 Modifies Default Values GraphExtraction

---

python/sparknlp/annotator/classifier_dl/__init__.py
python/sparknlp/annotator/classifier_dl/camembert_for_question_answering.py
python/sparknlp/annotator/classifier_dl/camembert_for_sequence_classification.py
python/sparknlp/internal/__init__.py
python/test/annotator/classifier_dl/camembert_for_question_aswering_test.py
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowCamemBertClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForQuestionAnswering.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForQuestionAnsweringTestSpec.scala

CamemBertForQuestionAnswering can load CamemBERT Models with a span classification head on top for extractive question-answering tasks like SQuAD (a linear layer on top of the hidden-states output to compute span start logits and span end logits).

SPARKNLP-474 Introducing CamemBERT for Question Answering annotator

---

.github/workflows/build_and_test.yml
project/Dependencies.scala
python/test/annotator/conll_generator_test.py
src/main/resources/log4j2.properties
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModelTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/util/CoNLLGeneratorTestSpec.scala

No need to update Scala 2.12.15 to something higher, Spark 3.3.1 is still on this version.
- Spark 3.3.1 is now a default package for our APIs
- GCP storage is updated to 2.16.0 from 2.15.0
- Spark 3.3.1 uses log4j2 so we need another file for log4j2
- Test Python by using pyspark 3.3.1 in GA
- Ignore the test directory by adding ignored tmp_
- Fix AnalysisException exception that requires a different caught message

SPARKNLP-666 use spark 3.3.1 as base

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowForClassification.scala

- This will fix the issue with optional key in metadata. This `"Some(POSITIVE)"` will be `"POSITIVE"`
current metadata:
```
+-----------------------------------------------------------------------------------------------+
|label                                                                                          |
+-----------------------------------------------------------------------------------------------+
|[{category, 0, 87, pos, {sentence -> 0, Some(neg) -> 0.13602075, Some(pos) -> 0.8639792}, []}] |
|[{category, 0, 48, pos, {sentence -> 0, Some(neg) -> 0.34219337, Some(pos) -> 0.65780663}, []}]|
|[{category, 0, 47, neg, {sentence -> 0, Some(neg) -> 0.7505674, Some(pos) -> 0.24943262}, []}] |
|[{category, 0, 17, pos, {sentence -> 0, Some(neg) -> 0.31065974, Some(pos) -> …
```

SPARKNLP-726 Fix metadata in XXXForSequenceClassification results

---

python/sparknlp/base/embeddings_finisher.py
python/sparknlp/base/finisher.py
python/sparknlp/base/light_pipeline.py

This change introduces a configuration to skip LightPipeline validation for `inputCols` on Python side. 
This toggle should only be used for specific annotators that do not follow the convention of  predefined `inputAnnotatorTypes` and `outputAnnotatorType`.
Check thread https://github.com/JohnSnowLabs/spark-nlp-internal/pull/1482#issuecomment-1384684725
- Unit Tests
- [Google Colab notebook](https://colab.research.google.com/drive/19FJafbdstkO1xKJmexQluzKjVqtJMbDF?usp=sharing)

SPARKNLP-724 Adding configuration to skip light pipeline validation

---

src/main/scala/com/johnsnowlabs/client/aws/AWSGateway.scala
src/main/scala/com/johnsnowlabs/client/gcp/GCPGateway.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala

This change introduces an enhancement when loading models from S3 or GCP. Which consists in checking if a model already exists in a bucket before copying from models hub to an external bucket.
The current implementation always copies models from models hub when `cache_pretained` is configure for S3 or GCP. This behavior is inefficient and makes an unnecessary usage of bandwidth and network resources.
Google Colab Notebooks
- Loading models from S3 
- [Loading models from GCP](https://colab.research.google.com/drive/15FrX1JstZMM6c2GfYYGc2EhXn-UUv-MG?usp=sharing)

SPARKNLP-728 Avoid Copying Existing Models on S3/GCP

---

python/sparknlp/__init__.py

This change adds param argument to `sparknlp.start()`. With this change arguments such as `cache_folder`,  `log_folder`, and  `cluster_tmp_dir` can be defined in a single params argument instead of a dedicated argument. For example:
```
params = {
"spark.jsl.settings.pretrained.cache_folder": "s3://my_bucket/my_models",
"spark.hadoop.fs.s3a.access.key": AWS_ACCESS_KEY_ID,
"spark.hadoop.fs.s3a.secret.key": AWS_SECRET_ACCESS_KEY,
"spark.hadoop.fs.s3a.session.token": AWS_SESSION_TOKEN,
"spark.jsl.settings.aws.region": "my_region"
}
spark = sparknlp.start(params=params)
```
Other JSL libraries have a param argument to set spark configurations. This change sync open-source spark-nlp to have the same behavior.
Google Colab:
- [sparknlp.start with …

SPARKNLP-734 Enable params argument in spark_nlp.start()

---

src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
src/test/scala/com/johnsnowlabs/util/ResourceHelperTestSpec.scala

This PR fixes an issue, where a private bucket S3 would fail to download, when using loadSavedModel.
Ran relevant tests with a public and private S3 bucket.

SPARKNLP-733: Fix loadSavedModel for private buckets

---

python/sparknlp/training/conll.py
python/test/training/conll_test.py
src/main/scala/com/johnsnowlabs/nlp/training/CoNLL.scala
src/test/resources/conll/test_conll_docid.txt
src/test/scala/com/johnsnowlabs/nlp/training/CoNLLTestSpec.scala

Supports `doc_id` information through:
```
DOCSTART- -X- -{doc_id}- O
```
i.e.
```
-DOCSTART- -X- -1- O
EU NNP B-NP B-ORG
rejects VBZ B-VP O
-DOCSTART- -X- 2 O
Rare NNP B-NP O
Hendrix NNP I-NP B-PER
-DOCSTART- -X- -3-1- O
China NNP B-NP B-LOC
says VBZ B-VP O
-DOCSTART-
China NNP B-NP B-LOC
says VBZ B-VP O
```
would produce:
```
+------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
|doc_id|                text|            document|            sentence|               token|                 pos|               label|
+------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
|     1|EU rejects German...|[{document, 0, 28...|[{document, 0, …
```

Doc id conll reader

---

README.md
build.sbt
project/Dependencies.scala
python/README.md
python/sparknlp/__init__.py
src/main/scala/com/johnsnowlabs/nlp/MultiDocumentAssembler.scala
src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/audio/HubertForCTC.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/audio/Wav2Vec2ForCTC.scala
src/main/scala/com/johnsnowlabs/nlp/training/CoNLL.scala
src/test/scala/com/johnsnowlabs/nlp/training/CoNLLTestSpec.scala

Spark NLP supports `m1` and `m2` under experimental status (still requires CI/CD to build/test before it is GA). We will refactor `m1` to `silicon` and `apple_silicon` to be more generic.

Sparknlp 740 rename refactor m 1 to silicon

---

docs/_posts/bunyamin-polat/2023-01-19-finmapper_nasdaq_ticker_stock_screener_en.md
docs/_posts/josejuanmartinez/2022-08-09-finmapper_nasdaq_companyname_en_3_2.md
docs/_posts/josejuanmartinez/2022-08-09-finmapper_nasdaq_ticker_en_3_2.md
docs/_posts/josejuanmartinez/2022-08-18-finmapper_edgar_companyname_en_3_2.md
docs/_posts/josejuanmartinez/2022-08-18-finmapper_edgar_irs_en_3_2.md
docs/_posts/josejuanmartinez/2022-08-18-legmapper_edgar_companyname_en_3_2.md
docs/_posts/josejuanmartinez/2022-08-18-legmapper_edgar_irs_en_3_2.md
docs/_posts/josejuanmartinez/2022-10-22-finmapper_nasdaq_data_company_name_en.md
docs/_posts/josejuanmartinez/2022-10-22-finmapper_nasdaq_data_ticker_en.md
docs/_posts/josejuanmartinez/2023-01-13-finmapper_wikipedia_parentcompanies_en.md
docs/_posts/josejuanmartinez/2023-01-13-finmapper_wikipedia_parentcompanies_ticker_en.md
docs/_posts/josejuanmartinez/2023-01-18-finel_wiki_parentorgs_ticker_en.md

Updated fin/leg ChunkMapers model card

---

docs/en/utility_helper_modules.md

Documentation of the new deid module added to the utility_helper_modules.md file.

deid utility module added

---

docs/en/utility_helper_modules.md

deid module update

---

docs/en/spark_ocr_versions/ocr_release_notes.md
docs/en/spark_ocr_versions/release_notes_4_3_1.md

release notes for ocr 4.3.1

---

python/sparknlp/__init__.py
src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
src/test/java/com/johnsnowlabs/nlp/GeneralAnnotationsTest.java
src/test/scala/com/johnsnowlabs/nlp/SparkNLPTestSpec.scala

- Added params parameter which can supply custom configurations to the SparkSession
This PR adds additional parameters that are available in the python version but not in the Scala version.
- added the `params` parameter, that enables users to add extra spark configurations easily
- python parameters `real_time_output` and `output_level` do not apply, as they forward the output of the JVMs to the python program
Added a new test (ignore for CI) for SparkNLP start

SPARKNLP-743: Add parameter to SparkNLP.start

---

python/sparknlp/base/multi_document_assembler.py

Removed parameter that doesn't exist on Scala code and is a bug.

Removed parameter calculationsCol

---

src/main/scala/com/johnsnowlabs/client/aws/AWSGateway.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/training/CoNLL.scala
src/main/scala/com/johnsnowlabs/nlp/training/POS.scala
src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala
src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
src/test/scala/com/johnsnowlabs/nlp/training/CoNLLUFixture.scala
src/test/scala/com/johnsnowlabs/nlp/training/CoNLLUTestSpec.scala

This change adds S3 support for CoNLL, POS, CoNLLU components.
Keep consistency between helper components used to files for training
- Unit tests
- [Google Colab](https://colab.research.google.com/drive/139s-fmINEbgrGpyFiyMeR0aVWCMg_Lkq?usp=sharing)

SPARKNLP-88 Adding support for S3 in CoNLL, POS, CoNLLU

---

python/sparknlp/__init__.py
python/sparknlp/annotator/__init__.py
python/sparknlp/annotator/chunk2_doc.py
python/sparknlp/annotator/date2_chunk.py
python/sparknlp/base/__init__.py
python/test/annotator/date2_chunk_test.py
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/Chunk2Doc.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/Date2Chunk.scala
src/main/scala/com/johnsnowlabs/nlp/base.scala
src/test/scala/com/johnsnowlabs/nlp/Date2ChunkTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddingsTestSpec.scala

When a pipeline is saved with either Date2Chunk or Chunk2Doc annotators, when it is being loaded in Python it cannot find these annotators. The pacakges were not sync between Python and Scala. 
These two annotators are now under `annotators` package in Python and Scala

Sparknlp 747 Date2Chunk and Chunk2Doc are not in the correct Python module

---

src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowClassifier.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMultiClassifier.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLTestSpec.scala

Users can set a validation split when training a `ClassifierDLApproach` or `MultiClassifierDLApproach`. However, if this fraction and training data count is low, it can result in empty validation. Currently, this will cause an uncaught error. This PR fixes this and prints a warning.
Changes:
- handle and print warning when insufficient training data with low validation split produces empty validation set
- resolved some warnings
Added new tests to reflect the behavior.  Tests are passing.

SPARKNLP-746: Handle empty validation sets

---

src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/DependencyArcList.java
src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/LocalFeatureData.java

This change fixes a bug that outputs all tokens as `<no-type>` for some sentences
Check issue #2775
- Local Tests
- Google Colab [notebook](https://colab.research.google.com/drive/1WZ7FuCtm_QxGgBI76Yi7_kJImthzitQW?usp=sharing)

SPARKNLP-750 DependencyParserModel Outputs All Chunks as <no-type>

---

src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala

This PR adds support for NER tags without any schema to be detected correctly in NerConverter annotator.
Currently, if the NER labels/tags generated by NerDLModel or any XXXForTokenClassification annotators have no schema (IO/IOB/IOB2/etc.) the NerConverter has some difficulties to extract the tag in its metadata. 
IOB/IOB2 -> I-PER / B-PER
without Schema -> PER
```sh
+----------------------------------------------------------------------------------------------+
|result                                                                                        |
+----------------------------------------------------------------------------------------------+
|[PER, PER, O, O, O, LOC, O, O, O, LOC, O, O, O, O, PER, O, O, O, O, LOC]                      |
|[ORG, PER, O, O, O, O, O, O, O] …
```

SPARKNLP-786 Add support for non-schema NER tags

---

python/sparknlp/annotator/er/entity_ruler.py
src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerModel.scala
src/main/scala/com/johnsnowlabs/storage/Database.scala

This change removes `enablePatternRegex` parameter from EntityRuler since it's deprecated starting at spark-nlp 4.2.0. It only lets a private parameter in `EntityRulerModel` for backward compatibility
It has been enough time since the deprecation of `enablePatternRegex`. It will be remove for the next major release.
- Local tests loading a model trained with older versions.

SPARKNLP-782 Removes deprecated parameter enablePatternRegex

---

python/sparknlp/annotator/date2_chunk.py
python/test/annotator/date2_chunk_test.py
src/main/scala/com/johnsnowlabs/nlp/annotators/Date2Chunk.scala
src/test/scala/com/johnsnowlabs/nlp/Date2ChunkTestSpec.scala

This PR adds a new feature to the `Date2Chunk` annotator that allows the user to change the name of the converted date entity.
Existing and new tests are passing.

SPARKNLP-748: Custom Entity Name for Date2Chunk

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala

When using `WorbEmbeddingsModel` with `setEnableInMemoryStorage` as true in a `LightPipeline` it raised `Non.get` error
Make available `WorbEmbeddingsModel` in `LightPipeline`
- Google Colab [Notebook](https://colab.research.google.com/drive/1vlqPg5rQU7SchthYBwq8VmzM7nEuG-B7?usp=sharing)

SPARKNLP-785 Fix WordEmbeddingsModel Bug with LightPipeline

---

docs/en/install.md
python/docs/getting_started/index.rst
python/sparknlp/__init__.py

This PR adds a note in the documentation, that Python 3.6 is deprecated in Spark 3.2

SPARKNLP-783: Python 3.6 deprecated in Spark 3.2

---

python/sparknlp/annotator/classifier_dl/__init__.py
python/sparknlp/annotator/classifier_dl/bert_for_zero_shot_classification.py
python/sparknlp/common/properties.py
python/sparknlp/internal/__init__.py
python/test/annotator/classifier_dl/bert_for_zero_shot_classification_test.py
src/main/scala/com/johnsnowlabs/ml/ai/AlbertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/BertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/CamemBertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/DeBertaClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/DistilBertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/RoBertaClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/XXXForClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/XlmRoBertaClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/XlnetClassification.scala
src/main/scala/com/johnsnowlabs/nlp/HasCandidateLabelsProperties.scala
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForZeroShotClassification.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForZeroShotClassificationTestSpec.scala

This PR introduces ZeroShot text classification. 
> BertForZeroShotClassification using a `ModelForSequenceClassification` trained on NLI (natural language inference) tasks. Equivalent of `BertForSequenceClassification` models, but these models don't require a hardcoded number of potential classes, they can be chosen at runtime. It usually means it's slower but it is much** more flexible. Any combination of sequences and labels can be passed and each combination will be posed as a premise/hypothesis pair and passed to the pretrained model.

SPARKNLP-763 Implementing ZeroShot Text Classification for BERT and DistilBERT based on NLI

---

docs/en/CPUvsGPUbenchmark.md
python/sparknlp/annotator/ner/ner_converter.py
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverter.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala

This PR introduces a new `nerHasNoSchema` param in NerConverter. In case the labels/tags coming from NER models don't have any schema `I-` or `B-`, enabling this param will help the metadata.
This was automated in 4.3.2 release, however, this way is more explicit and safer.

SPARKNLP-796 Creating a new `nerHasNoSchema` param

---

src/main/scala/com/johnsnowlabs/ml/ai/AlbertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/BertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/CamemBertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/DeBertaClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/DistilBertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/RoBertaClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/XXXForClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/XlmRoBertaClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/XlnetClassification.scala
src/main/scala/com/johnsnowlabs/nlp/HasClassifierActivationProperties.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForZeroShotClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DeBertaForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/LongformerForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlnetForSequenceClassification.scala

This change adds a `threshold` parameter to all annotators that use XXXForSequenceClassification and ZeroShotClassification components.
Allow users to setup this parameter to adjust the balance between precision and recall in the classification process.
Local unit tests

SPARKNLP-800 Adding threshold parameter to all ForSequenceClassification

---

python/sparknlp/__init__.py
python/sparknlp/annotator/classifier_dl/__init__.py
python/sparknlp/annotator/classifier_dl/distil_bert_for_zero_shot_classification.py
python/sparknlp/internal/__init__.py
python/test/annotator/classifier_dl/distil_bert_for_zero_shot_classification_test.py
src/main/scala/com/johnsnowlabs/ml/ai/DistilBertClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForZeroShotClassification.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForZeroShotClassificationTestSpec.scala

New Annotator DistilBertForZeroShotClassification 
Added DistilBertForZeroShotClassification in Scala and Python
Scala and python unit tests ( last unit test does not work at the moment  because of the sequence classifier bug)
- [X ] New feature (non-breaking change which adds functionality)

adding DistilBertForZeroShotClassification in python and scala

---

src/main/scala/com/johnsnowlabs/nlp/annotators/tapas/TapasEncoder.scala

A bug fix for the Tapas model. 
The problem is that the maximum value rank in Tapas is limited to 255 and if the text is long enough you may end up with higher ranks. The solution is to replace ranks higher than 255 with 255.
The issue was reported by a user in the slack channel. If you feed a long text (i.e table) you may end up with ranks higher than 255 and this is the max value allowed by the model (perhaps they used a byte variable to represent it or a static array). Such ranks case a Tensorflow exception.
I first reproduced the problem by running Tapas on long enough texts and made sure that the fixes solves the problem

Fix Tapas bug due to exceeding the maximum rank value

---

.github/workflows/build_and_test.yml
project/Dependencies.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/LoadSentencepiece.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcher.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/LoadsContrib.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/normalizer/MosesPunctNormalizer.scala
src/main/scala/com/johnsnowlabs/util/CoNLLGenerator.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/SparkSessionTest.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteBehaviors.scala
src/test/scala/com/johnsnowlabs/nlp/util/CoNLLGeneratorTestSpec.scala

Adding changes to make spark-nlp 3.4.0 default version by updating some imports
Use the latest spark version
- Local Tests
- Databricks 13

SPARKNLP-819 Adding changes to make spark-nlp 3.4.0 default version

---

src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala

This PR fixes a bug, where loadSavedModel throws an error, when trying to access files via DBFS.
It seems like in a previous commit for a new feature, `ResourceHelper`'s `path` variable changed types from `Path` to `Option[Path]` . Calling the `toString` method on this type will instead convert the `Option` instead of the actual path. This was fixed with `path.get`.
Tested on Databricks and it is working again as expected.

Fix loadSavedModel for DBFS

---

docs/en/transformer_entries/AlbertForSequenceClassification.md
docs/en/transformer_entries/BertForSequenceClassification.md
docs/en/transformer_entries/CamemBertForSequenceClassification.md
docs/en/transformer_entries/DistilBertForSequenceClassification.md
docs/en/transformer_entries/LongformerForSequenceClassification.md
docs/en/transformer_entries/RoBertaForSequenceClassification.md
docs/en/transformer_entries/XlmRoBertaForSequenceClassification.md

Adds details about `XXXForSequenceClassification` & `XXXForZeroShotClassification` annotators supporting multiclass and multilabel with `softmax` and `sigmoid`.

Update XXXForSequence with multilabel and activation function

---

examples/python/annotation/text/english/zero-shot text classification/Zero_Shot_Text_Classification_by_BERT.ipynb
python/sparknlp/common/properties.py
src/main/scala/com/johnsnowlabs/nlp/HasClassifierActivationProperties.scala

Adding multilabel param to all sequence and zero-shot classifiers
Adding `multilabel` parameter and `setMultiLabel` setter 
Activation is a bit too technical. So we added `multilabel` to allow users to better understand its purpose.
- Local Tests
- Google colab [notebook](https://colab.research.google.com/drive/1pizu9DzZEK18waaOtTwszK1RzpEXvB16?usp=sharing)

SPARKNLP-825 Adding multilabel param

---

src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/LoadsContrib.scala

Removing SystemUtils dependency in favor of Java compatibility
This changes fixes an error presented when using spark-nlp as a `dependency` in a Java project
Fix the following error:
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-05-13 10:15:11.314 ERROR 19571 --- [           main] o.s.boot.SpringApplication               : Application run failed
java.lang.NoClassDefFoundError: org/apache/commons/lang/SystemUtils
at com.johnsnowlabs.nlp.annotators.ner.dl.LoadsContrib$.contribPaths$lzycompute(LoadsContrib.scala:42) ~[spark-nlp_2.12-4.2.0.jar:4.2.0]
at com.johnsnowlabs.nlp.annotators.ner.dl.LoadsContrib$.contribPaths(LoadsContrib.scala:41) ~[spark-nlp_2.12-4.2.0.jar:4.2.0]
at …
```

SPARKNLP-839 Fix Java Compatibility Issue

---

python/sparknlp/internal/__init__.py
python/sparknlp/pretrained/resource_downloader.py
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/pretrained/MockResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderMetaSpec.scala

This PR adds a unzip argument to downloadModelDirectly in ResourceDownloader
issue: https://github.com/JohnSnowLabs/spark-nlp-internal/issues/1837
1) Added unzip argument to downloadModelDirectly() in ResourceDownloader.
BEFORE:   downloadModelDirectly(name, remote_loc="public/models")
AFTER:     downloadModelDirectly(name, remote_loc="public/models", unzip=True)
2) Updated also name argument
BEFORE:  clinical/models/deidentify_enriched_clinical_en_2.7.2_2.4_1611917177874.zip
AFTER:   1--> clinical/models/deidentify_enriched_clinical_en_2.7.2_2.4_1611917177874.zip  
2--> s3://auxdata.johnsnowlabs.com/clinical/models/deidentify_enriched_clinical_en_2.7.2_2.4_1611917177874.zip
3) deleted duplicate codes
Note: supported Backward compatibility
Tested via Scala and Python tests locally
- [x ] …

Add unzip param to downloadModelDirectly in ResourceDownloader

---

src/main/scala/com/johnsnowlabs/ml/ai/Albert.scala
src/main/scala/com/johnsnowlabs/ml/ai/Bert.scala
src/main/scala/com/johnsnowlabs/ml/ai/CamemBert.scala
src/main/scala/com/johnsnowlabs/ml/ai/DistilBert.scala
src/main/scala/com/johnsnowlabs/ml/ai/RoBerta.scala
src/main/scala/com/johnsnowlabs/ml/ai/XlmRoberta.scala
src/main/scala/com/johnsnowlabs/ml/ai/Xlnet.scala

This PR adds `warmup` TF session for the remaining of annotators: 
- ALBERT
- BERT
- CamemBERT
- DistilBERT
- RoBERTa
- XLM-RoBERTa
- XLNet
The warmup runs once when the model is being loaded to reduce the first inference time, it is also useful when external models are being imported. This makes sure those models work right there without the need of inferencing afterwards.

SPARKNLP 801 set up warmup for all embeddings

---

python/sparknlp/annotator/embeddings/__init__.py
python/sparknlp/annotator/embeddings/instructor_embeddings.py
python/sparknlp/internal/__init__.py
python/test/annotator/embeddings/instructor_embeddings_test.py
src/main/scala/com/johnsnowlabs/ml/ai/Instructor.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/sign/ModelSignatureConstants.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/InstructorEmbeddings.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/InstructorEmbeddingsTestSpec.scala

This PR adds Instructor embeddings to SparkNLP
Instructor-XL is the best model according to this leaderboard: https://huggingface.co/spaces/mteb/leaderboard
> We introduce Instructor👨‍🏫, an instruction-finetuned text embedding model that can generate text embeddings tailored to any task (e.g., classification, retrieval, clustering, text evaluation, etc.) and domains (e.g., science, finance, etc.) by simply providing the task instruction, without any finetuning. Instructor👨‍ achieves sota on 70 diverse embedding tasks! The model is easy to use with our customized sentence-transformer library. For more details, check out [our paper](https://arxiv.org/abs/2212.09741) and [project page](https://instructor-embedding.github.io/)!

SPARKNLP 836 - Introducing "Instructor Embeddings" for sentence embeddings like Instructor-XL model

---

python/sparknlp/annotator/embeddings/__init__.py
python/sparknlp/annotator/embeddings/e5_embeddings.py
python/sparknlp/internal/__init__.py
python/test/annotator/embeddings/e5_embeddings_test.py
src/main/scala/com/johnsnowlabs/ml/ai/E5.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/E5Embeddings.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/E5EmbeddingsTestSpec.scala

This PR adds E5 embeddings to SparkNLP
[e5-large-v2](https://huggingface.co/intfloat/e5-large-v2) is one of the best model according to this leaderboard: https://huggingface.co/spaces/mteb/leaderboard

SPARKNLP 852 - Introducing "E5 Embeddings" for sentence embeddings like e5-large-v2 model

---

python/test/annotator/seq2seq/bart_transformer_test.py
src/main/scala/com/johnsnowlabs/ml/ai/Bart.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/BartTransformer.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/BartTestSpec.scala

Added maxInputLength to `BartTransformer`. fixes #13829

SPARKNLP-846: BART: Added maxInputLength.

---

python/sparknlp/annotator/classifier_dl/bert_for_zero_shot_classification.py
src/main/scala/com/johnsnowlabs/nlp/HasClassifierActivationProperties.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForZeroShotClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForZeroShotClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForZeroShotClassification.scala

Modifies getActivation method to take multilabel into account and added as invocation for each classifier that uses `XXXForClassification.predictSequenceWithZeroShot` method
Solving issue #13881 
- Local Tests

SPARKNLP-867 Solves multiLabel param issue in ZeroShot annotators

---

python/sparknlp/__init__.py
src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
src/test/scala/com/johnsnowlabs/nlp/SparkNLPTestSpec.scala

- Users can use params to add `spark.driver.cores`, however, the hard-coded `local[*]` is overriding that
- So we need to check if `spark.driver.cores` is set, both added to the conf and make sure `local[N]` is set where N is `spark.driver.cores`
- There is a TypeError now checking if the `params` in Python side is an actual dict

Sparknlp 868 make spark driver cores override local in start functions

---

python/sparknlp/common/properties.py

This change adds `threshold` for Classifier DL components in Python module
Fix a bug when Python users try to use  `threshold` parameter
- Local Tests

SPARKNLP-869 Adding threshold to properties for python module

---

src/main/scala/com/johnsnowlabs/ml/ai/SentenceDetectorDL.scala
src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMultiClassifier.scala

Setting upper and lower bounds when computing accuracy
Due to anomalies in the datasets, the actual accuracy can go above 1. This confuses users and makes it look like the model results are unreliable.
- Local tests

SPARKNLP-738 Enforcing accuracy to 0 and 1 in classifiers

---

src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.scala

The change solves an issue with Marian transformers in Python by handling vocabulary type from Python side
Solves Marian transformers error in Python
- Local Tests
- Google colab [notebook](https://colab.research.google.com/drive/1rwJiyni5w3A7pJra0A9HSYmwPeR4JQAO?usp=sharing)

SPARKNLP-873 Issue with MarianTransformers models

---

src/main/scala/com/johnsnowlabs/ml/ai/Bart.scala
src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Generate.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/BartTestSpec.scala

BART low temperature value bug fix
This PR fixes a bug that will occur when there are no non infinite logits satisfying the low `temperature` and `top_k` values.

BART Bug fix #13898

---

src/main/scala/com/johnsnowlabs/ml/ai/E5.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/E5Embeddings.scala

This change adds ONNX support for E5Embeddings
Enable ONNX support for faster inference
- Local Tests
- Google Colab [notebook](https://huggingface.co/intfloat/e5-small-v2)

SPARKNLP-862 Adding ONNX support for E5 Embeddings

---

docs/_posts/ahmedlone127/2023-08-25-e5_base_opt_en.md
docs/_posts/ahmedlone127/2023-08-25-e5_base_quantized_en.md
docs/_posts/ahmedlone127/2023-08-25-e5_base_v2_opt_en.md
docs/_posts/ahmedlone127/2023-08-25-e5_base_v2_quantized_en.md
docs/_posts/ahmedlone127/2023-08-25-e5_large_v2_opt_en.md
docs/_posts/ahmedlone127/2023-08-25-e5_large_v2_quantized_en.md
docs/_posts/ahmedlone127/2023-08-25-e5_small_opt_en.md
docs/_posts/ahmedlone127/2023-08-25-e5_small_quantized_en.md
docs/_posts/ahmedlone127/2023-08-25-e5_small_v2_opt_en.md
docs/_posts/ahmedlone127/2023-08-25-e5_small_v2_quantized_en.md

Fixes modelhub card code sections for onnx E5 cards

fixed e5 modelhub card code sections

---

src/main/scala/com/johnsnowlabs/ml/onnx/OnnxSerializeModel.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/audio/WhisperForCTCTest.scala

This PR fixes the loading onnx whisper models. Previously, a suffix was used to name the model files. This has been removed.
All Tests passing.

[SPARKNLP-906] Fix reading suffix

---

src/main/scala/com/johnsnowlabs/ml/ai/AlbertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/XXXForClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/ZeroShotNerClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForQuestionAnswering.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForTokenClassification.scala

This PR adds ONNX Support for:
- AlbertQuestionAnswering
- AlbertSequenceClassification
- AlbertTokenClassification
Adding ONNX support for faster inference

Adding ONNX Support to ALBERT Token and Sequence Classification and Question Answering annotators

---

python/sparknlp/annotator/embeddings/doc2vec.py
python/sparknlp/annotator/embeddings/word2vec.py
src/main/scala/com/johnsnowlabs/nlp/embeddings/Doc2VecModel.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/Word2VecModel.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/Doc2VecTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/Word2VecTestSpec.scala

This change adds getVectors method to Word2VecModel and Doc2VecModel, allowing users to retrieve word vectors representation as a spark dataframe
Solves issue #13930
- Local Tests

SPARKNLP-884 Enabling getVectors method

---

docs/en/transformer_entries/WhisperForCTC.md
examples/python/annotation/audio/whisper/Automatic_Speech_Recognition_Whisper_(WhisperForCTC).ipynb
examples/python/transformers/HuggingFace in Spark NLP - WhisperForCTC.ipynb
examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_Whisper.ipynb
python/sparknlp/annotator/audio/whisper_for_ctc.py
src/main/scala/com/johnsnowlabs/nlp/annotators/audio/WhisperForCTC.scala

This PR adds a note and a check for WhisperForCTC. Only Spark Versions 3.4 and up are supported for this annotator.
More transparent errors, so that users will know which version to use.

SPARKNLP-919: Add note for Spark Version support

---

src/main/scala/com/johnsnowlabs/ml/ai/Bart.scala
src/main/scala/com/johnsnowlabs/ml/ai/RoBertaClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/GPT2Transformer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BartTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/Gpt2Tokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/XlmTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/LongformerEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaSentenceEmbeddings.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForQuestionAnsweringTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizerBehaviours.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/Gpt2TokenizerTestSpec.scala

This PR introduces several fixes to produce expected behavior of RobertaForQuestionAnswering models.
Resolves #14005.
It includes the following changes:
1. BPE Tokenizer includes a flag whether or not to always prepend a space before words (previous behavior for embeddings)
2. BPE Tokenizer correctly converts and tokenizes non-latin other special character words
3. RobertaForQA produces the same logits and indexes as the transformers implementation
- *Note*:  Spark NLP uses 1-based indexing. So to retrieve the answer strings, you have to use `context.slice(start + 1, end + 1)`
Users should expect the same results as their custom exported models
New tests added, existing tests are passing

SPARKNLP-921: Bug Fix for BPE and RobertaForQA

---

src/main/scala/com/johnsnowlabs/ml/ai/BertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/DistilBertClassification.scala

This change fix the return order of logits in `BertClassification` and `DistilBertClassification`
Solve potential bugs introduced in the changes for ONNX support in Bert and Distilbert classification components
- Local tests

[SPARKNLP-934] Fixing return order in computeLogitsWithTF

---

docs/en/annotator_entries/DocumentCharacterTextSplitter.md
docs/en/annotators.md
python/sparknlp/annotator/__init__.py
python/sparknlp/annotator/document_character_text_splitter.py
python/test/annotator/document_character_text_splitter_test.py
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/DocumentCharacterTextSplitter.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/DocumentCharacterTextSplitterTest.scala

This PR introduced the `DocumentCharacterTextSplitter` which allows users to split large documents into smaller chunks.
DocumentCharacterTextSplitter takes a list of separators. It takes the separators in order and
splits subtexts if they are over the chunk length, considering optional overlap of the chunks.
This will allow users manage large texts better to feed into e.g. language models
New and old tests are passing

SPARKNLP-924: DocumentCharacterTextSplitter

---

src/main/scala/com/johnsnowlabs/ml/ai/E5.scala
src/main/scala/com/johnsnowlabs/ml/ai/MPNet.scala
src/main/scala/com/johnsnowlabs/ml/util/LinAlg.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/E5EmbeddingsTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/MPNetEmbeddingsTestSpec.scala

This change modifies E5 and MPNet embeddings by adding a method for padding with zeros all required arrays inside a batch to ensure all of them have the same length.
In addition, this change resolves a bug with ONNX models where the size of the embedding is different for some sentences.
Solves issue #14049
Solves issue #14066
- Local Tests
- Google Colab [notebooks](https://colab.research.google.com/drive/1cVpUKzDswMQ_V6MiWlKrj6ZtDa2Ge7o5?usp=sharing)
- ONNX MPNet and E5 embeddings sizes [notebook](https://colab.research.google.com/drive/16eokLJ_SCA2OLy7vWuA76tu4aMIYn8MS#scrollTo=lnZ5ed06Dy7c)
- TF MPNet Embeddings size [notebook](https://colab.research.google.com/drive/1YsBtxGxDnv3iyTq7nwMP1CTJb4AaI7FG#scrollTo=IGvfkp4avWu7)
- E5 Embeddings values …

SPARKNLP-938 E5 and MPNet embeddings crash on a sentence basis - missing pool average

---

examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_CamemBertForQuestionAnswering.ipynb
examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_CamemBertForSequenceClassification.ipynb
examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_CamemBertForTokenClassification.ipynb
src/main/scala/com/johnsnowlabs/ml/ai/CamemBertClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForTokenClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForQuestionAnswering.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForTokenClassification.scala

Adding ONNX support for:
- CamemBertForQuestionAnswering
- CamemBertForTokenClassification
- CamemBertForSequenceClassification
Adding ONNX support for classification annotators for faster inference
- Local Tests

[SPARKNLP-939] Adding ONNX support for CamemBert transformers

---

docs/en/annotator_entries/DocumentCharacterTextSplitter.md
docs/en/annotator_entries/DocumentTokenSplitter.md
docs/en/annotators.md
python/sparknlp/annotator/__init__.py
python/sparknlp/annotator/document_character_text_splitter.py
python/sparknlp/annotator/document_token_splitter.py
python/sparknlp/annotator/document_token_splitter_test.py
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/DocumentCharacterTextSplitter.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/DocumentTokenSplitter.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/TextSplitter.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/DocumentCharacterTextSplitterTest.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/DocumentTokenSplitterTest.scala

This PR adds the annotator DocumentTokenSplitter. This annotator takes a large body of text and splits them into chunks of a given number of tokens. Currently, it splits the text by whitespaces to create the tokens. The number of these tokens will then be used as a measure of the text length. In the future, other tokenization techniques will be supported.
The PR also includes some minor fixes for DocumentCharacterTextSplitter.
This annotator makes splitting a large text to feed into language models easy.
New and existing tests passing

SPARKNLP-925 DocumentTokenSplitter

---

src/main/scala/com/johnsnowlabs/nlp/annotators/DocumentCharacterTextSplitter.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/DocumentCharacterTextSplitterTest.scala

This PR fixes a bug with the DocumentCharacterTextSplitter, where it couldn't be saved in a pipeline (saving it individually worked fined). 
This was due to the companion object missing for the annotator.
New and old tests passing.

SPARKNLP-955: DocumentCharacterTextSplitter Bug Fix

---

python/sparknlp/annotator/embeddings/bge_embeddings.py
python/sparknlp/internal/__init__.py
src/main/scala/com/johnsnowlabs/ml/ai/BGE.scala
src/main/scala/com/johnsnowlabs/ml/util/LinAlg.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/BGEEmbeddings.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/BGEEmbeddingsTestSpec.scala

Created Scala and Python classes for the BGE Embeddings models.
Spark NLP currently supports BGE embeddings but didn't have a specific class to store and work with those models. The current approach is to load the models as BertEmbeddings, which loads the sentence embeddings model, BGE, as word embeddings. To load the model as sentence embeddings, I added a new class based on the current E5 embeddings annotator.
The code has not been tested, as I don't have a Scala environment set yet.

Added BGE Embeddings

---

src/main/scala/com/johnsnowlabs/ml/ai/DeBertaClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DeBertaForQuestionAnswering.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DeBertaForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DeBertaForTokenClassification.scala

This PR adds ONNX support To DebertaForXXX annotators

adding onnx support to DeberatForXXX annotators

---

examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_XlmRoBertaForQuestionAnswering.ipynb
examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_XlmRoBertaForSequenceClassification.ipynb
examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_XlmRoBertaForTokenClassification.ipynb
src/main/scala/com/johnsnowlabs/ml/ai/AlbertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/BertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/CamemBertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/DeBertaClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/DistilBertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/RoBertaClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/XlmRoBertaClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForQuestionAnswering.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForSequenceClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForTokenClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForZeroShotClassification.scala

Adding ONNX support XLM-Roberta classifiers

Sparknlp 967 add onnx support to xlm roberta classifiers

---

src/main/scala/com/johnsnowlabs/storage/StorageLocator.scala

fixes #14129 
---
Databricks notebook was modified from [spark-nlp-training-and-inference-example](https://docs.databricks.com/en/_extras/notebooks/source/machine-learning/spark-nlp-training-and-inference-example.html)
- Libraries:
```
spark-nlp==5.2.2
com.johnsnowlabs.nlp:spark-nlp_2.12:5.2.2
```
- Advanced options -> Spark Config 
```
spark.kryoserializer.buffer.max 2000M
spark.kyroserializer org.apache.spark.serializer.KryoSerializer
spark.jsl.settings.storage.cluster_tmp_dir dbfs:/tmp/spark_nlp/standard
```
- Outcome: 
Errors thrown from `glove_embeddings = WordEmbeddingsModel.load( "dbfs:/FileStore/pzn_ai/nlp_pretrained_models/glove_100d") `
`_java.nio.file.AccessDeniedException: nvirginia-prod/42307XXX92305032/dbfs:/tmp/spark_nlp/standard/ca628fbc03c8_cdx/EMBEDDINGS_glove_100d/: PUT …

[Issue#14129] Fix for spark.jsl.settings.storage.cluster_tmp_dir configuration 

---

examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_BertForZeroShotClassification.ipynb
python/sparknlp/annotator/classifier_dl/bert_for_zero_shot_classification.py
python/test/annotator/classifier_dl/bert_for_zero_shot_classification_test.py
src/main/scala/com/johnsnowlabs/ml/ai/BertClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForZeroShotClassification.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForZeroShotClassificationTestSpec.scala

This PR adds onnx support to BertForZeroShotClassification

adding import notebook + changing default model + adding onnx support

---

src/main/scala/com/johnsnowlabs/ml/onnx/OnnxSerializeModel.scala
src/main/scala/com/johnsnowlabs/ml/onnx/OnnxWrapper.scala

Fixed bug with models that has 'onnx_data' file not working in dbfs/hdfs

Fixed a bug with models that has 'onnx_data' file not working in dbfs/hdfs

---

src/main/scala/com/johnsnowlabs/ml/ai/GPT2.scala

This PR fixes `java.lang.IllegalArgumentException: No Operation named [init_all_tables] in the Graph` when model needs to be deserialized (e.g. broadcast to worker nodes). The deserialization is skipped when the model is already loaded (so the issue will only appear on the worker nodes and not the driver)
GPT2 does not contain tables and so does not require this command. Moreover, this is a legacy feature of TF 1.x models.
Resolves #14110.
Tests for GPT2 are passing on a cluster.

SPARKNLP-1000: Fix No Operation named [init_all_tables] for GPT2

---

src/main/scala/com/johnsnowlabs/ml/ai/Albert.scala
src/main/scala/com/johnsnowlabs/ml/ai/AlbertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/BGE.scala
src/main/scala/com/johnsnowlabs/ml/ai/Bert.scala
src/main/scala/com/johnsnowlabs/ml/ai/BertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/CamemBert.scala
src/main/scala/com/johnsnowlabs/ml/ai/CamemBertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/DeBerta.scala
src/main/scala/com/johnsnowlabs/ml/ai/DeBertaClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/DistilBert.scala
src/main/scala/com/johnsnowlabs/ml/ai/DistilBertClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/E5.scala
src/main/scala/com/johnsnowlabs/ml/ai/MPNet.scala
src/main/scala/com/johnsnowlabs/ml/ai/RoBerta.scala
src/main/scala/com/johnsnowlabs/ml/ai/RoBertaClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/XlmRoBertaClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/XlmRoberta.scala
src/main/scala/com/johnsnowlabs/ml/ai/seq2seq/OnnxT5EncoderDecoder.scala
src/main/scala/com/johnsnowlabs/ml/ai/t5/OnnxT5EncoderDecoder.scala

This reverts commit eb91fde954769ef0ee18092f9011555fc22a5013.

Replace hard exception with soft logs

---

docs/_posts/maziyarpanahi/2023-02-08-zero_shot_ner_roberta_en.md
src/main/scala/com/johnsnowlabs/ml/ai/RoBertaClassification.scala
src/main/scala/com/johnsnowlabs/ml/ai/ZeroShotNerClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/ZeroShotNerModel.scala

Adding changes required to load ONNX version of `ZeroShotNerClassification` and fix predictions issue
Solves issue #14159
- Local Tests
- Google Colab [notebook](https://colab.research.google.com/drive/1T0LUV2nFJIyNl78OX85Jv8w9M2_5pA0K?usp=sharing)

[SPARKNLP-994] Solves ZeroShotNerClassification Issue

---

examples/python/annotation/text/english/language-translation/Multilingual_Translation_with_M2M100.ipynb

adding colab notebook for M2M100

---

docs/en/install.md
python/docs/getting_started/index.rst

This PR fixes inconsistent documentation regarding `sparknlp.start()` and how to manually start a Spark NLP Session
Resolves #14198.
No code changes, only documentation.

SPARKNLP-1026: Fix documentation for sparknlp.start()

---

docs/en/annotators.md
docs/en/transformer_entries/UAEEmbeddings.md
examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_E5.ipynb
python/sparknlp/annotator/embeddings/__init__.py
python/sparknlp/annotator/embeddings/uae_embeddings.py
python/sparknlp/internal/__init__.py
python/sparknlp/pretrained/resource_downloader.py
python/test/annotator/embeddings/uae_embeddings_test.py
src/main/scala/com/johnsnowlabs/ml/ai/UAE.scala
src/main/scala/com/johnsnowlabs/ml/onnx/OnnxSerializeModel.scala
src/main/scala/com/johnsnowlabs/ml/util/LinAlg.scala
src/main/scala/com/johnsnowlabs/nlp/annotator.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/UAEEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/ml/util/LinAlgTest.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/UAEEmbeddingsTestSpec.scala

This PR adds an Annotator for UAE embeddings.  For this, new pooling operations for word embeddings have been added. 
Namely poooling by 
1. Using a token at a specific index (such as the `[CLS]` token, or the last token)
2. Max pooling across the sequence dimension
3. `[CLS]` + Mean of the embeddings
These can be set with `setPoolingStrategy` for the annotator.
Additionally, it fixes a bug with serializing onnx models that do not have a `.onnx_data` file (b73dc0b1ecdb49af9f2fa6e47b0af23d47442a53). @prabod I think you worked on this part, could you review if the fix looks good? I provided a description in the commit message. Thanks!
New tests and old tests are passing.

SPARKNLP-962: UAEEmbeddings

---

src/main/scala/com/johnsnowlabs/nlp/pretrained/RepositoryMetadata.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala

issue --> https://github.com/JohnSnowLabs/spark-nlp/issues/14221
Cache mechanism implementation for metadata.json. 
Nowadays, metadata.json is more than 10MB and it will increase in the future.
The main logic is here: 
1 - gets3Object that includes getLastModified() (just contains a summary, do not download the whole metadata.json file.)
2- check the condition (cache contains up-to-date metadata)
3- If the cache contains up-to-date metadata, get it; 
Otherwise, download it, set it to the cache, and return it.

Cache mechanism implementation for metadata.json

---

src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala

The main goal of this PR is to close the connection of s3.  
Releases any underlying system resources by invoking the close() method in ResourceDownloader. 
There is a bug in spark-nlp==5.3.3, related to https://github.com/JohnSnowLabs/spark-nlp/pull/14224
When a lot of models are downloaded; 
since the connection is consumed,  
"Timeout waiting for connection from pool" error is thrown. 
There is a bug in spark-nlp==5.3.3. This PR will solve the bug.
Locally with Python and Scala. 
Additionally, I ran some test code in the Jenkins server when using the jar I created from this branch

Closed the S3 connection

---

build.sbt
project/Dependencies.scala

This PR adds the dependency for the `jsl-openvino` module.
Part of #14200.

openVINO Dependencies

---

src/main/scala/com/johnsnowlabs/ml/ai/BertClassification.scala

This change modifies BertForZeroShotClassification by adding a method for padding with zeros all required arrays inside a batch to ensure all of them have the same length.
ran local unit tests that were previously failing

bert for zero shot classification crashes on sentence basis 

---

src/main/scala/com/johnsnowlabs/ml/ai/LLAMA2.scala

Fix llama2 decoder receiving incorrect next position ID.

LLAMA2 OpenVINO Position ID Fix

---

python/sparknlp/annotator/seq2seq/__init__.py
python/sparknlp/annotator/seq2seq/mistral_transformer.py
python/sparknlp/internal/__init__.py
python/test/annotator/seq2seq/mistral_transformer_test.py
src/main/scala/com/johnsnowlabs/ml/ai/Mistral.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MistralTransformer.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MistralTestSpec.scala

Introducing MistralAI LLM models
Mistral 7B, a 7.3 billion-parameter model that stands out for its efficient and effective
performance in natural language processing. Surpassing Llama 2 13B across all benchmarks and
excelling over Llama 1 34B in various aspects, Mistral 7B strikes a balance between English
language tasks and code comprehension, rivaling the capabilities of CodeLlama 7B in the
latter.

SparkNLP - 995 Introducing MistralAI LLMs

---

src/main/scala/com/johnsnowlabs/ml/onnx/OnnxWrapper.scala
src/main/scala/com/johnsnowlabs/ml/openvino/OpenvinoWrapper.scala
src/main/scala/com/johnsnowlabs/ml/util/LoadExternalModel.scala
src/main/scala/com/johnsnowlabs/util/ZipArchiveUtil.scala

This PR addresses the issue of file duplication by adding a random suffix when using `sparkContext.addFile` for ONNX and OpenVINO models. This enhancement ensures that each file added to Spark has a unique name, preventing conflicts and improving the robustness of file handling in distributed environments.
Check [this jira](https://johnsnowlabs.atlassian.net/browse/SPARKNLP-1052) issue
- Databricks notebooks

[SPARKNLP-1052] Adding random suffix to avoid duplication in spark files

---

src/main/scala/com/johnsnowlabs/ml/ai/LLAMA2.scala
src/main/scala/com/johnsnowlabs/ml/ai/Mistral.scala
src/main/scala/com/johnsnowlabs/ml/ai/Phi2.scala
src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Generate.scala
src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitWarper/TopKLogitWarper.scala
src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitWarper/TopPLogitWarper.scala
src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Search/BeamScorer.scala
src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Search/BeamSearchScorer.scala
src/main/scala/com/johnsnowlabs/nlp/HasGeneratorProperties.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/LLAMA2Transformer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MistralTransformer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/Phi2Transformer.scala
src/test/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitProcess/LogitProcessorTest.scala
src/test/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitWarper/LogitWarperTest.scala

This PR adds the ability to specify custom stop token ids.

Added custom stop token id support

---

python/sparknlp/annotator/matcher/date_matcher.py
src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcher.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcherUtils.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcher.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcherMultiLanguageTestSpec.scala

Adding `aggressiveMatching` parameter to find dates even in ambiguous or less common formats. This will instruct the annotator to execute `runDateExtractorChain` method for empty outputs
See issue #14100
- Local Test
- Google Colab [notebook](https://colab.research.google.com/drive/1993b8yfvLlpg7hZysAFDp1kI8mVa-BYV?usp=sharing)

[SPARKNLP-1058] Adding aggressiveMatching parameter

---

examples/python/annotation/text/english/text-similarity/doc-sim-ranker/test_doc_sim_ranker.ipynb
python/sparknlp/annotator/similarity/document_similarity_ranker.py
src/main/scala/com/johnsnowlabs/nlp/annotators/similarity/DocumentSimilarityRankerApproach.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/similarity/DocumentSimilarityUtil.scala
src/main/scala/com/johnsnowlabs/util/spark/SparkUtil.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/SparkSessionTest.scala
src/test/scala/com/johnsnowlabs/nlp/similarity/DocumentSimilarityRankerTestSpec.scala
src/test/scala/com/johnsnowlabs/util/SparkUtilTest.scala

This pull request introduces the `aggregationMethod` parameter to the `DocumentSimilarityRanker` annotator. The new parameter allows users to specify the method used to aggregate multiple sentence embeddings into a single vector representation.
Allows users to tailor the aggregation method to their specific use case, whether they need a general overview (AVERAGE), focus on the initial context (FIRST), or emphasize the strongest signals (MAX).
This change solves the following issues:
- Issue #14368
- Issue #14195 
- Local Tests

[SPARKNLP-1059] Adding aggressiveMatching parameter to DocumentSimilarityRanker

---

python/sparknlp/annotator/seq2seq/__init__.py
python/sparknlp/annotator/seq2seq/qwen_transformer.py
python/sparknlp/internal/__init__.py
python/test/annotator/seq2seq/qwen_transformer_test.py
src/main/scala/com/johnsnowlabs/ml/ai/Qwen.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/QwenTransformer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeSpecialTokens.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/QwenTokenizer.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/QwenTestSpec.scala

This PR introduce the QWEN family of LLMs
Qwen: comprehensive language model series
Qwen1.5 is the beta version of Qwen2, a transformer-based decoder-only language model
pretrained on a large amount of data. In comparison with the previous released Qwen, the
improvements include:
6 model sizes, including 0.5B, 1.8B, 4B, 7B, 14B, and 72B; Significant performance improvement
in Chat models; Multilingual support of both base and chat models; Stable support of 32K
context length for models of all sizes

SparkNLP 997 Introducing QWEN2Transformer

---

examples/python/transformers/HuggingFace in Spark NLP - ViTForImageClassification.ipynb
examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_ConvNextForImageClassification.ipynb
examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_SwinForImageClassification.ipynb
examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_ViTForImageClassification.ipynb
examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_VisionEncoderDecoderForImageCaptioning_.ipynb
examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_snowflake.ipynb
src/main/scala/com/johnsnowlabs/ml/ai/ConvNextClassifier.scala
src/main/scala/com/johnsnowlabs/ml/ai/ViTClassifier.scala
src/main/scala/com/johnsnowlabs/ml/ai/VisionEncoderDecoder.scala
src/main/scala/com/johnsnowlabs/ml/ai/XlmRoBertaClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/cv/ConvNextForImageClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/cv/SwinForImageClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/cv/ViTForImageClassification.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/cv/VisionEncoderDecoderForImageCaptioning.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/cv/VisionEncoderDecoderForImageCaptioningTestSpec.scala

This PR introduces OnnxSupport to the following Vison annotators and adds example export notebooks:
- ViTForImageClassification
- VisionEncoderDecoderForImageCaptioning
- SwinForImageClassification
- ConvNextForImageClassification

Introducing onnx support to vision annotators

---

python/sparknlp/annotator/seq2seq/__init__.py
python/sparknlp/annotator/seq2seq/starcoder_transformer.py
python/sparknlp/internal/__init__.py
python/test/annotator/seq2seq/starcoder_transformer_test.py
src/main/scala/com/johnsnowlabs/ml/ai/StarCoder.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/StarCoderTransformer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeSpecialTokens.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/StarCoderTokenizer.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/StarCoderTestSpec.scala

This PR introduces StarCoder2
This pull request adds support for the StarCoder2 model in the Spark NLP library. StarCoder2 is a Transformer model designed specifically for code generation and understanding. It features 3 billion parameters and is trained on a diverse dataset including multiple programming languages, making it highly versatile for various coding tasks. The new model provides enhanced functionality for code completion, generation, and understanding.
The inclusion of StarCoder2 addresses the need for a robust code-focused language model within Spark NLP. This model will significantly improve the library's capabilities in code generation and understanding tasks, offering developers a powerful tool for software development and data science projects.
The StarCoder2 model has …

SPARKNLP 1034 implement starcoder2 for causal lm

---

examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_LLama3.ipynb
python/sparknlp/annotator/seq2seq/__init__.py
python/sparknlp/annotator/seq2seq/llama3_transformer.py
python/sparknlp/internal/__init__.py
python/test/annotator/seq2seq/llama3_transformer_test.py
src/main/scala/com/johnsnowlabs/ml/ai/LLAMA3.scala
src/main/scala/com/johnsnowlabs/nlp/HasGeneratorProperties.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/LLAMA3Transformer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/LLAMA3Tokenizer.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/LLAMA3TestSpec.scala

This PR Integrates LLAMA 3 family models into SparkNLP
The Llama 3 release introduces a new family of pretrained and fine-tuned LLMs, ranging in scale
from 8B to 70B parameters. Llama 3 models are designed with enhanced
efficiency, performance, and safety, making them more capable than previous versions. These models
are trained on a more diverse and expansive dataset, offering improved contextual understanding 
and generation quality.
The fine-tuned models, known as Llama 3-instruct, are optimized for dialogue applications using an advanced 
version of Reinforcement Learning from Human Feedback (RLHF). Llama 3-instruct models demonstrate superior 
performance across multiple benchmarks, outperforming Llama 2 and even matching or exceeding the capabilities 
of some closed-source models.

SPARKNLP Introducing LLAMA 3

---

docs/en/annotator_entries/AutoGGUF.md
examples/python/llama.cpp/llama.cpp_in_Spark_NLP_AutoGGUFModel.ipynb
python/sparknlp/annotator/seq2seq/auto_gguf_model.py
python/test/annotator/seq2seq/auto_gguf_model_test.py
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFModel.scala

This PR fixes a critical bug when using pretrained models with AutoGGUFModels. 
The file protocol is included in the path while trying to read the model. This has been (temporarily) fixed by removing the protocol from the path string. The file should be local at this point, as it as copied to a temporary local location if it was remote.
Tests passing with pretrained models.

[SPARKNLP-1027] Fix issue with pretrained model

---

src/main/scala/com/johnsnowlabs/ml/util/ModelEngine.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFModel.scala

adding a new engine called `llama_cpp` for all the GGUF models

Add a new llama_cpp engine

---

src/main/scala/com/johnsnowlabs/ml/gguf/GGUFWrapper.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFModel.scala

This PR fixes a a bug with loading pretrained models, when running AutoGGUF model pipelines from Databricks. 
This is due to an issue, with how paths are handled when loading the gguf file. 
Tests are passing on databricks.

Fix pretrained models not being found on dbfs systems

---

examples/python/transformers/HuggingFace_in_Spark_NLP_BLIPForQuestionAnswering.ipynb
python/sparknlp/annotator/cv/__init__.py
python/sparknlp/annotator/cv/blip_for_question_answering.py
python/sparknlp/base/image_assembler.py
python/sparknlp/base/light_pipeline.py
python/sparknlp/internal/__init__.py
python/test/annotator/cv/blip_for_question_answering_test.py
src/main/scala/com/johnsnowlabs/ml/ai/BLIPClassifier.scala
src/main/scala/com/johnsnowlabs/nlp/AnnotationImage.scala
src/main/scala/com/johnsnowlabs/nlp/HasBatchedAnnotateImage.scala
src/main/scala/com/johnsnowlabs/nlp/ImageAssembler.scala
src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/cv/BLIPForQuestionAnswering.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BertTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeSpecialTokens.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/PretrainedPipeline.scala
src/test/scala/com/johnsnowlabs/nlp/AssertAnnotations.scala
src/test/scala/com/johnsnowlabs/nlp/ImageAssemblerTest.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/cv/BLIPForQuestionAnsweringTest.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/cv/CLIPForZeroShotClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/cv/ViTImageClassificationTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/cv/VisionEncoderDecoderForImageCaptioningTestSpec.scala

This pull request introduces the BLIPForQuestionAnswering transformer, enabling enhanced image-based question-answering capabilities.
Usage Instructions
To utilize this new transformer, a DataFrame with the following structure is required:
- `image` column: Contains the file paths for each image within the directory.
- `text` column: Includes the specific question you would like to ask about each corresponding image.
Enhance Spark NLP with visual transformer capabilities.
- Local Test
- Databricks notebook

[SPARKNLP-1068] Introducing BLIPForQuestionAnswering transformer

---

src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
src/test/scala/com/johnsnowlabs/nlp/AnnotationUtils.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala

Addition chunk metadata to ChunkEmbeddings output
Previously, ChunkEmbeddings would lose the data in the chunk's original metadata in the output. This PR will continue to keep that metadata in the result.
When chunks are found by NERs, we get the entity information like {"entity": "NAME"}. Losing this information makes the result of ChunkEmbeddings unusable. I am thinking of writing a new annotator that takes the result of ChunkEmbeddings as input.
I wrote a solid unit test and added a helper unit test class named AnnotationUtils.

Addition chunk metadata to ChunkEmbeddings output

---

.gitattributes

ignore html as linguist-vendored

---

docs/en/transformer_entries/OLMoTransformer.md
examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_OLMO.ipynb
python/sparknlp/annotator/seq2seq/__init__.py
python/sparknlp/annotator/seq2seq/olmo_transformer.py
python/sparknlp/internal/__init__.py
python/test/annotator/seq2seq/olmo_transformer_test.py
src/main/scala/com/johnsnowlabs/ml/ai/OLMo.scala
src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Generate.scala
src/main/scala/com/johnsnowlabs/ml/onnx/OnnxSerializeModel.scala
src/main/scala/com/johnsnowlabs/ml/onnx/OnnxWrapper.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/OLMoTransformer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeSpecialTokens.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/OLMoTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/OLMoTestSpec.scala

OLMo is a series of Open Language Models designed to enable the science of language models. The OLMo models are trained on the [Dolma](https://huggingface.co/datasets/allenai/dolma) dataset. We release all code, checkpoints, logs (coming soon), and details involved in training these models.

SPARKNLP-1006: Introducing OLMo

---

examples/python/data-preprocessing/SparkNLP_Cleaner_Demo.ipynb
examples/python/data-preprocessing/SparkNLP_Email_Data_Preparation.ipynb
examples/python/data-preprocessing/SparkNLP_Extractor_Demo.ipynb
python/sparknlp/annotator/cleaners/__init__.py
python/sparknlp/annotator/cleaners/cleaner.py
python/sparknlp/annotator/cleaners/extractor.py
python/test/annotator/cleaners/cleaner_test.py
python/test/annotator/cleaners/extractor_test.py
src/main/scala/com/johnsnowlabs/nlp/annotators/cleaners/Cleaner.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/cleaners/Extractor.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/cleaners/util/CleanerHelper.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/cleaners/CleanerTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/cleaners/ExtractorTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/cleaners/util/CleanerHelperTestSpec.scala

This PR introduces two new SparkNLP powered annotators: **Extractor** and **Cleaner**.
**Extractor Annotator:**
Enables seamless extraction of key information (e.g., dates, emails, IP addresses) from various data sources such as `.eml` files. This simplifies data parsing workflows by isolating relevant details automatically.
**Cleaner Annotator:**
Removes unnecessary or undesirable content from datasets, such as bullets, dashes, and non-ASCII characters, enhancing data consistency and readability.
These annotators are designed for scalable, high-performance data processing, leveraging Apache Spark to handle large datasets efficiently.
In many real-world NLP tasks, raw data often contains noise, such as irrelevant symbols, inconsistent formatting, or extraneous details. Similarly, …

SPARKNLP-1109 Adding Extractor to Sparknlp

---

examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_MPNetForQuestionAnswering.ipynb
examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_XlmRoBertaSentenceEmbeddings.ipynb

This PR improves the Error handling of AutoGGUF type models, as discussed in #14530. 
There was an issue with how the error propagated to the user, resulting in an empty result dataframe. 
This is now fixed. In the case of an error on the llama.cpp side, the exception will be located in the metadata of each row (field `llamacpp_exception`).
Additionally, this PR contains some other minor fixes
- Added a `setNParallel` setter, as an alias for Spark NLPs `setBatchSize`. This controls the number of parallel decodings
- Changed the default AutoGGUFEmbedding model, so that the default download does not result in  an error.
- Some unrelated fixes with some example notebooks
#14530
New and old tests are passing.

Improved Error Handling for AutoGGUF models

---

.github/workflows/build_and_test.yml

Updating python 3.7 to 3.8 for jobs spark34 and spark33 since Github Actions removed support for python 3.7
- x ] My code follows the code style of this project.

[SPARKNLP-1164] Updating python 3.7 to 3.8 for jobs spark34 and spark33

---

.github/workflows/build_and_test.yml
python/sparknlp/reader/enums.py
python/sparknlp/reader/pdf_to_text.py
src/main/scala/com/johnsnowlabs/reader/PdfToText.scala
src/main/scala/com/johnsnowlabs/reader/SparkNLPReader.scala
src/main/scala/com/johnsnowlabs/reader/util/pdf/Enums.scala
src/main/scala/com/johnsnowlabs/reader/util/pdf/PDFLayoutTextStripper.java
src/main/scala/com/johnsnowlabs/reader/util/pdf/schema/MappingMatrix.scala
src/main/scala/com/johnsnowlabs/reader/util/pdf/schema/PageMatrix.scala
src/test/resources/reader/pdf/unsorted_text.pdf
src/test/scala/com/johnsnowlabs/reader/PdfToTextTest.scala

- Adding `splitPage` parameter to identify the correct number of pages
- Adding `onlyPageNum` parameter to display only the number of pages of the document
- Adding `textStripper` parameter used for output layout and formatting
- Adding `sort` parameter to enable or disable sorting lines
Enhancing PDF reader with additional features

Sparknlp-1158 Adding Parameters Options to PDF Reader

---

docs/en/transformer_entries/InternVLForMultiModal.md
examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_InternVLForMultiModal.ipynb
python/sparknlp/annotator/cv/__init__.py
python/sparknlp/annotator/cv/internvl_for_multimodal.py
python/sparknlp/internal/__init__.py
python/test/annotator/cv/internvl_for_multimodal_test.py
src/main/scala/com/johnsnowlabs/ml/ai/InternVL.scala
src/main/scala/com/johnsnowlabs/ml/openvino/OpenvinoWrapper.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/cv/InternVLForMultiModal.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/cv/util/transform/InternVLUtils.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/InternVLTokenizer.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/cv/InternVLForMultiModalTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/cv/feature_extractor/InternVLUtilsTestSpec.scala

This pull request introduces support for the `InternVLForMultiModal` model, a multimodal large language model designed for visual question answering. The changes include the addition of a new annotator, utility functions for image preprocessing, and test cases to validate functionality. This annotator can load InternVL 2, 2.5 and 3 family of models.

SparkNLP - 1123 Introducing InternVL

---

src/main/scala/com/johnsnowlabs/partition/BasicChunker.scala
src/main/scala/com/johnsnowlabs/partition/Chunk.scala
src/main/scala/com/johnsnowlabs/partition/SemanticChunker.scala
src/main/scala/com/johnsnowlabs/partition/TitleChunker.scala
src/test/scala/com/johnsnowlabs/partition/PartitionChunkerTest.scala
src/test/scala/com/johnsnowlabs/partition/PartitionTransformerTest.scala
src/test/scala/com/johnsnowlabs/partition/TitleChunkerTest.scala

This PR enhances Partition features by adding chunking ByTitle. This logic support more advanced chunking strategies such as:
- Soft Chunking Limit (newAfterNChars): Allows early section breaks before maxCharacters threshold.
- Contextual Overlap (overlapAll): Adds trailing context from the previous chunk to the next for better semantic continuity.
- Page Boundary Splitting: Respects pageNumber metadata and starts a new section when a page changes.
- Title Inclusion Behavior: Ensures titles are embedded within the following content instead of forming isolated chunks.

[SPARKNLP-1163] Adding title chunking strategy

---

src/main/scala/com/johnsnowlabs/client/CloudResources.scala
src/main/scala/com/johnsnowlabs/client/azure/AzureClient.scala
src/main/scala/com/johnsnowlabs/client/azure/AzureGateway.scala
src/main/scala/com/johnsnowlabs/client/util/CloudHelper.scala
src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala

Enhance Microsoft Fabric Support by adding the capability to download models from lakehouse containers in Microsoft Fabric.
Currently, Microsoft Fabric raises an error when attempting to download a model that is defined in a lakehouse container via the cache path. This limitation hinders users from managing and retrieving their models efficiently in lakehouse environments.
Microsoft Fabric notebooks with `cache_folder` i.e.
```json
%%configure -f
{
"conf": {
"spark.jsl.settings.pretrained.cache_folder": "abfss://my_workspace@onelake.dfs.fabric.microsoft.com/lakehouse_folder.Lakehouse/Files/my_models"
}
}
```

[SPARKNLP-1215] Updating support for Microsoft Fabric

---

python/sparknlp/partition/partition_properties.py
python/test/reader/reader2doc_test.py
python/test/reader/reader2table_test.py
src/main/scala/com/johnsnowlabs/partition/HasReaderProperties.scala
src/main/scala/com/johnsnowlabs/reader/HasReaderContent.scala
src/main/scala/com/johnsnowlabs/reader/Reader2Doc.scala
src/main/scala/com/johnsnowlabs/reader/Reader2Table.scala
src/main/scala/com/johnsnowlabs/reader/util/HTMLParser.scala
src/test/scala/com/johnsnowlabs/reader/Reader2DocTest.scala
src/test/scala/com/johnsnowlabs/reader/Reader2TableTest.scala

**Please merge before https://github.com/JohnSnowLabs/spark-nlp/pull/14668**
This change enables readers to accept a column of type String as input (in addition to existing types), so you can provide raw text directly rather than only files or external sources.
Before this patch, Spark NLP readers only supported inputs via file paths. That means if you already had a DataFrame with text content (say from another pipeline or a preliminary load), you had to write it to disk just to let the reader ingest it. This adds friction and overhead, especially in streaming or in-memory pipelines.
With this change, you can:
- Feed raw text stored in a DataFrame column directly into Spark NLP readers — zero I/O overhead when not needed.
- Simplify workflows and pipelines (no need for temporary file …

[SPARKNLP-1291] Adding support fort input string column on readers

---

build.sbt
project/Dependencies.scala
src/main/scala/com/johnsnowlabs/reader/XMLReader.scala
src/test/scala/com/johnsnowlabs/reader/Reader2DocTest.scala
src/test/scala/com/johnsnowlabs/reader/XMLReaderTest.scala

This change introduces fault-tolerant processing when encountering malformed XML inputs, allowing the XML reader to continue gracefully rather than failing entirely. 
Key changes include:
- Enhance the XML parsing logic to catch and skip over malformed segments (e.g. mismatched tags, invalid characters) instead of throwing fatal exceptions.
- Augment unit tests to cover a variety of malformed-XML scenarios (broken tags, missing closures, embedded invalid characters).
In real-world datasets, XML files are often imperfect: missing closing tags, unexpected characters, truncated fragments, or encoding issues. Without robust handling, a single malformed file or even a small malformed portion can break an entire ingestion pipeline, requiring manual cleanup or pre-validation steps.
With this …

[SPARKNLP-1292] Adding fault-tolerance support for malformed XML

---

src/main/scala/com/johnsnowlabs/nlp/ParamsAndFeaturesReadable.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFModel.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFReranker.scala
src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFVisionModel.scala
src/main/scala/com/johnsnowlabs/nlp/embeddings/AutoGGUFEmbeddings.scala
src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFRerankerTest.scala
src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFVisionModelTestSpec.scala
src/test/scala/com/johnsnowlabs/nlp/embeddings/AutoGGUFEmbeddingsTestSpec.scala

Trying to call .pretrained() on any GGUF- Model/Emedding / Reranker etc..   in databricks, gives exception, i.e. run 
```python
from sparknlp.annotator import AutoGGUFModel
AutoGGUFModel.pretrained("Phi_4_mini_instruct_Q4_K_M_gguf")
```
gives gives the following error:
```scala
ini_instruct_Q4_K_M_gguf download started this may take some time.
Approximate size to download 2.3 GB
[ | ]
An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: java.io.FileNotFoundException: file or folder: file:/root/cache_pretrained/Phi_4_mini_instruct_Q4_K_M_gguf_en_6.1.1_3.0_1754317230916 not found
at com.johnsnowlabs.nlp.util.io.ResourceHelper$SourceStream.<init>(ResourceHelper.scala:112)
at com.johnsnowlabs.nlp.util.io.ResourceHelper$.copyToLocal(Resourc …
```

fix duplicate loading in FeaturesFallbackReader
